// Process Image File
// Generated by CANopen Architect Professional 11.62.6737 on 5/24/2026 11:26:11 AM
// Generated from project E:\ursaScience\Modules\Modules-1000kbs.cax
// Generated from EDS 'PH-TempModule-n04-250kbs' 05-24-2026 11:25AM by Dakota Ward
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _PIMGH_
#define _PIMGH_

// EDS configuration usage
// 1 = configuration was used when this file was generated
#define EDSCONFIGURATION_ALL_ENTRIES 1

// EDS group usage
// 1 = group was used when this file was generated

// set to 1 to use this stack config
#define AUTO_GENERATED_STACK_CONFIG 1

#if (AUTO_GENERATED_STACK_CONFIG == 1)
// stack configuration

// if no stack version defined then assume version 5.xx
#ifndef _MCOPVERSION_
#define _MCOPVERSION_ 5
#endif

// Maximum number of receive PDOs
#define NR_OF_RPDOS       1

// Maximum number of transmit PDOs
#define NR_OF_TPDOS       2

// Default Node ID of this node
#if _MCOPVERSION_ >= 6
#define NODEID_DCF         0x04
#define DEFAULT_EMCY_COBID 0x00000080L + NODEID_DCF
#else
#define NODE_ID            0x04
#define DEFAULT_EMCY_COBID 0x00000080L + NODE_ID
#endif

// device type
#define OD_DEVICE_TYPE    0x00000404L

// Identity Object data [1018]
// Note: the values in Device -> Information are not used for this piece of code,
// only the values in [1018] are used
#define OD_VENDOR_ID      0x00000123L
#define OD_PRODUCT_CODE   0x00000004L
#define OD_REVISION       0x00010001L
#define OD_SERIAL_NUMBER  0x00123457L

// Specify the default heartbeat here
#define DEFAULT_HEARTBEAT 1000

// Defines the maximum number of heartbeat consumers
#define NR_OF_HB_CONSUMER 1

// Defines the maximum number of emergency consumers
#define NR_OF_EMCY_CONSUMERS 1

// Defines the emergency inhibit time (x100us)
#define EMCY_INHIBIT_TIME 0

#endif // AUTO_GENERATED_STACK_CONFIG == 1

// [6040,00] Unsigned16
#define P604000_ControlWord 0x00000000
#define PControlWord_604000 P604000_ControlWord
#define P604000 P604000_ControlWord
#define P0x60400x00 P604000_ControlWord
// The uppercase versions are deprecated
#define P604000_CONTROLWORD P604000_ControlWord
#define PCONTROLWORD_604000 P604000_ControlWord
// [6000,00] Unsigned16
#define P600000_pHValue 0x00000004
#define PpHValue_600000 P600000_pHValue
#define P600000 P600000_pHValue
#define P0x60000x00 P600000_pHValue
// The uppercase versions are deprecated
#define P600000_PHVALUE P600000_pHValue
#define PPHVALUE_600000 P600000_pHValue
// [6010,00] Integer16
#define P601000_Temperature 0x00000006
#define PTemperature_601000 P601000_Temperature
#define P601000 P601000_Temperature
#define P0x60100x00 P601000_Temperature
// The uppercase versions are deprecated
#define P601000_TEMPERATURE P601000_Temperature
#define PTEMPERATURE_601000 P601000_Temperature
// [6003,00] Unsigned16
#define P600300_pHMillivolts 0x00000008
#define PpHMillivolts_600300 P600300_pHMillivolts
#define P600300 P600300_pHMillivolts
#define P0x60030x00 P600300_pHMillivolts
// The uppercase versions are deprecated
#define P600300_PHMILLIVOLTS P600300_pHMillivolts
#define PPHMILLIVOLTS_600300 P600300_pHMillivolts
// [2300,00] Unsigned8
#define P230000_SensorStatus 0x0000000C
#define PSensorStatus_230000 P230000_SensorStatus
#define P230000 P230000_SensorStatus
#define P0x23000x00 P230000_SensorStatus
// The uppercase versions are deprecated
#define P230000_SENSORSTATUS P230000_SensorStatus
#define PSENSORSTATUS_230000 P230000_SensorStatus
// [6001,00] Unsigned8
#define P600100_pHSignalQuality 0x0000000D
#define PpHSignalQuality_600100 P600100_pHSignalQuality
#define P600100 P600100_pHSignalQuality
#define P0x60010x00 P600100_pHSignalQuality
// The uppercase versions are deprecated
#define P600100_PHSIGNALQUALITY P600100_pHSignalQuality
#define PPHSIGNALQUALITY_600100 P600100_pHSignalQuality
// [6011,00] Unsigned8
#define P601100_TempSignalQuality 0x0000000E
#define PTempSignalQuality_601100 P601100_TempSignalQuality
#define P601100 P601100_TempSignalQuality
#define P0x60110x00 P601100_TempSignalQuality
// The uppercase versions are deprecated
#define P601100_TEMPSIGNALQUALITY P601100_TempSignalQuality
#define PTEMPSIGNALQUALITY_601100 P601100_TempSignalQuality
// [1001,00] Unsigned8
#define P100100_Error_Register 0x0000000F
#define PError_Register_100100 P100100_Error_Register
#define P100100 P100100_Error_Register
#define P0x10010x00 P100100_Error_Register
// The uppercase versions are deprecated
#define P100100_ERROR_REGISTER P100100_Error_Register
#define PERROR_REGISTER_100100 P100100_Error_Register
// [1002,00] Unsigned32
#define P100200_Manufacturer_Status_Register 0x00000010
#define PManufacturer_Status_Register_100200 P100200_Manufacturer_Status_Register
#define P100200 P100200_Manufacturer_Status_Register
#define P0x10020x00 P100200_Manufacturer_Status_Register
// The uppercase versions are deprecated
#define P100200_MANUFACTURER_STATUS_REGISTER P100200_Manufacturer_Status_Register
#define PMANUFACTURER_STATUS_REGISTER_100200 P100200_Manufacturer_Status_Register
// [1006,00] Unsigned32
#define P100600_Communication_Cycle_Period 0x00000014
#define PCommunication_Cycle_Period_100600 P100600_Communication_Cycle_Period
#define P100600 P100600_Communication_Cycle_Period
#define P0x10060x00 P100600_Communication_Cycle_Period
// The uppercase versions are deprecated
#define P100600_COMMUNICATION_CYCLE_PERIOD P100600_Communication_Cycle_Period
#define PCOMMUNICATION_CYCLE_PERIOD_100600 P100600_Communication_Cycle_Period
// [1007,00] Unsigned32
#define P100700_Synchronous_Window_Length 0x00000018
#define PSynchronous_Window_Length_100700 P100700_Synchronous_Window_Length
#define P100700 P100700_Synchronous_Window_Length
#define P0x10070x00 P100700_Synchronous_Window_Length
// The uppercase versions are deprecated
#define P100700_SYNCHRONOUS_WINDOW_LENGTH P100700_Synchronous_Window_Length
#define PSYNCHRONOUS_WINDOW_LENGTH_100700 P100700_Synchronous_Window_Length
// [1008,00] VisibleString
#define P100800_Manufacturer_Device_Name 0x0000001C
#define PManufacturer_Device_Name_100800 P100800_Manufacturer_Device_Name
#define P100800 P100800_Manufacturer_Device_Name
#define P0x10080x00 P100800_Manufacturer_Device_Name
// The uppercase versions are deprecated
#define P100800_MANUFACTURER_DEVICE_NAME P100800_Manufacturer_Device_Name
#define PMANUFACTURER_DEVICE_NAME_100800 P100800_Manufacturer_Device_Name
// [1009,00] VisibleString
#define P100900_Manufacturer_Hardware_Version 0x00000035
#define PManufacturer_Hardware_Version_100900 P100900_Manufacturer_Hardware_Version
#define P100900 P100900_Manufacturer_Hardware_Version
#define P0x10090x00 P100900_Manufacturer_Hardware_Version
// The uppercase versions are deprecated
#define P100900_MANUFACTURER_HARDWARE_VERSION P100900_Manufacturer_Hardware_Version
#define PMANUFACTURER_HARDWARE_VERSION_100900 P100900_Manufacturer_Hardware_Version
// [100A,00] VisibleString
#define P100A00_Manufacturer_Software_Version 0x00000038
#define PManufacturer_Software_Version_100A00 P100A00_Manufacturer_Software_Version
#define P100A00 P100A00_Manufacturer_Software_Version
#define P0x100A0x00 P100A00_Manufacturer_Software_Version
// The uppercase versions are deprecated
#define P100A00_MANUFACTURER_SOFTWARE_VERSION P100A00_Manufacturer_Software_Version
#define PMANUFACTURER_SOFTWARE_VERSION_100A00 P100A00_Manufacturer_Software_Version
// [1012,00] Unsigned32
#define P101200_Time_Stamp_COB_ID 0x0000003B
#define PTime_Stamp_COB_ID_101200 P101200_Time_Stamp_COB_ID
#define P101200 P101200_Time_Stamp_COB_ID
#define P0x10120x00 P101200_Time_Stamp_COB_ID
// The uppercase versions are deprecated
#define P101200_TIME_STAMP_COB_ID P101200_Time_Stamp_COB_ID
#define PTIME_STAMP_COB_ID_101200 P101200_Time_Stamp_COB_ID
// [1013,00] Unsigned32
#define P101300_High_Resolution_Time_Stamp 0x0000003F
#define PHigh_Resolution_Time_Stamp_101300 P101300_High_Resolution_Time_Stamp
#define P101300 P101300_High_Resolution_Time_Stamp
#define P0x10130x00 P101300_High_Resolution_Time_Stamp
// The uppercase versions are deprecated
#define P101300_HIGH_RESOLUTION_TIME_STAMP P101300_High_Resolution_Time_Stamp
#define PHIGH_RESOLUTION_TIME_STAMP_101300 P101300_High_Resolution_Time_Stamp
// [1018,01] Unsigned32
#define P101801_Vendor_ID 0x00000043
#define PVendor_ID_101801 P101801_Vendor_ID
#define P101801 P101801_Vendor_ID
#define P0x10180x01 P101801_Vendor_ID
// The uppercase versions are deprecated
#define P101801_VENDOR_ID P101801_Vendor_ID
#define PVENDOR_ID_101801 P101801_Vendor_ID
// [1018,02] Unsigned32
#define P101802_Product_Code 0x00000047
#define PProduct_Code_101802 P101802_Product_Code
#define P101802 P101802_Product_Code
#define P0x10180x02 P101802_Product_Code
// The uppercase versions are deprecated
#define P101802_PRODUCT_CODE P101802_Product_Code
#define PPRODUCT_CODE_101802 P101802_Product_Code
// [1018,03] Unsigned32
#define P101803_Revision_Number 0x0000004B
#define PRevision_Number_101803 P101803_Revision_Number
#define P101803 P101803_Revision_Number
#define P0x10180x03 P101803_Revision_Number
// The uppercase versions are deprecated
#define P101803_REVISION_NUMBER P101803_Revision_Number
#define PREVISION_NUMBER_101803 P101803_Revision_Number
// [1018,04] Unsigned32
#define P101804_Serial_Number 0x0000004F
#define PSerial_Number_101804 P101804_Serial_Number
#define P101804 P101804_Serial_Number
#define P0x10180x04 P101804_Serial_Number
// The uppercase versions are deprecated
#define P101804_SERIAL_NUMBER P101804_Serial_Number
#define PSERIAL_NUMBER_101804 P101804_Serial_Number
// [1020,01] Unsigned32
#define P102001_Configuration_Date 0x00000053
#define PConfiguration_Date_102001 P102001_Configuration_Date
#define P102001 P102001_Configuration_Date
#define P0x10200x01 P102001_Configuration_Date
// The uppercase versions are deprecated
#define P102001_CONFIGURATION_DATE P102001_Configuration_Date
#define PCONFIGURATION_DATE_102001 P102001_Configuration_Date
// [1020,02] Unsigned32
#define P102002_Configuration_Time 0x00000057
#define PConfiguration_Time_102002 P102002_Configuration_Time
#define P102002 P102002_Configuration_Time
#define P0x10200x02 P102002_Configuration_Time
// The uppercase versions are deprecated
#define P102002_CONFIGURATION_TIME P102002_Configuration_Time
#define PCONFIGURATION_TIME_102002 P102002_Configuration_Time
// [1200,01] Unsigned32
#define P120001_COB_ID_Client_to_Server 0x0000005B
#define PCOB_ID_Client_to_Server_120001 P120001_COB_ID_Client_to_Server
#define P120001 P120001_COB_ID_Client_to_Server
#define P0x12000x01 P120001_COB_ID_Client_to_Server
// The uppercase versions are deprecated
#define P120001_COB_ID_CLIENT_TO_SERVER P120001_COB_ID_Client_to_Server
#define PCOB_ID_CLIENT_TO_SERVER_120001 P120001_COB_ID_Client_to_Server
// [1200,02] Unsigned32
#define P120002_COB_ID_Server_to_Client 0x0000005F
#define PCOB_ID_Server_to_Client_120002 P120002_COB_ID_Server_to_Client
#define P120002 P120002_COB_ID_Server_to_Client
#define P0x12000x02 P120002_COB_ID_Server_to_Client
// The uppercase versions are deprecated
#define P120002_COB_ID_SERVER_TO_CLIENT P120002_COB_ID_Server_to_Client
#define PCOB_ID_SERVER_TO_CLIENT_120002 P120002_COB_ID_Server_to_Client
// [2000,00] Unsigned8
#define P200000_LEDControl 0x00000063
#define PLEDControl_200000 P200000_LEDControl
#define P200000 P200000_LEDControl
#define P0x20000x00 P200000_LEDControl
// The uppercase versions are deprecated
#define P200000_LEDCONTROL P200000_LEDControl
#define PLEDCONTROL_200000 P200000_LEDControl
// [2200,00] Unsigned8
#define P220000_pHCalibrationCommand 0x00000064
#define PpHCalibrationCommand_220000 P220000_pHCalibrationCommand
#define P220000 P220000_pHCalibrationCommand
#define P0x22000x00 P220000_pHCalibrationCommand
// The uppercase versions are deprecated
#define P220000_PHCALIBRATIONCOMMAND P220000_pHCalibrationCommand
#define PPHCALIBRATIONCOMMAND_220000 P220000_pHCalibrationCommand
// [2201,00] Unsigned8
#define P220100_pHCalibrationStatus 0x00000065
#define PpHCalibrationStatus_220100 P220100_pHCalibrationStatus
#define P220100 P220100_pHCalibrationStatus
#define P0x22010x00 P220100_pHCalibrationStatus
// The uppercase versions are deprecated
#define P220100_PHCALIBRATIONSTATUS P220100_pHCalibrationStatus
#define PPHCALIBRATIONSTATUS_220100 P220100_pHCalibrationStatus
// [2202,00] Integer16
#define P220200_CalibrationBuffer4 0x00000066
#define PCalibrationBuffer4_220200 P220200_CalibrationBuffer4
#define P220200 P220200_CalibrationBuffer4
#define P0x22020x00 P220200_CalibrationBuffer4
// The uppercase versions are deprecated
#define P220200_CALIBRATIONBUFFER4 P220200_CalibrationBuffer4
#define PCALIBRATIONBUFFER4_220200 P220200_CalibrationBuffer4
// [2203,00] Integer16
#define P220300_CalibrationBuffer7 0x00000068
#define PCalibrationBuffer7_220300 P220300_CalibrationBuffer7
#define P220300 P220300_CalibrationBuffer7
#define P0x22030x00 P220300_CalibrationBuffer7
// The uppercase versions are deprecated
#define P220300_CALIBRATIONBUFFER7 P220300_CalibrationBuffer7
#define PCALIBRATIONBUFFER7_220300 P220300_CalibrationBuffer7
// [2204,00] Integer16
#define P220400_CalibrationBuffer10 0x0000006A
#define PCalibrationBuffer10_220400 P220400_CalibrationBuffer10
#define P220400 P220400_CalibrationBuffer10
#define P0x22040x00 P220400_CalibrationBuffer10
// The uppercase versions are deprecated
#define P220400_CALIBRATIONBUFFER10 P220400_CalibrationBuffer10
#define PCALIBRATIONBUFFER10_220400 P220400_CalibrationBuffer10
// [2205,00] Unsigned8
#define P220500_pHCalibrationMode 0x0000006C
#define PpHCalibrationMode_220500 P220500_pHCalibrationMode
#define P220500 P220500_pHCalibrationMode
#define P0x22050x00 P220500_pHCalibrationMode
// The uppercase versions are deprecated
#define P220500_PHCALIBRATIONMODE P220500_pHCalibrationMode
#define PPHCALIBRATIONMODE_220500 P220500_pHCalibrationMode
// [2210,00] Integer16
#define P221000_TempOffset 0x0000006D
#define PTempOffset_221000 P221000_TempOffset
#define P221000 P221000_TempOffset
#define P0x22100x00 P221000_TempOffset
// The uppercase versions are deprecated
#define P221000_TEMPOFFSET P221000_TempOffset
#define PTEMPOFFSET_221000 P221000_TempOffset
// [2220,00] Unsigned8
#define P222000_pHElectrodeStatus 0x0000006F
#define PpHElectrodeStatus_222000 P222000_pHElectrodeStatus
#define P222000 P222000_pHElectrodeStatus
#define P0x22200x00 P222000_pHElectrodeStatus
// The uppercase versions are deprecated
#define P222000_PHELECTRODESTATUS P222000_pHElectrodeStatus
#define PPHELECTRODESTATUS_222000 P222000_pHElectrodeStatus
// [2221,00] Unsigned16
#define P222100_ElectrodeAge 0x00000070
#define PElectrodeAge_222100 P222100_ElectrodeAge
#define P222100 P222100_ElectrodeAge
#define P0x22210x00 P222100_ElectrodeAge
// The uppercase versions are deprecated
#define P222100_ELECTRODEAGE P222100_ElectrodeAge
#define PELECTRODEAGE_222100 P222100_ElectrodeAge
// [2222,00] Unsigned32
#define P222200_LastCalibrationDate 0x00000072
#define PLastCalibrationDate_222200 P222200_LastCalibrationDate
#define P222200 P222200_LastCalibrationDate
#define P0x22220x00 P222200_LastCalibrationDate
// The uppercase versions are deprecated
#define P222200_LASTCALIBRATIONDATE P222200_LastCalibrationDate
#define PLASTCALIBRATIONDATE_222200 P222200_LastCalibrationDate
// [2400,00] Unsigned16
#define P240000_pHDeltaThreshold 0x00000076
#define PpHDeltaThreshold_240000 P240000_pHDeltaThreshold
#define P240000 P240000_pHDeltaThreshold
#define P0x24000x00 P240000_pHDeltaThreshold
// The uppercase versions are deprecated
#define P240000_PHDELTATHRESHOLD P240000_pHDeltaThreshold
#define PPHDELTATHRESHOLD_240000 P240000_pHDeltaThreshold
// [2401,00] Integer16
#define P240100_TempDeltaTheshold 0x00000078
#define PTempDeltaTheshold_240100 P240100_TempDeltaTheshold
#define P240100 P240100_TempDeltaTheshold
#define P0x24010x00 P240100_TempDeltaTheshold
// The uppercase versions are deprecated
#define P240100_TEMPDELTATHESHOLD P240100_TempDeltaTheshold
#define PTEMPDELTATHESHOLD_240100 P240100_TempDeltaTheshold
// [2402,00] Unsigned8
#define P240200_StatusDeltaThreshold 0x0000007A
#define PStatusDeltaThreshold_240200 P240200_StatusDeltaThreshold
#define P240200 P240200_StatusDeltaThreshold
#define P0x24020x00 P240200_StatusDeltaThreshold
// The uppercase versions are deprecated
#define P240200_STATUSDELTATHRESHOLD P240200_StatusDeltaThreshold
#define PSTATUSDELTATHRESHOLD_240200 P240200_StatusDeltaThreshold
// [6002,00] Unsigned8
#define P600200_pHSensorStatus 0x0000007B
#define PpHSensorStatus_600200 P600200_pHSensorStatus
#define P600200 P600200_pHSensorStatus
#define P0x60020x00 P600200_pHSensorStatus
// The uppercase versions are deprecated
#define P600200_PHSENSORSTATUS P600200_pHSensorStatus
#define PPHSENSORSTATUS_600200 P600200_pHSensorStatus
// [6012,00] Unsigned8
#define P601200_TempSensorStatus 0x0000007C
#define PTempSensorStatus_601200 P601200_TempSensorStatus
#define P601200 P601200_TempSensorStatus
#define P0x60120x00 P601200_TempSensorStatus
// The uppercase versions are deprecated
#define P601200_TEMPSENSORSTATUS P601200_TempSensorStatus
#define PTEMPSENSORSTATUS_601200 P601200_TempSensorStatus
// [6041,00] Unsigned16
#define P604100_StatusWord 0x0000007D
#define PStatusWord_604100 P604100_StatusWord
#define P604100 P604100_StatusWord
#define P0x60410x00 P604100_StatusWord
// The uppercase versions are deprecated
#define P604100_STATUSWORD P604100_StatusWord
#define PSTATUSWORD_604100 P604100_StatusWord

// last byte used in process image
#define PIMGEND 0x0000007E

// sizes for entries in the process image in bytes
#define SIZEOF_6040_00_CONTROLWORD 2
#define SIZEOF_6000_00_PHVALUE 2
#define SIZEOF_6010_00_TEMPERATURE 2
#define SIZEOF_6003_00_PHMILLIVOLTS 2
#define SIZEOF_2300_00_SENSORSTATUS 1
#define SIZEOF_6001_00_PHSIGNALQUALITY 1
#define SIZEOF_6011_00_TEMPSIGNALQUALITY 1
#define SIZEOF_1001_00_ERROR_REGISTER 1
#define SIZEOF_1002_00_MANUFACTURER_STATUS_REGISTER 4
#define SIZEOF_1006_00_COMMUNICATION_CYCLE_PERIOD 4
#define SIZEOF_1007_00_SYNCHRONOUS_WINDOW_LENGTH 4
#define SIZEOF_1008_00_MANUFACTURER_DEVICE_NAME 25
#define SIZEOF_1009_00_MANUFACTURER_HARDWARE_VERSION 3
#define SIZEOF_100A_00_MANUFACTURER_SOFTWARE_VERSION 3
#define SIZEOF_1012_00_TIME_STAMP_COB_ID 4
#define SIZEOF_1013_00_HIGH_RESOLUTION_TIME_STAMP 4
#define SIZEOF_1018_01_VENDOR_ID 4
#define SIZEOF_1018_02_PRODUCT_CODE 4
#define SIZEOF_1018_03_REVISION_NUMBER 4
#define SIZEOF_1018_04_SERIAL_NUMBER 4
#define SIZEOF_1020_01_CONFIGURATION_DATE 4
#define SIZEOF_1020_02_CONFIGURATION_TIME 4
#define SIZEOF_1200_01_COB_ID_CLIENT_TO_SERVER 4
#define SIZEOF_1200_02_COB_ID_SERVER_TO_CLIENT 4
#define SIZEOF_2000_00_LEDCONTROL 1
#define SIZEOF_2200_00_PHCALIBRATIONCOMMAND 1
#define SIZEOF_2201_00_PHCALIBRATIONSTATUS 1
#define SIZEOF_2202_00_CALIBRATIONBUFFER4 2
#define SIZEOF_2203_00_CALIBRATIONBUFFER7 2
#define SIZEOF_2204_00_CALIBRATIONBUFFER10 2
#define SIZEOF_2205_00_PHCALIBRATIONMODE 1
#define SIZEOF_2210_00_TEMPOFFSET 2
#define SIZEOF_2220_00_PHELECTRODESTATUS 1
#define SIZEOF_2221_00_ELECTRODEAGE 2
#define SIZEOF_2222_00_LASTCALIBRATIONDATE 4
#define SIZEOF_2400_00_PHDELTATHRESHOLD 2
#define SIZEOF_2401_00_TEMPDELTATHESHOLD 2
#define SIZEOF_2402_00_STATUSDELTATHRESHOLD 1
#define SIZEOF_6002_00_PHSENSORSTATUS 1
#define SIZEOF_6012_00_TEMPSENSORSTATUS 1
#define SIZEOF_6041_00_STATUSWORD 2

// default values for process image
#define PIMGDEFAULTS { \
/*[6040,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[6000,00]*/        0xBC, 0x02, \
/*[6010,00]*/        0xFA, 0x00, \
/*[6003,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[2300,00]*/        0x00, \
/*[6001,00]*/        0x64, \
/*[6011,00]*/        0x64, \
/*[1001,00]*/        0x00, \
/*[1002,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1006,00]*/        0xA0, 0x86, 0x01, 0x00, \
/*[1007,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x70, 0x48, 0x20, 0x61, 0x6E, 0x64, 0x20, 0x54, 0x65, 0x6D, \
                     0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x20, 0x4D, \
                     0x6F, 0x64, 0x75, 0x6C, 0x65, \
/*[1009,00]*/        0x31, 0x2E, 0x30, \
/*[100A,00]*/        0x31, 0x2E, 0x30, \
/*[1012,00]*/        0x00, 0x01, 0x00, 0x00, \
/*[1013,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x23, 0x01, 0x00, 0x00, \
/*[1018,02]*/        0x04, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x01, 0x00, 0x01, 0x00, \
/*[1018,04]*/        0x57, 0x34, 0x12, 0x00, \
/*[1020,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[2200,00]*/        0x00, \
/*[2201,00]*/        0x00, \
/*[2202,00]*/        0xEE, 0x06, \
/*[2203,00]*/        0x00, 0x00, \
/*[2204,00]*/        0x12, 0xF9, \
/*[2205,00]*/        0x00, \
/*[2210,00]*/        0x00, 0x00, \
/*[2220,00]*/        0x00, \
/*[2221,00]*/        0x00, 0x00, \
/*[2222,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[2400,00]*/        0x0A, 0x00, \
/*[2401,00]*/        0x05, 0x00, \
/*[2402,00]*/        0x01, \
/*[6002,00]*/        0x00, \
/*[6012,00]*/        0x00, \
/*[6041,00]*/        0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGDEFAULTS 

// minimum values for process image
#define PIMGMINS { \
/*[6040,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[6000,00]*/        0x00, 0x00, \
/*[6010,00]*/        0x00, 0x00, \
/*[6003,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[2300,00]*/        0x00, \
/*[6001,00]*/        0x00, \
/*[6011,00]*/        0x00, \
/*[1001,00]*/        0x00, \
/*[1002,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1006,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1007,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1009,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[100A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1012,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1013,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[2200,00]*/        0x00, \
/*[2201,00]*/        0x00, \
/*[2202,00]*/        0x00, 0x00, \
/*[2203,00]*/        0x00, 0x00, \
/*[2204,00]*/        0x00, 0x00, \
/*[2205,00]*/        0x00, \
/*[2210,00]*/        0x00, 0x00, \
/*[2220,00]*/        0x00, \
/*[2221,00]*/        0x00, 0x00, \
/*[2222,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[2400,00]*/        0x00, 0x00, \
/*[2401,00]*/        0x00, 0x00, \
/*[2402,00]*/        0x00, \
/*[6002,00]*/        0x00, \
/*[6012,00]*/        0x00, \
/*[6041,00]*/        0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMINS 

// maximum values for process image
#define PIMGMAXS { \
/*[6040,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[6000,00]*/        0x00, 0x00, \
/*[6010,00]*/        0x00, 0x00, \
/*[6003,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[2300,00]*/        0x00, \
/*[6001,00]*/        0x00, \
/*[6011,00]*/        0x00, \
/*[1001,00]*/        0x00, \
/*[1002,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1006,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1007,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1009,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[100A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1012,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1013,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[2200,00]*/        0x00, \
/*[2201,00]*/        0x00, \
/*[2202,00]*/        0x00, 0x00, \
/*[2203,00]*/        0x00, 0x00, \
/*[2204,00]*/        0x00, 0x00, \
/*[2205,00]*/        0x00, \
/*[2210,00]*/        0x00, 0x00, \
/*[2220,00]*/        0x00, \
/*[2221,00]*/        0x00, 0x00, \
/*[2222,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[2400,00]*/        0x00, 0x00, \
/*[2401,00]*/        0x00, 0x00, \
/*[2402,00]*/        0x00, \
/*[6002,00]*/        0x00, \
/*[6012,00]*/        0x00, \
/*[6041,00]*/        0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMAXS 

// Example usage: PIMG_OFFSET(0x1000, 0x00)
#define PIMG_OFFSET(index, subindex) P##index##subindex

#endif // _PIMGH_
