// Process Image File
// Generated by CANopen Architect Professional 11.62.6737 on 9/30/2026 12:38:14 PM
// Generated from project E:\ursaScience\Modules\Modules-base.cax
// Generated from EDS 'PH-TempModule-n04-250kbs' 09-30-2026 12:26PM by Dakota Ward
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _PIMGH_
#define _PIMGH_

// EDS configuration usage
// 1 = configuration was used when this file was generated
#define EDSCONFIGURATION_ALL_ENTRIES 1

// EDS group usage
// 1 = group was used when this file was generated

// set to 1 to use this stack config
#define AUTO_GENERATED_STACK_CONFIG 1

#if (AUTO_GENERATED_STACK_CONFIG == 1)
// stack configuration

// if no stack version defined then assume version 5.xx
#ifndef _MCOPVERSION_
#define _MCOPVERSION_ 5
#endif

// Maximum number of receive PDOs
#define NR_OF_RPDOS       1

// Maximum number of transmit PDOs
#define NR_OF_TPDOS       2

// Default Node ID of this node
#if _MCOPVERSION_ >= 6
#define NODEID_DCF         0x04
#define DEFAULT_EMCY_COBID 0x00000080L + NODEID_DCF
#else
#define NODE_ID            0x04
#define DEFAULT_EMCY_COBID 0x00000080L + NODE_ID
#endif

// device type
#define OD_DEVICE_TYPE    0x00000404L

// Identity Object data [1018]
// Note: the values in Device -> Information are not used for this piece of code,
// only the values in [1018] are used
#define OD_VENDOR_ID      0x00000123L
#define OD_PRODUCT_CODE   0x00000004L
#define OD_REVISION       0x00020000L
#define OD_SERIAL_NUMBER  0x00123457L

// Specify the default heartbeat here
#define DEFAULT_HEARTBEAT 1000

// Defines the maximum number of heartbeat consumers
#define NR_OF_HB_CONSUMER 1

// Defines the maximum number of emergency consumers
#define NR_OF_EMCY_CONSUMERS 1

// Defines the emergency inhibit time (x100us)
#define EMCY_INHIBIT_TIME 0

#endif // AUTO_GENERATED_STACK_CONFIG == 1

// [6040,00] Unsigned16
#define P604000_ControlWord 0x00000000
#define PControlWord_604000 P604000_ControlWord
#define P604000 P604000_ControlWord
#define P0x60400x00 P604000_ControlWord
// The uppercase versions are deprecated
#define P604000_CONTROLWORD P604000_ControlWord
#define PCONTROLWORD_604000 P604000_ControlWord
// [6003,00] Unsigned16
#define P600300_pHMillivolts 0x00000004
#define PpHMillivolts_600300 P600300_pHMillivolts
#define P600300 P600300_pHMillivolts
#define P0x60030x00 P600300_pHMillivolts
// The uppercase versions are deprecated
#define P600300_PHMILLIVOLTS P600300_pHMillivolts
#define PPHMILLIVOLTS_600300 P600300_pHMillivolts
// [6010,00] Integer16
#define P601000_Temperature 0x00000006
#define PTemperature_601000 P601000_Temperature
#define P601000 P601000_Temperature
#define P0x60100x00 P601000_Temperature
// The uppercase versions are deprecated
#define P601000_TEMPERATURE P601000_Temperature
#define PTEMPERATURE_601000 P601000_Temperature
// [2300,00] Unsigned8
#define P230000_SensorStatus 0x00000008
#define PSensorStatus_230000 P230000_SensorStatus
#define P230000 P230000_SensorStatus
#define P0x23000x00 P230000_SensorStatus
// The uppercase versions are deprecated
#define P230000_SENSORSTATUS P230000_SensorStatus
#define PSENSORSTATUS_230000 P230000_SensorStatus
// [6001,00] Unsigned8
#define P600100_pHSignalQuality 0x00000009
#define PpHSignalQuality_600100 P600100_pHSignalQuality
#define P600100 P600100_pHSignalQuality
#define P0x60010x00 P600100_pHSignalQuality
// The uppercase versions are deprecated
#define P600100_PHSIGNALQUALITY P600100_pHSignalQuality
#define PPHSIGNALQUALITY_600100 P600100_pHSignalQuality
// [6011,00] Unsigned8
#define P601100_TempSignalQuality 0x0000000A
#define PTempSignalQuality_601100 P601100_TempSignalQuality
#define P601100 P601100_TempSignalQuality
#define P0x60110x00 P601100_TempSignalQuality
// The uppercase versions are deprecated
#define P601100_TEMPSIGNALQUALITY P601100_TempSignalQuality
#define PTEMPSIGNALQUALITY_601100 P601100_TempSignalQuality
// [1001,00] Unsigned8
#define P100100_Error_Register 0x0000000B
#define PError_Register_100100 P100100_Error_Register
#define P100100 P100100_Error_Register
#define P0x10010x00 P100100_Error_Register
// The uppercase versions are deprecated
#define P100100_ERROR_REGISTER P100100_Error_Register
#define PERROR_REGISTER_100100 P100100_Error_Register
// [1008,00] VisibleString
#define P100800_Manufacturer_Device_Name 0x0000000C
#define PManufacturer_Device_Name_100800 P100800_Manufacturer_Device_Name
#define P100800 P100800_Manufacturer_Device_Name
#define P0x10080x00 P100800_Manufacturer_Device_Name
// The uppercase versions are deprecated
#define P100800_MANUFACTURER_DEVICE_NAME P100800_Manufacturer_Device_Name
#define PMANUFACTURER_DEVICE_NAME_100800 P100800_Manufacturer_Device_Name
// [1009,00] VisibleString
#define P100900_Manufacturer_Hardware_Version 0x00000025
#define PManufacturer_Hardware_Version_100900 P100900_Manufacturer_Hardware_Version
#define P100900 P100900_Manufacturer_Hardware_Version
#define P0x10090x00 P100900_Manufacturer_Hardware_Version
// The uppercase versions are deprecated
#define P100900_MANUFACTURER_HARDWARE_VERSION P100900_Manufacturer_Hardware_Version
#define PMANUFACTURER_HARDWARE_VERSION_100900 P100900_Manufacturer_Hardware_Version
// [100A,00] VisibleString
#define P100A00_Manufacturer_Software_Version 0x00000028
#define PManufacturer_Software_Version_100A00 P100A00_Manufacturer_Software_Version
#define P100A00 P100A00_Manufacturer_Software_Version
#define P0x100A0x00 P100A00_Manufacturer_Software_Version
// The uppercase versions are deprecated
#define P100A00_MANUFACTURER_SOFTWARE_VERSION P100A00_Manufacturer_Software_Version
#define PMANUFACTURER_SOFTWARE_VERSION_100A00 P100A00_Manufacturer_Software_Version
// [1018,01] Unsigned32
#define P101801_Vendor_ID 0x0000002B
#define PVendor_ID_101801 P101801_Vendor_ID
#define P101801 P101801_Vendor_ID
#define P0x10180x01 P101801_Vendor_ID
// The uppercase versions are deprecated
#define P101801_VENDOR_ID P101801_Vendor_ID
#define PVENDOR_ID_101801 P101801_Vendor_ID
// [1018,02] Unsigned32
#define P101802_Product_Code 0x0000002F
#define PProduct_Code_101802 P101802_Product_Code
#define P101802 P101802_Product_Code
#define P0x10180x02 P101802_Product_Code
// The uppercase versions are deprecated
#define P101802_PRODUCT_CODE P101802_Product_Code
#define PPRODUCT_CODE_101802 P101802_Product_Code
// [1018,03] Unsigned32
#define P101803_Revision_Number 0x00000033
#define PRevision_Number_101803 P101803_Revision_Number
#define P101803 P101803_Revision_Number
#define P0x10180x03 P101803_Revision_Number
// The uppercase versions are deprecated
#define P101803_REVISION_NUMBER P101803_Revision_Number
#define PREVISION_NUMBER_101803 P101803_Revision_Number
// [1018,04] Unsigned32
#define P101804_Serial_Number 0x00000037
#define PSerial_Number_101804 P101804_Serial_Number
#define P101804 P101804_Serial_Number
#define P0x10180x04 P101804_Serial_Number
// The uppercase versions are deprecated
#define P101804_SERIAL_NUMBER P101804_Serial_Number
#define PSERIAL_NUMBER_101804 P101804_Serial_Number
// [1200,01] Unsigned32
#define P120001_COB_ID_Client_to_Server 0x0000003B
#define PCOB_ID_Client_to_Server_120001 P120001_COB_ID_Client_to_Server
#define P120001 P120001_COB_ID_Client_to_Server
#define P0x12000x01 P120001_COB_ID_Client_to_Server
// The uppercase versions are deprecated
#define P120001_COB_ID_CLIENT_TO_SERVER P120001_COB_ID_Client_to_Server
#define PCOB_ID_CLIENT_TO_SERVER_120001 P120001_COB_ID_Client_to_Server
// [1200,02] Unsigned32
#define P120002_COB_ID_Server_to_Client 0x0000003F
#define PCOB_ID_Server_to_Client_120002 P120002_COB_ID_Server_to_Client
#define P120002 P120002_COB_ID_Server_to_Client
#define P0x12000x02 P120002_COB_ID_Server_to_Client
// The uppercase versions are deprecated
#define P120002_COB_ID_SERVER_TO_CLIENT P120002_COB_ID_Server_to_Client
#define PCOB_ID_SERVER_TO_CLIENT_120002 P120002_COB_ID_Server_to_Client
// [2000,00] Unsigned8
#define P200000_LEDControl 0x00000043
#define PLEDControl_200000 P200000_LEDControl
#define P200000 P200000_LEDControl
#define P0x20000x00 P200000_LEDControl
// The uppercase versions are deprecated
#define P200000_LEDCONTROL P200000_LEDControl
#define PLEDCONTROL_200000 P200000_LEDControl
// [6002,00] Unsigned8
#define P600200_pHSensorStatus 0x00000044
#define PpHSensorStatus_600200 P600200_pHSensorStatus
#define P600200 P600200_pHSensorStatus
#define P0x60020x00 P600200_pHSensorStatus
// The uppercase versions are deprecated
#define P600200_PHSENSORSTATUS P600200_pHSensorStatus
#define PPHSENSORSTATUS_600200 P600200_pHSensorStatus
// [6012,00] Unsigned8
#define P601200_TempSensorStatus 0x00000045
#define PTempSensorStatus_601200 P601200_TempSensorStatus
#define P601200 P601200_TempSensorStatus
#define P0x60120x00 P601200_TempSensorStatus
// The uppercase versions are deprecated
#define P601200_TEMPSENSORSTATUS P601200_TempSensorStatus
#define PTEMPSENSORSTATUS_601200 P601200_TempSensorStatus
// [6041,00] Unsigned16
#define P604100_StatusWord 0x00000046
#define PStatusWord_604100 P604100_StatusWord
#define P604100 P604100_StatusWord
#define P0x60410x00 P604100_StatusWord
// The uppercase versions are deprecated
#define P604100_STATUSWORD P604100_StatusWord
#define PSTATUSWORD_604100 P604100_StatusWord

// last byte used in process image
#define PIMGEND 0x00000047

// sizes for entries in the process image in bytes
#define SIZEOF_6040_00_CONTROLWORD 2
#define SIZEOF_6003_00_PHMILLIVOLTS 2
#define SIZEOF_6010_00_TEMPERATURE 2
#define SIZEOF_2300_00_SENSORSTATUS 1
#define SIZEOF_6001_00_PHSIGNALQUALITY 1
#define SIZEOF_6011_00_TEMPSIGNALQUALITY 1
#define SIZEOF_1001_00_ERROR_REGISTER 1
#define SIZEOF_1008_00_MANUFACTURER_DEVICE_NAME 25
#define SIZEOF_1009_00_MANUFACTURER_HARDWARE_VERSION 3
#define SIZEOF_100A_00_MANUFACTURER_SOFTWARE_VERSION 3
#define SIZEOF_1018_01_VENDOR_ID 4
#define SIZEOF_1018_02_PRODUCT_CODE 4
#define SIZEOF_1018_03_REVISION_NUMBER 4
#define SIZEOF_1018_04_SERIAL_NUMBER 4
#define SIZEOF_1200_01_COB_ID_CLIENT_TO_SERVER 4
#define SIZEOF_1200_02_COB_ID_SERVER_TO_CLIENT 4
#define SIZEOF_2000_00_LEDCONTROL 1
#define SIZEOF_6002_00_PHSENSORSTATUS 1
#define SIZEOF_6012_00_TEMPSENSORSTATUS 1
#define SIZEOF_6041_00_STATUSWORD 2

// default values for process image
#define PIMGDEFAULTS { \
/*[6040,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[6003,00]*/        0x00, 0x00, \
/*[6010,00]*/        0xFA, 0x00, \
/*[2300,00]*/        0x00, \
/*[6001,00]*/        0x64, \
/*[6011,00]*/        0x64, \
/*[1001,00]*/        0x00, \
/*[1008,00]*/        0x70, 0x48, 0x20, 0x61, 0x6E, 0x64, 0x20, 0x54, 0x65, 0x6D, \
                     0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x20, 0x4D, \
                     0x6F, 0x64, 0x75, 0x6C, 0x65, \
/*[1009,00]*/        0x31, 0x2E, 0x30, \
/*[100A,00]*/        0x31, 0x2E, 0x30, \
/*[1018,01]*/        0x23, 0x01, 0x00, 0x00, \
/*[1018,02]*/        0x04, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x00, 0x00, 0x02, 0x00, \
/*[1018,04]*/        0x57, 0x34, 0x12, 0x00, \
/*[1200,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[6002,00]*/        0x00, \
/*[6012,00]*/        0x00, \
/*[6041,00]*/        0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGDEFAULTS 

// minimum values for process image
#define PIMGMINS { \
/*[6040,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[6003,00]*/        0x00, 0x00, \
/*[6010,00]*/        0x00, 0x00, \
/*[2300,00]*/        0x00, \
/*[6001,00]*/        0x00, \
/*[6011,00]*/        0x00, \
/*[1001,00]*/        0x00, \
/*[1008,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1009,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[100A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[6002,00]*/        0x00, \
/*[6012,00]*/        0x00, \
/*[6041,00]*/        0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMINS 

// maximum values for process image
#define PIMGMAXS { \
/*[6040,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[6003,00]*/        0x00, 0x00, \
/*[6010,00]*/        0x00, 0x00, \
/*[2300,00]*/        0x00, \
/*[6001,00]*/        0x00, \
/*[6011,00]*/        0x00, \
/*[1001,00]*/        0x00, \
/*[1008,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1009,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[100A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[6002,00]*/        0x00, \
/*[6012,00]*/        0x00, \
/*[6041,00]*/        0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMAXS 

// Example usage: PIMG_OFFSET(0x1000, 0x00)
#define PIMG_OFFSET(index, subindex) P##index##subindex

#endif // _PIMGH_
