// Entries and Replies
// Generated by CANopen Architect Professional 11.62.6737 on 5/30/2026 11:33:10 AM
// Generated from project E:\ursaScience\Modules\Modules-1000kbs.cax
// Generated from EDS 'PumpModule-n02-250kbs' 05-24-2026 11:27AM by Dakota Ward
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _ENTRIESANDREPLIESH_
#define _ENTRIESANDREPLIESH_

// compatibility define for stack versions 7.00 and 8.00
#ifndef COFD
#define COFD 0x00
#endif

// Number of device type values
#define OD_1000H_NUM 1

// Device type values
#define OD_1000H_LIST \
  0x00020192L, /* [0x1000,0x00] Device Type (Unsigned32) */ \

// Define IGNORE_AUTO_SERIAL if the application or stack defines the serial number

#ifndef IGNORE_AUTO_SERIAL
#define SDOREPLYSERIAL(index,sub,len,val) SDOREPLY(index,sub,len,val)
#else
#define SDOREPLYSERIAL(index,sub,len,val)
#endif

// WARNING - below is a best guess as to which entries are really constants
// Comment out entries that are changed by the application/stack

#define SDOREPLY_ENTRIES \
/* [0x1000,0x00] Device Type (Unsigned32) */ \
SDOREPLY(0x1000, 0x00, 4, OD_DEVICE_TYPE), \
/* [0x1005,0x00] SYNC COB-ID (Unsigned32) */ \
SDOREPLY(0x1005, 0x00, 4, 0x00000080L), \
/* [0x1006,0x00] Communication Cycle Period (Unsigned32) */ \
SDOREPLY(0x1006, 0x00, 4, 0x000186A0L), \
/* [0x1014,0x00] Emergency COB-ID (Unsigned32) */ \
SDOREPLY(0x1014, 0x00, 4, DEFAULT_EMCY_COBID), \
/* [0x1015,0x00] Emergency Inhibit Time (Unsigned16) */ \
SDOREPLY(0x1015, 0x00, 2, 0x00000000L), \
/* [0x1016,0x00] Consumer Heartbeat Time - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1016, 0x00, 1, 0x00000004L), \
/* [0x1016,0x01] Consumer Heartbeat Time - Consumer Heartbeat Time 1 (Unsigned32) */ \
SDOREPLY(0x1016, 0x01, 4, 0x00000000L), \
/* [0x1016,0x02] Consumer Heartbeat Time - Consumer Heartbeat Time 2 (Unsigned32) */ \
SDOREPLY(0x1016, 0x02, 4, 0x00000000L), \
/* [0x1016,0x03] Consumer Heartbeat Time - Consumer Heartbeat Time 3 (Unsigned32) */ \
SDOREPLY(0x1016, 0x03, 4, 0x00000000L), \
/* [0x1016,0x04] Consumer Heartbeat Time - Consumer Heartbeat Time 4 (Unsigned32) */ \
SDOREPLY(0x1016, 0x04, 4, 0x00000000L), \
/* [0x1017,0x00] Producer Heartbeat Time (Unsigned16) */ \
SDOREPLY(0x1017, 0x00, 2, 0x000003E8L), \
/* [0x1018,0x00] Identity - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1018, 0x00, 1, 0x00000004L), \
/* [0x1018,0x04] Identity - Serial Number (Unsigned32) */ \
SDOREPLYSERIAL(0x1018, 0x04, 4, OD_SERIAL_NUMBER), \
/* [0x1019,0x00] Synchronous Counter Overflow Value (Unsigned8) */ \
SDOREPLY(0x1019, 0x00, 1, 0x00000000L), \
/* [0x1020,0x00] Verify Configuration - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1020, 0x00, 1, 0x00000002L), \
/* [0x1028,0x00] Emergency Consumer - Number of Consumed Emergency Objects (Unsigned8) */ \
SDOREPLY(0x1028, 0x00, 1, 0x00000004L), \
/* [0x1028,0x01] Emergency Consumer - Emergency Consumer 1 (Unsigned32) */ \
SDOREPLY(0x1028, 0x01, 4, 0x00000000L), \
/* [0x1028,0x02] Emergency Consumer - Emergency Consumer 2 (Unsigned32) */ \
SDOREPLY(0x1028, 0x02, 4, 0x00000000L), \
/* [0x1028,0x03] Emergency Consumer - Emergency Consumer 3 (Unsigned32) */ \
SDOREPLY(0x1028, 0x03, 4, 0x00000000L), \
/* [0x1028,0x04] Emergency Consumer - Emergency Consumer 4 (Unsigned32) */ \
SDOREPLY(0x1028, 0x04, 4, 0x00000000L), \
/* [0x1200,0x00] SDO Server Parameter - Number of entries (Unsigned8) */ \
SDOREPLY(0x1200, 0x00, 1, 0x00000002L), \
/* [0x1200,0x01] SDO Server Parameter - COB-ID Client to Server (Unsigned32) */ \
SDOREPLY(0x1200, 0x01, 4, 0x00000000L), \
/* [0x1200,0x02] SDO Server Parameter - COB-ID Server to Client (Unsigned32) */ \
SDOREPLY(0x1200, 0x02, 4, 0x00000000L), \
\
/* PDO parameters are in Object Dictionary */ \
\
/* RPDO communication parameters */ \
/* [0x1400,0x00] Receive PDO 1 Communication - Highest Subindex Supported (Unsigned8) */ \
SDOREPLY(0x1400, 0x00, 1, 0x00000005L), \
/* [0x1400,0x01] Receive PDO 1 Communication - COB ID used by PDO (Unsigned32) */ \
SDOREPLY(0x1400, 0x01, 4, 0x00000000L), \
/* [0x1400,0x02] Receive PDO 1 Communication - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1400, 0x02, 1, 0x00000001L), \
/* [0x1400,0x03] Receive PDO 1 Communication - Inhibit Time (Unsigned16) */ \
SDOREPLY(0x1400, 0x03, 2, 0x00000000L), \
/* [0x1400,0x05] Receive PDO 1 Communication - Event Timer (Unsigned16) */ \
SDOREPLY(0x1400, 0x05, 2, 0x00000000L), \
\
/* RPDO mapping parameters */ \
/* [0x1600,0x00] Receive PDO 1 Mapping - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1600, 0x00, 1, 0x00000002L), \
/* [0x1600,0x01] Receive PDO 1 Mapping - ControlWord (Unsigned32) */ \
SDOREPLY(0x1600, 0x01, 4, 0x60400010L), \
/* [0x1600,0x02] Receive PDO 1 Mapping - TargetFlowRate (Unsigned32) */ \
SDOREPLY(0x1600, 0x02, 4, 0x60420010L), \
\
/* TPDO communication parameters */ \
/* [0x1800,0x00] Transmit PDO 1 Communication - Highest Subindex Supported (Unsigned8) */ \
SDOREPLY(0x1800, 0x00, 1, 0x00000006L), \
/* [0x1800,0x01] Transmit PDO 1 Communication - COB ID used by PDO (Unsigned32) */ \
SDOREPLY(0x1800, 0x01, 4, 0x00000000L), \
/* [0x1800,0x02] Transmit PDO 1 Communication - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1800, 0x02, 1, 0x00000001L), \
/* [0x1800,0x03] Transmit PDO 1 Communication - Inhibit Time (Unsigned16) */ \
SDOREPLY(0x1800, 0x03, 2, 0x00000000L), \
/* [0x1800,0x05] Transmit PDO 1 Communication - Event Timer (Unsigned16) */ \
SDOREPLY(0x1800, 0x05, 2, 0x00000000L), \
/* [0x1800,0x06] Transmit PDO 1 Communication - Sync Start Value (Unsigned8) */ \
SDOREPLY(0x1800, 0x06, 1, 0x00000000L), \
/* [0x1801,0x00] Transmit PDO 2 Communication - Highest Subindex Supported (Unsigned8) */ \
SDOREPLY(0x1801, 0x00, 1, 0x00000006L), \
/* [0x1801,0x01] Transmit PDO 2 Communication - COB ID used by PDO (Unsigned32) */ \
SDOREPLY(0x1801, 0x01, 4, 0x00000000L), \
/* [0x1801,0x02] Transmit PDO 2 Communication - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1801, 0x02, 1, 0x00000001L), \
/* [0x1801,0x03] Transmit PDO 2 Communication - Inhibit Time (Unsigned16) */ \
SDOREPLY(0x1801, 0x03, 2, 0x00000000L), \
/* [0x1801,0x05] Transmit PDO 2 Communication - Event Timer (Unsigned16) */ \
SDOREPLY(0x1801, 0x05, 2, 0x00000000L), \
/* [0x1801,0x06] Transmit PDO 2 Communication - Sync Start Value (Unsigned8) */ \
SDOREPLY(0x1801, 0x06, 1, 0x00000000L), \
\
/* TPDO mapping parameters */ \
/* [0x1A00,0x00] Transmit PDO 1 Mapping - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1A00, 0x00, 1, 0x00000002L), \
/* [0x1A00,0x01] Transmit PDO 1 Mapping - Status Word (Unsigned32) */ \
SDOREPLY(0x1A00, 0x01, 4, 0x60410010L), \
/* [0x1A00,0x02] Transmit PDO 1 Mapping - ActualFlowRate (Unsigned32) */ \
SDOREPLY(0x1A00, 0x02, 4, 0x60430010L), \
/* [0x1A01,0x00] Transmit PDO 2 Mapping - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1A01, 0x00, 1, 0x00000003L), \
/* [0x1A01,0x01] Transmit PDO 2 Mapping - Pump State (Unsigned32) */ \
SDOREPLY(0x1A01, 0x01, 4, 0x24000008L), \
/* [0x1A01,0x02] Transmit PDO 2 Mapping - ErrorRegister (Unsigned32) */ \
SDOREPLY(0x1A01, 0x02, 4, 0x10010008L), \
/* [0x1A01,0x03] Transmit PDO 2 Mapping - DoseDelivered (Unsigned32) */ \
SDOREPLY(0x1A01, 0x03, 4, 0x23040020L), \
\
/* [0x1F80,0x00] NMT Startup (Unsigned32) */ \
SDOREPLY(0x1F80, 0x00, 4, 0x00000004L), \

// 1 MACROS WERE GENERATED TO HOLD THE SDO REPLIES
// USE THE FOLLOWING INITIALIZER:
// SDOREPLY_ENTRIES 


#define ODGENTRY_CONSTINITS \


#define ODGENTRY_ENTRIES \
ODGENTRYP(0x1008, 0x00, ODRD, 11, P100800_Manufacturer_Device_Name), \

// 1 MACROS WERE GENERATED TO HOLD THE OD REPLIES
// USE THE FOLLOWING INITIALIZER:
// ODGENTRY_ENTRIES 

#define ODENTRY_ENTRIES \
ODENTRY(0x1002, 0x00, 4+ODRD+RMAP, P100200_Manufacturer_Status_Register), \
ODENTRY(0x1007, 0x00, 4+ODRD+ODWR, P100700_Synchronous_Window_Length), \
ODENTRY(0x1009, 0x00, 3+ODRD, P100900_Manufacturer_Hardware_Version), \
ODENTRY(0x100A, 0x00, 3+ODRD, P100A00_Manufacturer_Software_Version), \
ODENTRY(0x1012, 0x00, 4+ODRD+ODWR, P101200_Time_Stamp_COB_ID), \
ODENTRY(0x1013, 0x00, 4+ODRD+RMAP, P101300_High_Resolution_Time_Stamp), \
ODENTRY(0x1018, 0x01, 4+ODRD, P101801_Vendor_ID), \
ODENTRY(0x1018, 0x02, 4+ODRD, P101802_Product_Code), \
ODENTRY(0x1018, 0x03, 4+ODRD, P101803_Revision_Number), \
ODENTRY(0x1020, 0x01, 4+ODRD+ODWR, P102001_Configuration_Date), \
ODENTRY(0x1020, 0x02, 4+ODRD+ODWR, P102002_Configuration_Time), \
ODENTRY(0x2000, 0x00, 1+ODRD+ODWR, P200000_LEDControl), \
ODENTRY(0x2100, 0x00, 2+ODRD+ODWR, P210000_MaxFlowRate), \
ODENTRY(0x2102, 0x00, 1+ODRD, P210200_EmergencyStopState), \
ODENTRY(0x2200, 0x00, 4+ODRD+ODWR, P220000_FlowCorrectionFactor), \
ODENTRY(0x2300, 0x00, 4+ODRD+ODWR, P230000_DoseVolume), \
ODENTRY(0x2301, 0x00, 2+ODRD+ODWR, P230100_DoseFlowRate), \
ODENTRY(0x2302, 0x00, 1+ODWR, P230200_DoseCommand), \
ODENTRY(0x2303, 0x00, 1+ODRD, P230300_DoseStatus), \
ODENTRY(0x2304, 0x00, 4+ODRD+RMAP, P230400_DoseDelivered), \
ODENTRY(0x2305, 0x00, 2+ODRD+ODWR, P230500_DoseTimeout), \
ODENTRY(0x2400, 0x00, 1+ODRD+RMAP, P240000_PumpState), \
ODENTRY(0x6040, 0x00, 2+ODRD+ODWR+WMAP, P604000_ControlWord), \
ODENTRY(0x6041, 0x00, 2+ODRD+RMAP, P604100_StatusWord), \
ODENTRY(0x6042, 0x00, 2+ODRD+ODWR+WMAP, P604200_TargetFlowRate), \
ODENTRY(0x6043, 0x00, 2+ODRD+RMAP, P604300_ActualFlowRate), \

// 1 MACROS WERE GENERATED TO HOLD THE OD REPLIES
// USE THE FOLLOWING INITIALIZER:
// ODENTRY_ENTRIES 

// all entries in the object dictionary
#define OD_ID_LIST \
  0x100000, /* [0x1000,0x00] Device Type (Unsigned32) */ \
  0x100100, /* [0x1001,0x00] Error Register (Unsigned8) */ \
  0x100200, /* [0x1002,0x00] Manufacturer Status Register (Unsigned32) */ \
  0x100300, /* [0x1003,0x00] Pre-defined Error Field - Number of Errors (Unsigned8) */ \
  0x100301, /* [0x1003,0x01] Pre-defined Error Field - Standard Error Field 1 (Unsigned32) */ \
  0x100302, /* [0x1003,0x02] Pre-defined Error Field - Standard Error Field 2 (Unsigned32) */ \
  0x100303, /* [0x1003,0x03] Pre-defined Error Field - Standard Error Field 3 (Unsigned32) */ \
  0x100304, /* [0x1003,0x04] Pre-defined Error Field - Standard Error Field 4 (Unsigned32) */ \
  0x100500, /* [0x1005,0x00] SYNC COB-ID (Unsigned32) */ \
  0x100600, /* [0x1006,0x00] Communication Cycle Period (Unsigned32) */ \
  0x100700, /* [0x1007,0x00] Synchronous Window Length (Unsigned32) */ \
  0x100800, /* [0x1008,0x00] Manufacturer Device Name (VisibleString) */ \
  0x100900, /* [0x1009,0x00] Manufacturer Hardware Version (VisibleString) */ \
  0x100A00, /* [0x100A,0x00] Manufacturer Software Version (VisibleString) */ \
  0x101000, /* [0x1010,0x00] Store Parameters - Number of Entries (Unsigned8) */ \
  0x101001, /* [0x1010,0x01] Store Parameters - Save All Parameters (Unsigned32) */ \
  0x101002, /* [0x1010,0x02] Store Parameters - Save Communication Parameters (Unsigned32) */ \
  0x101003, /* [0x1010,0x03] Store Parameters - Save Application Parameters (Unsigned32) */ \
  0x101004, /* [0x1010,0x04] Store Parameters - Save Manufacturer Defined Parameters 1 (Unsigned32) */ \
  0x101100, /* [0x1011,0x00] Restore Default Parameters - Number of Entries (Unsigned8) */ \
  0x101101, /* [0x1011,0x01] Restore Default Parameters - Restore All Parameters (Unsigned32) */ \
  0x101102, /* [0x1011,0x02] Restore Default Parameters - Restore Communication Parameters (Unsigned32) */ \
  0x101103, /* [0x1011,0x03] Restore Default Parameters - Restore Application Parameters (Unsigned32) */ \
  0x101104, /* [0x1011,0x04] Restore Default Parameters - Restore Manufacturer Defined Parameters 1 (Unsigned32) */ \
  0x101200, /* [0x1012,0x00] Time Stamp COB-ID (Unsigned32) */ \
  0x101300, /* [0x1013,0x00] High Resolution Time Stamp (Unsigned32) */ \
  0x101400, /* [0x1014,0x00] Emergency COB-ID (Unsigned32) */ \
  0x101500, /* [0x1015,0x00] Emergency Inhibit Time (Unsigned16) */ \
  0x101600, /* [0x1016,0x00] Consumer Heartbeat Time - Number of Entries (Unsigned8) */ \
  0x101601, /* [0x1016,0x01] Consumer Heartbeat Time - Consumer Heartbeat Time 1 (Unsigned32) */ \
  0x101602, /* [0x1016,0x02] Consumer Heartbeat Time - Consumer Heartbeat Time 2 (Unsigned32) */ \
  0x101603, /* [0x1016,0x03] Consumer Heartbeat Time - Consumer Heartbeat Time 3 (Unsigned32) */ \
  0x101604, /* [0x1016,0x04] Consumer Heartbeat Time - Consumer Heartbeat Time 4 (Unsigned32) */ \
  0x101700, /* [0x1017,0x00] Producer Heartbeat Time (Unsigned16) */ \
  0x101800, /* [0x1018,0x00] Identity - Number of Entries (Unsigned8) */ \
  0x101801, /* [0x1018,0x01] Identity - Vendor ID (Unsigned32) */ \
  0x101802, /* [0x1018,0x02] Identity - Product Code (Unsigned32) */ \
  0x101803, /* [0x1018,0x03] Identity - Revision Number (Unsigned32) */ \
  0x101804, /* [0x1018,0x04] Identity - Serial Number (Unsigned32) */ \
  0x101900, /* [0x1019,0x00] Synchronous Counter Overflow Value (Unsigned8) */ \
  0x102000, /* [0x1020,0x00] Verify Configuration - Number of Entries (Unsigned8) */ \
  0x102001, /* [0x1020,0x01] Verify Configuration - Configuration Date (Unsigned32) */ \
  0x102002, /* [0x1020,0x02] Verify Configuration - Configuration Time (Unsigned32) */ \
  0x102800, /* [0x1028,0x00] Emergency Consumer - Number of Consumed Emergency Objects (Unsigned8) */ \
  0x102801, /* [0x1028,0x01] Emergency Consumer - Emergency Consumer 1 (Unsigned32) */ \
  0x102802, /* [0x1028,0x02] Emergency Consumer - Emergency Consumer 2 (Unsigned32) */ \
  0x102803, /* [0x1028,0x03] Emergency Consumer - Emergency Consumer 3 (Unsigned32) */ \
  0x102804, /* [0x1028,0x04] Emergency Consumer - Emergency Consumer 4 (Unsigned32) */ \
  0x120000, /* [0x1200,0x00] SDO Server Parameter - Number of entries (Unsigned8) */ \
  0x120001, /* [0x1200,0x01] SDO Server Parameter - COB-ID Client to Server (Unsigned32) */ \
  0x120002, /* [0x1200,0x02] SDO Server Parameter - COB-ID Server to Client (Unsigned32) */ \
  0x140000, /* [0x1400,0x00] Receive PDO 1 Communication - Highest Subindex Supported (Unsigned8) */ \
  0x140001, /* [0x1400,0x01] Receive PDO 1 Communication - COB ID used by PDO (Unsigned32) */ \
  0x140002, /* [0x1400,0x02] Receive PDO 1 Communication - Transmission Type (Unsigned8) */ \
  0x140003, /* [0x1400,0x03] Receive PDO 1 Communication - Inhibit Time (Unsigned16) */ \
  0x140005, /* [0x1400,0x05] Receive PDO 1 Communication - Event Timer (Unsigned16) */ \
  0x160000, /* [0x1600,0x00] Receive PDO 1 Mapping - Number of Entries (Unsigned8) */ \
  0x160001, /* [0x1600,0x01] Receive PDO 1 Mapping - ControlWord (Unsigned32) */ \
  0x160002, /* [0x1600,0x02] Receive PDO 1 Mapping - TargetFlowRate (Unsigned32) */ \
  0x180000, /* [0x1800,0x00] Transmit PDO 1 Communication - Highest Subindex Supported (Unsigned8) */ \
  0x180001, /* [0x1800,0x01] Transmit PDO 1 Communication - COB ID used by PDO (Unsigned32) */ \
  0x180002, /* [0x1800,0x02] Transmit PDO 1 Communication - Transmission Type (Unsigned8) */ \
  0x180003, /* [0x1800,0x03] Transmit PDO 1 Communication - Inhibit Time (Unsigned16) */ \
  0x180005, /* [0x1800,0x05] Transmit PDO 1 Communication - Event Timer (Unsigned16) */ \
  0x180006, /* [0x1800,0x06] Transmit PDO 1 Communication - Sync Start Value (Unsigned8) */ \
  0x180100, /* [0x1801,0x00] Transmit PDO 2 Communication - Highest Subindex Supported (Unsigned8) */ \
  0x180101, /* [0x1801,0x01] Transmit PDO 2 Communication - COB ID used by PDO (Unsigned32) */ \
  0x180102, /* [0x1801,0x02] Transmit PDO 2 Communication - Transmission Type (Unsigned8) */ \
  0x180103, /* [0x1801,0x03] Transmit PDO 2 Communication - Inhibit Time (Unsigned16) */ \
  0x180105, /* [0x1801,0x05] Transmit PDO 2 Communication - Event Timer (Unsigned16) */ \
  0x180106, /* [0x1801,0x06] Transmit PDO 2 Communication - Sync Start Value (Unsigned8) */ \
  0x1A0000, /* [0x1A00,0x00] Transmit PDO 1 Mapping - Number of Entries (Unsigned8) */ \
  0x1A0001, /* [0x1A00,0x01] Transmit PDO 1 Mapping - Status Word (Unsigned32) */ \
  0x1A0002, /* [0x1A00,0x02] Transmit PDO 1 Mapping - ActualFlowRate (Unsigned32) */ \
  0x1A0100, /* [0x1A01,0x00] Transmit PDO 2 Mapping - Number of Entries (Unsigned8) */ \
  0x1A0101, /* [0x1A01,0x01] Transmit PDO 2 Mapping - Pump State (Unsigned32) */ \
  0x1A0102, /* [0x1A01,0x02] Transmit PDO 2 Mapping - ErrorRegister (Unsigned32) */ \
  0x1A0103, /* [0x1A01,0x03] Transmit PDO 2 Mapping - DoseDelivered (Unsigned32) */ \
  0x1F8000, /* [0x1F80,0x00] NMT Startup (Unsigned32) */ \
  0x200000, /* [0x2000,0x00] LEDControl (Unsigned8) */ \
  0x210000, /* [0x2100,0x00] MaxFlowRate (Unsigned16) */ \
  0x210200, /* [0x2102,0x00] EmergencyStopState (Boolean) */ \
  0x220000, /* [0x2200,0x00] FlowCorrectionFactor (Real32) */ \
  0x230000, /* [0x2300,0x00] DoseVolume (Unsigned32) */ \
  0x230100, /* [0x2301,0x00] DoseFlowRate (Integer16) */ \
  0x230200, /* [0x2302,0x00] DoseCommand (Unsigned8) */ \
  0x230300, /* [0x2303,0x00] DoseStatus (Unsigned8) */ \
  0x230400, /* [0x2304,0x00] DoseDelivered (Unsigned32) */ \
  0x230500, /* [0x2305,0x00] DoseTimeout (Unsigned16) */ \
  0x240000, /* [0x2400,0x00] PumpState (Unsigned8) */ \
  0x604000, /* [0x6040,0x00] ControlWord (Unsigned16) */ \
  0x604100, /* [0x6041,0x00] StatusWord (Unsigned16) */ \
  0x604200, /* [0x6042,0x00] TargetFlowRate (Integer16) */ \
  0x604300, /* [0x6043,0x00] ActualFlowRate (Integer16) */ \

// 1 MACROS WERE GENERATED TO HOLD THE LIST OF OD ENTRIES
// USE THE FOLLOWING INITIALIZER:
// OD_ID_LIST 

#if defined(USE_CANOPEN_FD) && (USE_CANOPEN_FD == 1)

// types of all entries in the object dictionary
#define OD_ID_TYPE \
  TYPE_UNSIGNED32     , /* [0x1000,0x00] Device Type (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x1001,0x00] Error Register (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1002,0x00] Manufacturer Status Register (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x1003,0x00] Pre-defined Error Field - Number of Errors (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1003,0x01] Pre-defined Error Field - Standard Error Field 1 (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1003,0x02] Pre-defined Error Field - Standard Error Field 2 (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1003,0x03] Pre-defined Error Field - Standard Error Field 3 (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1003,0x04] Pre-defined Error Field - Standard Error Field 4 (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1005,0x00] SYNC COB-ID (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1006,0x00] Communication Cycle Period (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1007,0x00] Synchronous Window Length (Unsigned32) */ \
  TYPE_VISIBLE_STRING , /* [0x1008,0x00] Manufacturer Device Name (VisibleString) */ \
  TYPE_VISIBLE_STRING , /* [0x1009,0x00] Manufacturer Hardware Version (VisibleString) */ \
  TYPE_VISIBLE_STRING , /* [0x100A,0x00] Manufacturer Software Version (VisibleString) */ \
  TYPE_UNSIGNED8      , /* [0x1010,0x00] Store Parameters - Number of Entries (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1010,0x01] Store Parameters - Save All Parameters (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1010,0x02] Store Parameters - Save Communication Parameters (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1010,0x03] Store Parameters - Save Application Parameters (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1010,0x04] Store Parameters - Save Manufacturer Defined Parameters 1 (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x1011,0x00] Restore Default Parameters - Number of Entries (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1011,0x01] Restore Default Parameters - Restore All Parameters (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1011,0x02] Restore Default Parameters - Restore Communication Parameters (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1011,0x03] Restore Default Parameters - Restore Application Parameters (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1011,0x04] Restore Default Parameters - Restore Manufacturer Defined Parameters 1 (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1012,0x00] Time Stamp COB-ID (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1013,0x00] High Resolution Time Stamp (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1014,0x00] Emergency COB-ID (Unsigned32) */ \
  TYPE_UNSIGNED16     , /* [0x1015,0x00] Emergency Inhibit Time (Unsigned16) */ \
  TYPE_UNSIGNED8      , /* [0x1016,0x00] Consumer Heartbeat Time - Number of Entries (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1016,0x01] Consumer Heartbeat Time - Consumer Heartbeat Time 1 (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1016,0x02] Consumer Heartbeat Time - Consumer Heartbeat Time 2 (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1016,0x03] Consumer Heartbeat Time - Consumer Heartbeat Time 3 (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1016,0x04] Consumer Heartbeat Time - Consumer Heartbeat Time 4 (Unsigned32) */ \
  TYPE_UNSIGNED16     , /* [0x1017,0x00] Producer Heartbeat Time (Unsigned16) */ \
  TYPE_UNSIGNED8      , /* [0x1018,0x00] Identity - Number of Entries (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1018,0x01] Identity - Vendor ID (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1018,0x02] Identity - Product Code (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1018,0x03] Identity - Revision Number (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1018,0x04] Identity - Serial Number (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x1019,0x00] Synchronous Counter Overflow Value (Unsigned8) */ \
  TYPE_UNSIGNED8      , /* [0x1020,0x00] Verify Configuration - Number of Entries (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1020,0x01] Verify Configuration - Configuration Date (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1020,0x02] Verify Configuration - Configuration Time (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x1028,0x00] Emergency Consumer - Number of Consumed Emergency Objects (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1028,0x01] Emergency Consumer - Emergency Consumer 1 (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1028,0x02] Emergency Consumer - Emergency Consumer 2 (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1028,0x03] Emergency Consumer - Emergency Consumer 3 (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1028,0x04] Emergency Consumer - Emergency Consumer 4 (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x1200,0x00] SDO Server Parameter - Number of entries (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1200,0x01] SDO Server Parameter - COB-ID Client to Server (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1200,0x02] SDO Server Parameter - COB-ID Server to Client (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x1400,0x00] Receive PDO 1 Communication - Highest Subindex Supported (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1400,0x01] Receive PDO 1 Communication - COB ID used by PDO (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x1400,0x02] Receive PDO 1 Communication - Transmission Type (Unsigned8) */ \
  TYPE_UNSIGNED16     , /* [0x1400,0x03] Receive PDO 1 Communication - Inhibit Time (Unsigned16) */ \
  TYPE_UNSIGNED16     , /* [0x1400,0x05] Receive PDO 1 Communication - Event Timer (Unsigned16) */ \
  TYPE_UNSIGNED8      , /* [0x1600,0x00] Receive PDO 1 Mapping - Number of Entries (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1600,0x01] Receive PDO 1 Mapping - ControlWord (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1600,0x02] Receive PDO 1 Mapping - TargetFlowRate (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x1800,0x00] Transmit PDO 1 Communication - Highest Subindex Supported (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1800,0x01] Transmit PDO 1 Communication - COB ID used by PDO (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x1800,0x02] Transmit PDO 1 Communication - Transmission Type (Unsigned8) */ \
  TYPE_UNSIGNED16     , /* [0x1800,0x03] Transmit PDO 1 Communication - Inhibit Time (Unsigned16) */ \
  TYPE_UNSIGNED16     , /* [0x1800,0x05] Transmit PDO 1 Communication - Event Timer (Unsigned16) */ \
  TYPE_UNSIGNED8      , /* [0x1800,0x06] Transmit PDO 1 Communication - Sync Start Value (Unsigned8) */ \
  TYPE_UNSIGNED8      , /* [0x1801,0x00] Transmit PDO 2 Communication - Highest Subindex Supported (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1801,0x01] Transmit PDO 2 Communication - COB ID used by PDO (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x1801,0x02] Transmit PDO 2 Communication - Transmission Type (Unsigned8) */ \
  TYPE_UNSIGNED16     , /* [0x1801,0x03] Transmit PDO 2 Communication - Inhibit Time (Unsigned16) */ \
  TYPE_UNSIGNED16     , /* [0x1801,0x05] Transmit PDO 2 Communication - Event Timer (Unsigned16) */ \
  TYPE_UNSIGNED8      , /* [0x1801,0x06] Transmit PDO 2 Communication - Sync Start Value (Unsigned8) */ \
  TYPE_UNSIGNED8      , /* [0x1A00,0x00] Transmit PDO 1 Mapping - Number of Entries (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1A00,0x01] Transmit PDO 1 Mapping - Status Word (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1A00,0x02] Transmit PDO 1 Mapping - ActualFlowRate (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x1A01,0x00] Transmit PDO 2 Mapping - Number of Entries (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x1A01,0x01] Transmit PDO 2 Mapping - Pump State (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1A01,0x02] Transmit PDO 2 Mapping - ErrorRegister (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1A01,0x03] Transmit PDO 2 Mapping - DoseDelivered (Unsigned32) */ \
  TYPE_UNSIGNED32     , /* [0x1F80,0x00] NMT Startup (Unsigned32) */ \
  TYPE_UNSIGNED8      , /* [0x2000,0x00] LEDControl (Unsigned8) */ \
  TYPE_UNSIGNED16     , /* [0x2100,0x00] MaxFlowRate (Unsigned16) */ \
  TYPE_BOOLEAN        , /* [0x2102,0x00] EmergencyStopState (Boolean) */ \
  TYPE_REAL32         , /* [0x2200,0x00] FlowCorrectionFactor (Real32) */ \
  TYPE_UNSIGNED32     , /* [0x2300,0x00] DoseVolume (Unsigned32) */ \
  TYPE_INTEGER16      , /* [0x2301,0x00] DoseFlowRate (Integer16) */ \
  TYPE_UNSIGNED8      , /* [0x2302,0x00] DoseCommand (Unsigned8) */ \
  TYPE_UNSIGNED8      , /* [0x2303,0x00] DoseStatus (Unsigned8) */ \
  TYPE_UNSIGNED32     , /* [0x2304,0x00] DoseDelivered (Unsigned32) */ \
  TYPE_UNSIGNED16     , /* [0x2305,0x00] DoseTimeout (Unsigned16) */ \
  TYPE_UNSIGNED8      , /* [0x2400,0x00] PumpState (Unsigned8) */ \
  TYPE_UNSIGNED16     , /* [0x6040,0x00] ControlWord (Unsigned16) */ \
  TYPE_UNSIGNED16     , /* [0x6041,0x00] StatusWord (Unsigned16) */ \
  TYPE_INTEGER16      , /* [0x6042,0x00] TargetFlowRate (Integer16) */ \
  TYPE_INTEGER16      , /* [0x6043,0x00] ActualFlowRate (Integer16) */ \

// 1 MACROS WERE GENERATED TO HOLD THE LIST OF OD ENTRY TYPES
// USE THE FOLLOWING INITIALIZER:
// OD_ID_TYPE 

// table location of all entries in the object dictionary
#define OD_ID_TABLELOCATION \
  ODLOC_SDOREPLY, /* [0x1000,0x00] Device Type (Unsigned32) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1001,0x00] Error Register (Unsigned8) */ \
  ODLOC_ODENTRY , /* [0x1002,0x00] Manufacturer Status Register (Unsigned32) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1003,0x00] Pre-defined Error Field - Number of Errors (Unsigned8) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1003,0x01] Pre-defined Error Field - Standard Error Field 1 (Unsigned32) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1003,0x02] Pre-defined Error Field - Standard Error Field 2 (Unsigned32) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1003,0x03] Pre-defined Error Field - Standard Error Field 3 (Unsigned32) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1003,0x04] Pre-defined Error Field - Standard Error Field 4 (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1005,0x00] SYNC COB-ID (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1006,0x00] Communication Cycle Period (Unsigned32) */ \
  ODLOC_ODENTRY , /* [0x1007,0x00] Synchronous Window Length (Unsigned32) */ \
  ODLOC_ODGENTRY, /* [0x1008,0x00] Manufacturer Device Name (VisibleString) */ \
  ODLOC_ODENTRY , /* [0x1009,0x00] Manufacturer Hardware Version (VisibleString) */ \
  ODLOC_ODENTRY , /* [0x100A,0x00] Manufacturer Software Version (VisibleString) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1010,0x00] Store Parameters - Number of Entries (Unsigned8) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1010,0x01] Store Parameters - Save All Parameters (Unsigned32) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1010,0x02] Store Parameters - Save Communication Parameters (Unsigned32) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1010,0x03] Store Parameters - Save Application Parameters (Unsigned32) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1010,0x04] Store Parameters - Save Manufacturer Defined Parameters 1 (Unsigned32) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1011,0x00] Restore Default Parameters - Number of Entries (Unsigned8) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1011,0x01] Restore Default Parameters - Restore All Parameters (Unsigned32) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1011,0x02] Restore Default Parameters - Restore Communication Parameters (Unsigned32) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1011,0x03] Restore Default Parameters - Restore Application Parameters (Unsigned32) */ \
/* WARNING - TABLE OF ENTRY IS UNKNOWN */ \
  ODLOC_UNKNOWN , /* [0x1011,0x04] Restore Default Parameters - Restore Manufacturer Defined Parameters 1 (Unsigned32) */ \
  ODLOC_ODENTRY , /* [0x1012,0x00] Time Stamp COB-ID (Unsigned32) */ \
  ODLOC_ODENTRY , /* [0x1013,0x00] High Resolution Time Stamp (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1014,0x00] Emergency COB-ID (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1015,0x00] Emergency Inhibit Time (Unsigned16) */ \
  ODLOC_SDOREPLY, /* [0x1016,0x00] Consumer Heartbeat Time - Number of Entries (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1016,0x01] Consumer Heartbeat Time - Consumer Heartbeat Time 1 (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1016,0x02] Consumer Heartbeat Time - Consumer Heartbeat Time 2 (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1016,0x03] Consumer Heartbeat Time - Consumer Heartbeat Time 3 (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1016,0x04] Consumer Heartbeat Time - Consumer Heartbeat Time 4 (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1017,0x00] Producer Heartbeat Time (Unsigned16) */ \
  ODLOC_SDOREPLY, /* [0x1018,0x00] Identity - Number of Entries (Unsigned8) */ \
  ODLOC_ODENTRY , /* [0x1018,0x01] Identity - Vendor ID (Unsigned32) */ \
  ODLOC_ODENTRY , /* [0x1018,0x02] Identity - Product Code (Unsigned32) */ \
  ODLOC_ODENTRY , /* [0x1018,0x03] Identity - Revision Number (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1018,0x04] Identity - Serial Number (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1019,0x00] Synchronous Counter Overflow Value (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1020,0x00] Verify Configuration - Number of Entries (Unsigned8) */ \
  ODLOC_ODENTRY , /* [0x1020,0x01] Verify Configuration - Configuration Date (Unsigned32) */ \
  ODLOC_ODENTRY , /* [0x1020,0x02] Verify Configuration - Configuration Time (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1028,0x00] Emergency Consumer - Number of Consumed Emergency Objects (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1028,0x01] Emergency Consumer - Emergency Consumer 1 (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1028,0x02] Emergency Consumer - Emergency Consumer 2 (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1028,0x03] Emergency Consumer - Emergency Consumer 3 (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1028,0x04] Emergency Consumer - Emergency Consumer 4 (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1200,0x00] SDO Server Parameter - Number of entries (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1200,0x01] SDO Server Parameter - COB-ID Client to Server (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1200,0x02] SDO Server Parameter - COB-ID Server to Client (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1400,0x00] Receive PDO 1 Communication - Highest Subindex Supported (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1400,0x01] Receive PDO 1 Communication - COB ID used by PDO (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1400,0x02] Receive PDO 1 Communication - Transmission Type (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1400,0x03] Receive PDO 1 Communication - Inhibit Time (Unsigned16) */ \
  ODLOC_SDOREPLY, /* [0x1400,0x05] Receive PDO 1 Communication - Event Timer (Unsigned16) */ \
  ODLOC_SDOREPLY, /* [0x1600,0x00] Receive PDO 1 Mapping - Number of Entries (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1600,0x01] Receive PDO 1 Mapping - ControlWord (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1600,0x02] Receive PDO 1 Mapping - TargetFlowRate (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1800,0x00] Transmit PDO 1 Communication - Highest Subindex Supported (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1800,0x01] Transmit PDO 1 Communication - COB ID used by PDO (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1800,0x02] Transmit PDO 1 Communication - Transmission Type (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1800,0x03] Transmit PDO 1 Communication - Inhibit Time (Unsigned16) */ \
  ODLOC_SDOREPLY, /* [0x1800,0x05] Transmit PDO 1 Communication - Event Timer (Unsigned16) */ \
  ODLOC_SDOREPLY, /* [0x1800,0x06] Transmit PDO 1 Communication - Sync Start Value (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1801,0x00] Transmit PDO 2 Communication - Highest Subindex Supported (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1801,0x01] Transmit PDO 2 Communication - COB ID used by PDO (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1801,0x02] Transmit PDO 2 Communication - Transmission Type (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1801,0x03] Transmit PDO 2 Communication - Inhibit Time (Unsigned16) */ \
  ODLOC_SDOREPLY, /* [0x1801,0x05] Transmit PDO 2 Communication - Event Timer (Unsigned16) */ \
  ODLOC_SDOREPLY, /* [0x1801,0x06] Transmit PDO 2 Communication - Sync Start Value (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1A00,0x00] Transmit PDO 1 Mapping - Number of Entries (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1A00,0x01] Transmit PDO 1 Mapping - Status Word (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1A00,0x02] Transmit PDO 1 Mapping - ActualFlowRate (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1A01,0x00] Transmit PDO 2 Mapping - Number of Entries (Unsigned8) */ \
  ODLOC_SDOREPLY, /* [0x1A01,0x01] Transmit PDO 2 Mapping - Pump State (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1A01,0x02] Transmit PDO 2 Mapping - ErrorRegister (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1A01,0x03] Transmit PDO 2 Mapping - DoseDelivered (Unsigned32) */ \
  ODLOC_SDOREPLY, /* [0x1F80,0x00] NMT Startup (Unsigned32) */ \
  ODLOC_ODENTRY , /* [0x2000,0x00] LEDControl (Unsigned8) */ \
  ODLOC_ODENTRY , /* [0x2100,0x00] MaxFlowRate (Unsigned16) */ \
  ODLOC_ODENTRY , /* [0x2102,0x00] EmergencyStopState (Boolean) */ \
  ODLOC_ODENTRY , /* [0x2200,0x00] FlowCorrectionFactor (Real32) */ \
  ODLOC_ODENTRY , /* [0x2300,0x00] DoseVolume (Unsigned32) */ \
  ODLOC_ODENTRY , /* [0x2301,0x00] DoseFlowRate (Integer16) */ \
  ODLOC_ODENTRY , /* [0x2302,0x00] DoseCommand (Unsigned8) */ \
  ODLOC_ODENTRY , /* [0x2303,0x00] DoseStatus (Unsigned8) */ \
  ODLOC_ODENTRY , /* [0x2304,0x00] DoseDelivered (Unsigned32) */ \
  ODLOC_ODENTRY , /* [0x2305,0x00] DoseTimeout (Unsigned16) */ \
  ODLOC_ODENTRY , /* [0x2400,0x00] PumpState (Unsigned8) */ \
  ODLOC_ODENTRY , /* [0x6040,0x00] ControlWord (Unsigned16) */ \
  ODLOC_ODENTRY , /* [0x6041,0x00] StatusWord (Unsigned16) */ \
  ODLOC_ODENTRY , /* [0x6042,0x00] TargetFlowRate (Integer16) */ \
  ODLOC_ODENTRY , /* [0x6043,0x00] ActualFlowRate (Integer16) */ \

// 1 MACROS WERE GENERATED TO HOLD THE LIST OF OD ENTRY TYPES
// USE THE FOLLOWING INITIALIZER:
// OD_ID_TABLELOCATION 

#endif // USE_CANOPEN_FD

#endif // _ENTRIESANDREPLIESH_
