// Process Image File
// Generated by CANopen Architect Professional 11.62.6737 on 5/30/2026 11:33:10 AM
// Generated from project E:\ursaScience\Modules\Modules-1000kbs.cax
// Generated from EDS 'PumpModule-n02-250kbs' 05-24-2026 11:27AM by Dakota Ward
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _PIMGH_
#define _PIMGH_

// EDS configuration usage
// 1 = configuration was used when this file was generated
#define EDSCONFIGURATION_ALL_ENTRIES 1

// EDS group usage
// 1 = group was used when this file was generated

// set to 1 to use this stack config
#define AUTO_GENERATED_STACK_CONFIG 1

#if (AUTO_GENERATED_STACK_CONFIG == 1)
// stack configuration

// if no stack version defined then assume version 5.xx
#ifndef _MCOPVERSION_
#define _MCOPVERSION_ 5
#endif

// Maximum number of receive PDOs
#define NR_OF_RPDOS       1

// Maximum number of transmit PDOs
#define NR_OF_TPDOS       2

// Default Node ID of this node
#if _MCOPVERSION_ >= 6
#define NODEID_DCF         0x02
#define DEFAULT_EMCY_COBID 0x00000080L + NODEID_DCF
#else
#define NODE_ID            0x02
#define DEFAULT_EMCY_COBID 0x00000080L + NODE_ID
#endif

// device type
#define OD_DEVICE_TYPE    0x00020192L

// Identity Object data [1018]
// Note: the values in Device -> Information are not used for this piece of code,
// only the values in [1018] are used
#define OD_VENDOR_ID      0x00000123L
#define OD_PRODUCT_CODE   0x00000003L
#define OD_REVISION       0x00010001L
#define OD_SERIAL_NUMBER  0x00123456L

// Specify the default heartbeat here
#define DEFAULT_HEARTBEAT 1000

// Defines the maximum number of heartbeat consumers
#define NR_OF_HB_CONSUMER 4

// Defines the maximum number of emergency consumers
#define NR_OF_EMCY_CONSUMERS 4

// Defines the emergency inhibit time (x100us)
#define EMCY_INHIBIT_TIME 0

#endif // AUTO_GENERATED_STACK_CONFIG == 1

// [6040,00] Unsigned16
#define P604000_ControlWord 0x00000000
#define PControlWord_604000 P604000_ControlWord
#define P604000 P604000_ControlWord
#define P0x60400x00 P604000_ControlWord
// The uppercase versions are deprecated
#define P604000_CONTROLWORD P604000_ControlWord
#define PCONTROLWORD_604000 P604000_ControlWord
// [6042,00] Integer16
#define P604200_TargetFlowRate 0x00000002
#define PTargetFlowRate_604200 P604200_TargetFlowRate
#define P604200 P604200_TargetFlowRate
#define P0x60420x00 P604200_TargetFlowRate
// The uppercase versions are deprecated
#define P604200_TARGETFLOWRATE P604200_TargetFlowRate
#define PTARGETFLOWRATE_604200 P604200_TargetFlowRate
// [6041,00] Unsigned16
#define P604100_StatusWord 0x00000004
#define PStatusWord_604100 P604100_StatusWord
#define P604100 P604100_StatusWord
#define P0x60410x00 P604100_StatusWord
// The uppercase versions are deprecated
#define P604100_STATUSWORD P604100_StatusWord
#define PSTATUSWORD_604100 P604100_StatusWord
// [6043,00] Integer16
#define P604300_ActualFlowRate 0x00000006
#define PActualFlowRate_604300 P604300_ActualFlowRate
#define P604300 P604300_ActualFlowRate
#define P0x60430x00 P604300_ActualFlowRate
// The uppercase versions are deprecated
#define P604300_ACTUALFLOWRATE P604300_ActualFlowRate
#define PACTUALFLOWRATE_604300 P604300_ActualFlowRate
// [2400,00] Unsigned8
#define P240000_PumpState 0x00000008
#define PPumpState_240000 P240000_PumpState
#define P240000 P240000_PumpState
#define P0x24000x00 P240000_PumpState
// The uppercase versions are deprecated
#define P240000_PUMPSTATE P240000_PumpState
#define PPUMPSTATE_240000 P240000_PumpState
// [1001,00] Unsigned8
#define P100100_Error_Register 0x00000009
#define PError_Register_100100 P100100_Error_Register
#define P100100 P100100_Error_Register
#define P0x10010x00 P100100_Error_Register
// The uppercase versions are deprecated
#define P100100_ERROR_REGISTER P100100_Error_Register
#define PERROR_REGISTER_100100 P100100_Error_Register
// [2304,00] Unsigned32
#define P230400_DoseDelivered 0x0000000A
#define PDoseDelivered_230400 P230400_DoseDelivered
#define P230400 P230400_DoseDelivered
#define P0x23040x00 P230400_DoseDelivered
// The uppercase versions are deprecated
#define P230400_DOSEDELIVERED P230400_DoseDelivered
#define PDOSEDELIVERED_230400 P230400_DoseDelivered
// [1002,00] Unsigned32
#define P100200_Manufacturer_Status_Register 0x00000010
#define PManufacturer_Status_Register_100200 P100200_Manufacturer_Status_Register
#define P100200 P100200_Manufacturer_Status_Register
#define P0x10020x00 P100200_Manufacturer_Status_Register
// The uppercase versions are deprecated
#define P100200_MANUFACTURER_STATUS_REGISTER P100200_Manufacturer_Status_Register
#define PMANUFACTURER_STATUS_REGISTER_100200 P100200_Manufacturer_Status_Register
// [1006,00] Unsigned32
#define P100600_Communication_Cycle_Period 0x00000014
#define PCommunication_Cycle_Period_100600 P100600_Communication_Cycle_Period
#define P100600 P100600_Communication_Cycle_Period
#define P0x10060x00 P100600_Communication_Cycle_Period
// The uppercase versions are deprecated
#define P100600_COMMUNICATION_CYCLE_PERIOD P100600_Communication_Cycle_Period
#define PCOMMUNICATION_CYCLE_PERIOD_100600 P100600_Communication_Cycle_Period
// [1007,00] Unsigned32
#define P100700_Synchronous_Window_Length 0x00000018
#define PSynchronous_Window_Length_100700 P100700_Synchronous_Window_Length
#define P100700 P100700_Synchronous_Window_Length
#define P0x10070x00 P100700_Synchronous_Window_Length
// The uppercase versions are deprecated
#define P100700_SYNCHRONOUS_WINDOW_LENGTH P100700_Synchronous_Window_Length
#define PSYNCHRONOUS_WINDOW_LENGTH_100700 P100700_Synchronous_Window_Length
// [1008,00] VisibleString
#define P100800_Manufacturer_Device_Name 0x0000001C
#define PManufacturer_Device_Name_100800 P100800_Manufacturer_Device_Name
#define P100800 P100800_Manufacturer_Device_Name
#define P0x10080x00 P100800_Manufacturer_Device_Name
// The uppercase versions are deprecated
#define P100800_MANUFACTURER_DEVICE_NAME P100800_Manufacturer_Device_Name
#define PMANUFACTURER_DEVICE_NAME_100800 P100800_Manufacturer_Device_Name
// [1009,00] VisibleString
#define P100900_Manufacturer_Hardware_Version 0x00000027
#define PManufacturer_Hardware_Version_100900 P100900_Manufacturer_Hardware_Version
#define P100900 P100900_Manufacturer_Hardware_Version
#define P0x10090x00 P100900_Manufacturer_Hardware_Version
// The uppercase versions are deprecated
#define P100900_MANUFACTURER_HARDWARE_VERSION P100900_Manufacturer_Hardware_Version
#define PMANUFACTURER_HARDWARE_VERSION_100900 P100900_Manufacturer_Hardware_Version
// [100A,00] VisibleString
#define P100A00_Manufacturer_Software_Version 0x0000002A
#define PManufacturer_Software_Version_100A00 P100A00_Manufacturer_Software_Version
#define P100A00 P100A00_Manufacturer_Software_Version
#define P0x100A0x00 P100A00_Manufacturer_Software_Version
// The uppercase versions are deprecated
#define P100A00_MANUFACTURER_SOFTWARE_VERSION P100A00_Manufacturer_Software_Version
#define PMANUFACTURER_SOFTWARE_VERSION_100A00 P100A00_Manufacturer_Software_Version
// [1012,00] Unsigned32
#define P101200_Time_Stamp_COB_ID 0x0000002D
#define PTime_Stamp_COB_ID_101200 P101200_Time_Stamp_COB_ID
#define P101200 P101200_Time_Stamp_COB_ID
#define P0x10120x00 P101200_Time_Stamp_COB_ID
// The uppercase versions are deprecated
#define P101200_TIME_STAMP_COB_ID P101200_Time_Stamp_COB_ID
#define PTIME_STAMP_COB_ID_101200 P101200_Time_Stamp_COB_ID
// [1013,00] Unsigned32
#define P101300_High_Resolution_Time_Stamp 0x00000031
#define PHigh_Resolution_Time_Stamp_101300 P101300_High_Resolution_Time_Stamp
#define P101300 P101300_High_Resolution_Time_Stamp
#define P0x10130x00 P101300_High_Resolution_Time_Stamp
// The uppercase versions are deprecated
#define P101300_HIGH_RESOLUTION_TIME_STAMP P101300_High_Resolution_Time_Stamp
#define PHIGH_RESOLUTION_TIME_STAMP_101300 P101300_High_Resolution_Time_Stamp
// [1018,01] Unsigned32
#define P101801_Vendor_ID 0x00000035
#define PVendor_ID_101801 P101801_Vendor_ID
#define P101801 P101801_Vendor_ID
#define P0x10180x01 P101801_Vendor_ID
// The uppercase versions are deprecated
#define P101801_VENDOR_ID P101801_Vendor_ID
#define PVENDOR_ID_101801 P101801_Vendor_ID
// [1018,02] Unsigned32
#define P101802_Product_Code 0x00000039
#define PProduct_Code_101802 P101802_Product_Code
#define P101802 P101802_Product_Code
#define P0x10180x02 P101802_Product_Code
// The uppercase versions are deprecated
#define P101802_PRODUCT_CODE P101802_Product_Code
#define PPRODUCT_CODE_101802 P101802_Product_Code
// [1018,03] Unsigned32
#define P101803_Revision_Number 0x0000003D
#define PRevision_Number_101803 P101803_Revision_Number
#define P101803 P101803_Revision_Number
#define P0x10180x03 P101803_Revision_Number
// The uppercase versions are deprecated
#define P101803_REVISION_NUMBER P101803_Revision_Number
#define PREVISION_NUMBER_101803 P101803_Revision_Number
// [1018,04] Unsigned32
#define P101804_Serial_Number 0x00000041
#define PSerial_Number_101804 P101804_Serial_Number
#define P101804 P101804_Serial_Number
#define P0x10180x04 P101804_Serial_Number
// The uppercase versions are deprecated
#define P101804_SERIAL_NUMBER P101804_Serial_Number
#define PSERIAL_NUMBER_101804 P101804_Serial_Number
// [1020,01] Unsigned32
#define P102001_Configuration_Date 0x00000045
#define PConfiguration_Date_102001 P102001_Configuration_Date
#define P102001 P102001_Configuration_Date
#define P0x10200x01 P102001_Configuration_Date
// The uppercase versions are deprecated
#define P102001_CONFIGURATION_DATE P102001_Configuration_Date
#define PCONFIGURATION_DATE_102001 P102001_Configuration_Date
// [1020,02] Unsigned32
#define P102002_Configuration_Time 0x00000049
#define PConfiguration_Time_102002 P102002_Configuration_Time
#define P102002 P102002_Configuration_Time
#define P0x10200x02 P102002_Configuration_Time
// The uppercase versions are deprecated
#define P102002_CONFIGURATION_TIME P102002_Configuration_Time
#define PCONFIGURATION_TIME_102002 P102002_Configuration_Time
// [1200,01] Unsigned32
#define P120001_COB_ID_Client_to_Server 0x0000004D
#define PCOB_ID_Client_to_Server_120001 P120001_COB_ID_Client_to_Server
#define P120001 P120001_COB_ID_Client_to_Server
#define P0x12000x01 P120001_COB_ID_Client_to_Server
// The uppercase versions are deprecated
#define P120001_COB_ID_CLIENT_TO_SERVER P120001_COB_ID_Client_to_Server
#define PCOB_ID_CLIENT_TO_SERVER_120001 P120001_COB_ID_Client_to_Server
// [1200,02] Unsigned32
#define P120002_COB_ID_Server_to_Client 0x00000051
#define PCOB_ID_Server_to_Client_120002 P120002_COB_ID_Server_to_Client
#define P120002 P120002_COB_ID_Server_to_Client
#define P0x12000x02 P120002_COB_ID_Server_to_Client
// The uppercase versions are deprecated
#define P120002_COB_ID_SERVER_TO_CLIENT P120002_COB_ID_Server_to_Client
#define PCOB_ID_SERVER_TO_CLIENT_120002 P120002_COB_ID_Server_to_Client
// [2000,00] Unsigned8
#define P200000_LEDControl 0x00000055
#define PLEDControl_200000 P200000_LEDControl
#define P200000 P200000_LEDControl
#define P0x20000x00 P200000_LEDControl
// The uppercase versions are deprecated
#define P200000_LEDCONTROL P200000_LEDControl
#define PLEDCONTROL_200000 P200000_LEDControl
// [2100,00] Unsigned16
#define P210000_MaxFlowRate 0x00000056
#define PMaxFlowRate_210000 P210000_MaxFlowRate
#define P210000 P210000_MaxFlowRate
#define P0x21000x00 P210000_MaxFlowRate
// The uppercase versions are deprecated
#define P210000_MAXFLOWRATE P210000_MaxFlowRate
#define PMAXFLOWRATE_210000 P210000_MaxFlowRate
// [2102,00] Boolean
#define P210200_EmergencyStopState 0x00000058
#define PEmergencyStopState_210200 P210200_EmergencyStopState
#define P210200 P210200_EmergencyStopState
#define P0x21020x00 P210200_EmergencyStopState
// The uppercase versions are deprecated
#define P210200_EMERGENCYSTOPSTATE P210200_EmergencyStopState
#define PEMERGENCYSTOPSTATE_210200 P210200_EmergencyStopState
// [2200,00] Real32
#define P220000_FlowCorrectionFactor 0x00000059
#define PFlowCorrectionFactor_220000 P220000_FlowCorrectionFactor
#define P220000 P220000_FlowCorrectionFactor
#define P0x22000x00 P220000_FlowCorrectionFactor
// The uppercase versions are deprecated
#define P220000_FLOWCORRECTIONFACTOR P220000_FlowCorrectionFactor
#define PFLOWCORRECTIONFACTOR_220000 P220000_FlowCorrectionFactor
// [2300,00] Unsigned32
#define P230000_DoseVolume 0x0000005D
#define PDoseVolume_230000 P230000_DoseVolume
#define P230000 P230000_DoseVolume
#define P0x23000x00 P230000_DoseVolume
// The uppercase versions are deprecated
#define P230000_DOSEVOLUME P230000_DoseVolume
#define PDOSEVOLUME_230000 P230000_DoseVolume
// [2301,00] Integer16
#define P230100_DoseFlowRate 0x00000061
#define PDoseFlowRate_230100 P230100_DoseFlowRate
#define P230100 P230100_DoseFlowRate
#define P0x23010x00 P230100_DoseFlowRate
// The uppercase versions are deprecated
#define P230100_DOSEFLOWRATE P230100_DoseFlowRate
#define PDOSEFLOWRATE_230100 P230100_DoseFlowRate
// [2302,00] Unsigned8
#define P230200_DoseCommand 0x00000063
#define PDoseCommand_230200 P230200_DoseCommand
#define P230200 P230200_DoseCommand
#define P0x23020x00 P230200_DoseCommand
// The uppercase versions are deprecated
#define P230200_DOSECOMMAND P230200_DoseCommand
#define PDOSECOMMAND_230200 P230200_DoseCommand
// [2303,00] Unsigned8
#define P230300_DoseStatus 0x00000064
#define PDoseStatus_230300 P230300_DoseStatus
#define P230300 P230300_DoseStatus
#define P0x23030x00 P230300_DoseStatus
// The uppercase versions are deprecated
#define P230300_DOSESTATUS P230300_DoseStatus
#define PDOSESTATUS_230300 P230300_DoseStatus
// [2305,00] Unsigned16
#define P230500_DoseTimeout 0x00000065
#define PDoseTimeout_230500 P230500_DoseTimeout
#define P230500 P230500_DoseTimeout
#define P0x23050x00 P230500_DoseTimeout
// The uppercase versions are deprecated
#define P230500_DOSETIMEOUT P230500_DoseTimeout
#define PDOSETIMEOUT_230500 P230500_DoseTimeout

// last byte used in process image
#define PIMGEND 0x00000066

// sizes for entries in the process image in bytes
#define SIZEOF_6040_00_CONTROLWORD 2
#define SIZEOF_6042_00_TARGETFLOWRATE 2
#define SIZEOF_6041_00_STATUSWORD 2
#define SIZEOF_6043_00_ACTUALFLOWRATE 2
#define SIZEOF_2400_00_PUMPSTATE 1
#define SIZEOF_1001_00_ERROR_REGISTER 1
#define SIZEOF_2304_00_DOSEDELIVERED 4
#define SIZEOF_1002_00_MANUFACTURER_STATUS_REGISTER 4
#define SIZEOF_1006_00_COMMUNICATION_CYCLE_PERIOD 4
#define SIZEOF_1007_00_SYNCHRONOUS_WINDOW_LENGTH 4
#define SIZEOF_1008_00_MANUFACTURER_DEVICE_NAME 11
#define SIZEOF_1009_00_MANUFACTURER_HARDWARE_VERSION 3
#define SIZEOF_100A_00_MANUFACTURER_SOFTWARE_VERSION 3
#define SIZEOF_1012_00_TIME_STAMP_COB_ID 4
#define SIZEOF_1013_00_HIGH_RESOLUTION_TIME_STAMP 4
#define SIZEOF_1018_01_VENDOR_ID 4
#define SIZEOF_1018_02_PRODUCT_CODE 4
#define SIZEOF_1018_03_REVISION_NUMBER 4
#define SIZEOF_1018_04_SERIAL_NUMBER 4
#define SIZEOF_1020_01_CONFIGURATION_DATE 4
#define SIZEOF_1020_02_CONFIGURATION_TIME 4
#define SIZEOF_1200_01_COB_ID_CLIENT_TO_SERVER 4
#define SIZEOF_1200_02_COB_ID_SERVER_TO_CLIENT 4
#define SIZEOF_2000_00_LEDCONTROL 1
#define SIZEOF_2100_00_MAXFLOWRATE 2
#define SIZEOF_2102_00_EMERGENCYSTOPSTATE 1
#define SIZEOF_2200_00_FLOWCORRECTIONFACTOR 4
#define SIZEOF_2300_00_DOSEVOLUME 4
#define SIZEOF_2301_00_DOSEFLOWRATE 2
#define SIZEOF_2302_00_DOSECOMMAND 1
#define SIZEOF_2303_00_DOSESTATUS 1
#define SIZEOF_2305_00_DOSETIMEOUT 2

// default values for process image
#define PIMGDEFAULTS { \
/*[6040,00]*/        0x00, 0x00, \
/*[6042,00]*/        0x00, 0x00, \
/*[6041,00]*/        0x40, 0x00, \
/*[6043,00]*/        0x00, 0x00, \
/*[2400,00]*/        0x01, \
/*[1001,00]*/        0x00, \
/*[2304,00]*/        0x00, 0x00, 0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[1002,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1006,00]*/        0xA0, 0x86, 0x01, 0x00, \
/*[1007,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x50, 0x75, 0x6D, 0x70, 0x20, 0x4D, 0x6F, 0x64, 0x75, 0x6C, \
                     0x65, \
/*[1009,00]*/        0x31, 0x2E, 0x30, \
/*[100A,00]*/        0x31, 0x2E, 0x30, \
/*[1012,00]*/        0x00, 0x01, 0x00, 0x00, \
/*[1013,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x23, 0x01, 0x00, 0x00, \
/*[1018,02]*/        0x03, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x01, 0x00, 0x01, 0x00, \
/*[1018,04]*/        0x56, 0x34, 0x12, 0x00, \
/*[1020,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[2100,00]*/        0xC8, 0x00, \
/*[2102,00]*/        0x00, \
/*[2200,00]*/        0x8D, 0x97, 0x96, 0x3F, \
/*[2300,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[2301,00]*/        0x64, 0x00, \
/*[2302,00]*/        0x00, \
/*[2303,00]*/        0x00, \
/*[2305,00]*/        0x2C, 0x01, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGDEFAULTS 

// minimum values for process image
#define PIMGMINS { \
/*[6040,00]*/        0x00, 0x00, \
/*[6042,00]*/        0x00, 0x00, \
/*[6041,00]*/        0x00, 0x00, \
/*[6043,00]*/        0x00, 0x00, \
/*[2400,00]*/        0x00, \
/*[1001,00]*/        0x00, \
/*[2304,00]*/        0x00, 0x00, 0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[1002,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1006,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1007,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1009,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[100A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1012,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1013,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[2100,00]*/        0x00, 0x00, \
/*[2102,00]*/        0x00, \
/*[2200,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[2300,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[2301,00]*/        0x00, 0x00, \
/*[2302,00]*/        0x00, \
/*[2303,00]*/        0x00, \
/*[2305,00]*/        0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMINS 

// maximum values for process image
#define PIMGMAXS { \
/*[6040,00]*/        0x00, 0x00, \
/*[6042,00]*/        0x00, 0x00, \
/*[6041,00]*/        0x00, 0x00, \
/*[6043,00]*/        0x00, 0x00, \
/*[2400,00]*/        0x00, \
/*[1001,00]*/        0x00, \
/*[2304,00]*/        0x00, 0x00, 0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[1002,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1006,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1007,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1009,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[100A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1012,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1013,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[2100,00]*/        0x00, 0x00, \
/*[2102,00]*/        0x00, \
/*[2200,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[2300,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[2301,00]*/        0x00, 0x00, \
/*[2302,00]*/        0x00, \
/*[2303,00]*/        0x00, \
/*[2305,00]*/        0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMAXS 

// Example usage: PIMG_OFFSET(0x1000, 0x00)
#define PIMG_OFFSET(index, subindex) P##index##subindex

#endif // _PIMGH_
