// Process Image File
// Generated by CANopen Architect Professional 11.62.6737 on 8/21/2026 10:47:43 AM
// Generated from project E:\ursaScience\Modules\Modules-1000kbs.cax
// Generated from EDS 'PumpModule-n01-250kbs' 08-21-2026 10:46AM by Dakota Ward
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _PIMGH_
#define _PIMGH_

// EDS configuration usage
// 1 = configuration was used when this file was generated
#define EDSCONFIGURATION_ALL_ENTRIES 1

// EDS group usage
// 1 = group was used when this file was generated

// set to 1 to use this stack config
#define AUTO_GENERATED_STACK_CONFIG 1

#if (AUTO_GENERATED_STACK_CONFIG == 1)
// stack configuration

// if no stack version defined then assume version 5.xx
#ifndef _MCOPVERSION_
#define _MCOPVERSION_ 5
#endif

// Maximum number of receive PDOs
#define NR_OF_RPDOS       1

// Maximum number of transmit PDOs
#define NR_OF_TPDOS       2

// Default Node ID of this node
#if _MCOPVERSION_ >= 6
#define NODEID_DCF         0x01
#define DEFAULT_EMCY_COBID 0x00000080L + NODEID_DCF
#else
#define NODE_ID            0x01
#define DEFAULT_EMCY_COBID 0x00000080L + NODE_ID
#endif

// device type
#define OD_DEVICE_TYPE    0x00020192L

// Identity Object data [1018]
// Note: the values in Device -> Information are not used for this piece of code,
// only the values in [1018] are used
#define OD_VENDOR_ID      0x00000123L
#define OD_PRODUCT_CODE   0x00000003L
#define OD_REVISION       0x00010001L
#define OD_SERIAL_NUMBER  0x00123456L

// Specify the default heartbeat here
#define DEFAULT_HEARTBEAT 1000

// Defines the maximum number of heartbeat consumers
#define NR_OF_HB_CONSUMER 4

// Defines the maximum number of emergency consumers
#define NR_OF_EMCY_CONSUMERS 4

// Defines the emergency inhibit time (x100us)
#define EMCY_INHIBIT_TIME 0

#endif // AUTO_GENERATED_STACK_CONFIG == 1

// [6040,00] Unsigned16
#define P604000_ControlWord 0x00000000
#define PControlWord_604000 P604000_ControlWord
#define P604000 P604000_ControlWord
#define P0x60400x00 P604000_ControlWord
// The uppercase versions are deprecated
#define P604000_CONTROLWORD P604000_ControlWord
#define PCONTROLWORD_604000 P604000_ControlWord
// [2600,00] Integer16
#define P260000_StepRate 0x00000002
#define PStepRate_260000 P260000_StepRate
#define P260000 P260000_StepRate
#define P0x26000x00 P260000_StepRate
// The uppercase versions are deprecated
#define P260000_STEPRATE P260000_StepRate
#define PSTEPRATE_260000 P260000_StepRate
// [2601,00] Unsigned32
#define P260100_TargetSteps 0x00000004
#define PTargetSteps_260100 P260100_TargetSteps
#define P260100 P260100_TargetSteps
#define P0x26010x00 P260100_TargetSteps
// The uppercase versions are deprecated
#define P260100_TARGETSTEPS P260100_TargetSteps
#define PTARGETSTEPS_260100 P260100_TargetSteps
// [6041,00] Unsigned16
#define P604100_StatusWord 0x00000008
#define PStatusWord_604100 P604100_StatusWord
#define P604100 P604100_StatusWord
#define P0x60410x00 P604100_StatusWord
// The uppercase versions are deprecated
#define P604100_STATUSWORD P604100_StatusWord
#define PSTATUSWORD_604100 P604100_StatusWord
// [2602,00] Integer16
#define P260200_ActualStepRate 0x0000000A
#define PActualStepRate_260200 P260200_ActualStepRate
#define P260200 P260200_ActualStepRate
#define P0x26020x00 P260200_ActualStepRate
// The uppercase versions are deprecated
#define P260200_ACTUALSTEPRATE P260200_ActualStepRate
#define PACTUALSTEPRATE_260200 P260200_ActualStepRate
// [2400,00] Unsigned8
#define P240000_PumpState 0x0000000C
#define PPumpState_240000 P240000_PumpState
#define P240000 P240000_PumpState
#define P0x24000x00 P240000_PumpState
// The uppercase versions are deprecated
#define P240000_PUMPSTATE P240000_PumpState
#define PPUMPSTATE_240000 P240000_PumpState
// [1001,00] Unsigned8
#define P100100_Error_Register 0x0000000D
#define PError_Register_100100 P100100_Error_Register
#define P100100 P100100_Error_Register
#define P0x10010x00 P100100_Error_Register
// The uppercase versions are deprecated
#define P100100_ERROR_REGISTER P100100_Error_Register
#define PERROR_REGISTER_100100 P100100_Error_Register
// [2603,00] Unsigned32
#define P260300_StepsRemaining 0x0000000E
#define PStepsRemaining_260300 P260300_StepsRemaining
#define P260300 P260300_StepsRemaining
#define P0x26030x00 P260300_StepsRemaining
// The uppercase versions are deprecated
#define P260300_STEPSREMAINING P260300_StepsRemaining
#define PSTEPSREMAINING_260300 P260300_StepsRemaining
// [1002,00] Unsigned32
#define P100200_Manufacturer_Status_Register 0x00000014
#define PManufacturer_Status_Register_100200 P100200_Manufacturer_Status_Register
#define P100200 P100200_Manufacturer_Status_Register
#define P0x10020x00 P100200_Manufacturer_Status_Register
// The uppercase versions are deprecated
#define P100200_MANUFACTURER_STATUS_REGISTER P100200_Manufacturer_Status_Register
#define PMANUFACTURER_STATUS_REGISTER_100200 P100200_Manufacturer_Status_Register
// [1006,00] Unsigned32
#define P100600_Communication_Cycle_Period 0x00000018
#define PCommunication_Cycle_Period_100600 P100600_Communication_Cycle_Period
#define P100600 P100600_Communication_Cycle_Period
#define P0x10060x00 P100600_Communication_Cycle_Period
// The uppercase versions are deprecated
#define P100600_COMMUNICATION_CYCLE_PERIOD P100600_Communication_Cycle_Period
#define PCOMMUNICATION_CYCLE_PERIOD_100600 P100600_Communication_Cycle_Period
// [1007,00] Unsigned32
#define P100700_Synchronous_Window_Length 0x0000001C
#define PSynchronous_Window_Length_100700 P100700_Synchronous_Window_Length
#define P100700 P100700_Synchronous_Window_Length
#define P0x10070x00 P100700_Synchronous_Window_Length
// The uppercase versions are deprecated
#define P100700_SYNCHRONOUS_WINDOW_LENGTH P100700_Synchronous_Window_Length
#define PSYNCHRONOUS_WINDOW_LENGTH_100700 P100700_Synchronous_Window_Length
// [1008,00] VisibleString
#define P100800_Manufacturer_Device_Name 0x00000020
#define PManufacturer_Device_Name_100800 P100800_Manufacturer_Device_Name
#define P100800 P100800_Manufacturer_Device_Name
#define P0x10080x00 P100800_Manufacturer_Device_Name
// The uppercase versions are deprecated
#define P100800_MANUFACTURER_DEVICE_NAME P100800_Manufacturer_Device_Name
#define PMANUFACTURER_DEVICE_NAME_100800 P100800_Manufacturer_Device_Name
// [1009,00] VisibleString
#define P100900_Manufacturer_Hardware_Version 0x0000002B
#define PManufacturer_Hardware_Version_100900 P100900_Manufacturer_Hardware_Version
#define P100900 P100900_Manufacturer_Hardware_Version
#define P0x10090x00 P100900_Manufacturer_Hardware_Version
// The uppercase versions are deprecated
#define P100900_MANUFACTURER_HARDWARE_VERSION P100900_Manufacturer_Hardware_Version
#define PMANUFACTURER_HARDWARE_VERSION_100900 P100900_Manufacturer_Hardware_Version
// [100A,00] VisibleString
#define P100A00_Manufacturer_Software_Version 0x0000002E
#define PManufacturer_Software_Version_100A00 P100A00_Manufacturer_Software_Version
#define P100A00 P100A00_Manufacturer_Software_Version
#define P0x100A0x00 P100A00_Manufacturer_Software_Version
// The uppercase versions are deprecated
#define P100A00_MANUFACTURER_SOFTWARE_VERSION P100A00_Manufacturer_Software_Version
#define PMANUFACTURER_SOFTWARE_VERSION_100A00 P100A00_Manufacturer_Software_Version
// [1012,00] Unsigned32
#define P101200_Time_Stamp_COB_ID 0x00000031
#define PTime_Stamp_COB_ID_101200 P101200_Time_Stamp_COB_ID
#define P101200 P101200_Time_Stamp_COB_ID
#define P0x10120x00 P101200_Time_Stamp_COB_ID
// The uppercase versions are deprecated
#define P101200_TIME_STAMP_COB_ID P101200_Time_Stamp_COB_ID
#define PTIME_STAMP_COB_ID_101200 P101200_Time_Stamp_COB_ID
// [1013,00] Unsigned32
#define P101300_High_Resolution_Time_Stamp 0x00000035
#define PHigh_Resolution_Time_Stamp_101300 P101300_High_Resolution_Time_Stamp
#define P101300 P101300_High_Resolution_Time_Stamp
#define P0x10130x00 P101300_High_Resolution_Time_Stamp
// The uppercase versions are deprecated
#define P101300_HIGH_RESOLUTION_TIME_STAMP P101300_High_Resolution_Time_Stamp
#define PHIGH_RESOLUTION_TIME_STAMP_101300 P101300_High_Resolution_Time_Stamp
// [1018,01] Unsigned32
#define P101801_Vendor_ID 0x00000039
#define PVendor_ID_101801 P101801_Vendor_ID
#define P101801 P101801_Vendor_ID
#define P0x10180x01 P101801_Vendor_ID
// The uppercase versions are deprecated
#define P101801_VENDOR_ID P101801_Vendor_ID
#define PVENDOR_ID_101801 P101801_Vendor_ID
// [1018,02] Unsigned32
#define P101802_Product_Code 0x0000003D
#define PProduct_Code_101802 P101802_Product_Code
#define P101802 P101802_Product_Code
#define P0x10180x02 P101802_Product_Code
// The uppercase versions are deprecated
#define P101802_PRODUCT_CODE P101802_Product_Code
#define PPRODUCT_CODE_101802 P101802_Product_Code
// [1018,03] Unsigned32
#define P101803_Revision_Number 0x00000041
#define PRevision_Number_101803 P101803_Revision_Number
#define P101803 P101803_Revision_Number
#define P0x10180x03 P101803_Revision_Number
// The uppercase versions are deprecated
#define P101803_REVISION_NUMBER P101803_Revision_Number
#define PREVISION_NUMBER_101803 P101803_Revision_Number
// [1018,04] Unsigned32
#define P101804_Serial_Number 0x00000045
#define PSerial_Number_101804 P101804_Serial_Number
#define P101804 P101804_Serial_Number
#define P0x10180x04 P101804_Serial_Number
// The uppercase versions are deprecated
#define P101804_SERIAL_NUMBER P101804_Serial_Number
#define PSERIAL_NUMBER_101804 P101804_Serial_Number
// [1020,01] Unsigned32
#define P102001_Configuration_Date 0x00000049
#define PConfiguration_Date_102001 P102001_Configuration_Date
#define P102001 P102001_Configuration_Date
#define P0x10200x01 P102001_Configuration_Date
// The uppercase versions are deprecated
#define P102001_CONFIGURATION_DATE P102001_Configuration_Date
#define PCONFIGURATION_DATE_102001 P102001_Configuration_Date
// [1020,02] Unsigned32
#define P102002_Configuration_Time 0x0000004D
#define PConfiguration_Time_102002 P102002_Configuration_Time
#define P102002 P102002_Configuration_Time
#define P0x10200x02 P102002_Configuration_Time
// The uppercase versions are deprecated
#define P102002_CONFIGURATION_TIME P102002_Configuration_Time
#define PCONFIGURATION_TIME_102002 P102002_Configuration_Time
// [1200,01] Unsigned32
#define P120001_COB_ID_Client_to_Server 0x00000051
#define PCOB_ID_Client_to_Server_120001 P120001_COB_ID_Client_to_Server
#define P120001 P120001_COB_ID_Client_to_Server
#define P0x12000x01 P120001_COB_ID_Client_to_Server
// The uppercase versions are deprecated
#define P120001_COB_ID_CLIENT_TO_SERVER P120001_COB_ID_Client_to_Server
#define PCOB_ID_CLIENT_TO_SERVER_120001 P120001_COB_ID_Client_to_Server
// [1200,02] Unsigned32
#define P120002_COB_ID_Server_to_Client 0x00000055
#define PCOB_ID_Server_to_Client_120002 P120002_COB_ID_Server_to_Client
#define P120002 P120002_COB_ID_Server_to_Client
#define P0x12000x02 P120002_COB_ID_Server_to_Client
// The uppercase versions are deprecated
#define P120002_COB_ID_SERVER_TO_CLIENT P120002_COB_ID_Server_to_Client
#define PCOB_ID_SERVER_TO_CLIENT_120002 P120002_COB_ID_Server_to_Client
// [2000,00] Unsigned8
#define P200000_LEDControl 0x00000059
#define PLEDControl_200000 P200000_LEDControl
#define P200000 P200000_LEDControl
#define P0x20000x00 P200000_LEDControl
// The uppercase versions are deprecated
#define P200000_LEDCONTROL P200000_LEDControl
#define PLEDCONTROL_200000 P200000_LEDControl
// [2500,00] Unsigned8
#define P250000_TMCInitStatus 0x0000005A
#define PTMCInitStatus_250000 P250000_TMCInitStatus
#define P250000 P250000_TMCInitStatus
#define P0x25000x00 P250000_TMCInitStatus
// The uppercase versions are deprecated
#define P250000_TMCINITSTATUS P250000_TMCInitStatus
#define PTMCINITSTATUS_250000 P250000_TMCInitStatus
// [2501,00] Unsigned8
#define P250100_TMCInitFailedStep 0x0000005B
#define PTMCInitFailedStep_250100 P250100_TMCInitFailedStep
#define P250100 P250100_TMCInitFailedStep
#define P0x25010x00 P250100_TMCInitFailedStep
// The uppercase versions are deprecated
#define P250100_TMCINITFAILEDSTEP P250100_TMCInitFailedStep
#define PTMCINITFAILEDSTEP_250100 P250100_TMCInitFailedStep
// [2502,00] Unsigned32
#define P250200_LastDrvStatus 0x0000005C
#define PLastDrvStatus_250200 P250200_LastDrvStatus
#define P250200 P250200_LastDrvStatus
#define P0x25020x00 P250200_LastDrvStatus
// The uppercase versions are deprecated
#define P250200_LASTDRVSTATUS P250200_LastDrvStatus
#define PLASTDRVSTATUS_250200 P250200_LastDrvStatus
// [2503,00] Unsigned32
#define P250300_FaultSource 0x00000060
#define PFaultSource_250300 P250300_FaultSource
#define P250300 P250300_FaultSource
#define P0x25030x00 P250300_FaultSource
// The uppercase versions are deprecated
#define P250300_FAULTSOURCE P250300_FaultSource
#define PFAULTSOURCE_250300 P250300_FaultSource

// last byte used in process image
#define PIMGEND 0x00000063

// sizes for entries in the process image in bytes
#define SIZEOF_6040_00_CONTROLWORD 2
#define SIZEOF_2600_00_STEPRATE 2
#define SIZEOF_2601_00_TARGETSTEPS 4
#define SIZEOF_6041_00_STATUSWORD 2
#define SIZEOF_2602_00_ACTUALSTEPRATE 2
#define SIZEOF_2400_00_PUMPSTATE 1
#define SIZEOF_1001_00_ERROR_REGISTER 1
#define SIZEOF_2603_00_STEPSREMAINING 4
#define SIZEOF_1002_00_MANUFACTURER_STATUS_REGISTER 4
#define SIZEOF_1006_00_COMMUNICATION_CYCLE_PERIOD 4
#define SIZEOF_1007_00_SYNCHRONOUS_WINDOW_LENGTH 4
#define SIZEOF_1008_00_MANUFACTURER_DEVICE_NAME 11
#define SIZEOF_1009_00_MANUFACTURER_HARDWARE_VERSION 3
#define SIZEOF_100A_00_MANUFACTURER_SOFTWARE_VERSION 3
#define SIZEOF_1012_00_TIME_STAMP_COB_ID 4
#define SIZEOF_1013_00_HIGH_RESOLUTION_TIME_STAMP 4
#define SIZEOF_1018_01_VENDOR_ID 4
#define SIZEOF_1018_02_PRODUCT_CODE 4
#define SIZEOF_1018_03_REVISION_NUMBER 4
#define SIZEOF_1018_04_SERIAL_NUMBER 4
#define SIZEOF_1020_01_CONFIGURATION_DATE 4
#define SIZEOF_1020_02_CONFIGURATION_TIME 4
#define SIZEOF_1200_01_COB_ID_CLIENT_TO_SERVER 4
#define SIZEOF_1200_02_COB_ID_SERVER_TO_CLIENT 4
#define SIZEOF_2000_00_LEDCONTROL 1
#define SIZEOF_2500_00_TMCINITSTATUS 1
#define SIZEOF_2501_00_TMCINITFAILEDSTEP 1
#define SIZEOF_2502_00_LASTDRVSTATUS 4
#define SIZEOF_2503_00_FAULTSOURCE 4

// default values for process image
#define PIMGDEFAULTS { \
/*[6040,00]*/        0x00, 0x00, \
/*[2600,00]*/        0x00, 0x00, \
/*[2601,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6041,00]*/        0x40, 0x00, \
/*[2602,00]*/        0x00, 0x00, \
/*[2400,00]*/        0x01, \
/*[1001,00]*/        0x00, \
/*[2603,00]*/        0x00, 0x00, 0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[1002,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1006,00]*/        0xA0, 0x86, 0x01, 0x00, \
/*[1007,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x50, 0x75, 0x6D, 0x70, 0x20, 0x4D, 0x6F, 0x64, 0x75, 0x6C, \
                     0x65, \
/*[1009,00]*/        0x31, 0x2E, 0x30, \
/*[100A,00]*/        0x31, 0x2E, 0x30, \
/*[1012,00]*/        0x00, 0x01, 0x00, 0x00, \
/*[1013,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x23, 0x01, 0x00, 0x00, \
/*[1018,02]*/        0x03, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x01, 0x00, 0x01, 0x00, \
/*[1018,04]*/        0x56, 0x34, 0x12, 0x00, \
/*[1020,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[2500,00]*/        0x00, \
/*[2501,00]*/        0x00, \
/*[2502,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[2503,00]*/        0x00, 0x00, 0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGDEFAULTS 

// minimum values for process image
#define PIMGMINS { \
/*[6040,00]*/        0x00, 0x00, \
/*[2600,00]*/        0x00, 0x00, \
/*[2601,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6041,00]*/        0x00, 0x00, \
/*[2602,00]*/        0x00, 0x00, \
/*[2400,00]*/        0x00, \
/*[1001,00]*/        0x00, \
/*[2603,00]*/        0x00, 0x00, 0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[1002,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1006,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1007,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1009,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[100A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1012,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1013,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[2500,00]*/        0x00, \
/*[2501,00]*/        0x00, \
/*[2502,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[2503,00]*/        0x00, 0x00, 0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMINS 

// maximum values for process image
#define PIMGMAXS { \
/*[6040,00]*/        0x00, 0x00, \
/*[2600,00]*/        0x00, 0x00, \
/*[2601,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6041,00]*/        0x00, 0x00, \
/*[2602,00]*/        0x00, 0x00, \
/*[2400,00]*/        0x00, \
/*[1001,00]*/        0x00, \
/*[2603,00]*/        0x00, 0x00, 0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[1002,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1006,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1007,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1009,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[100A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1012,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1013,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1200,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[2500,00]*/        0x00, \
/*[2501,00]*/        0x00, \
/*[2502,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[2503,00]*/        0x06, 0x00, 0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMAXS 

// Example usage: PIMG_OFFSET(0x1000, 0x00)
#define PIMG_OFFSET(index, subindex) P##index##subindex

#endif // _PIMGH_
