// Initialization
// Generated by CANopen Architect Professional 11.62.6737 on 8/21/2026 10:47:43 AM
// Generated from project E:\ursaScience\Modules\Modules-1000kbs.cax
// Generated from EDS 'PumpModule-n01-250kbs' 08-21-2026 10:46AM by Dakota Ward
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _STACKINITH_
#define _STACKINITH_

#define FILE_VERSION 1
#define FILE_REVISION 0
#define DESCRIPTION "CanOpen EDS for Ursa Science Pump Module"

// CAN bitrate definitions as defined in CiA305
#ifndef CIA305_CAN_BITRATE_1000
#define CIA305_CAN_BITRATE_1000 0
#endif
#ifndef CIA305_CAN_BITRATE_800
#define CIA305_CAN_BITRATE_800  1
#endif
#ifndef CIA305_CAN_BITRATE_500
#define CIA305_CAN_BITRATE_500  2
#endif
#ifndef CIA305_CAN_BITRATE_250
#define CIA305_CAN_BITRATE_250  3
#endif
#ifndef CIA305_CAN_BITRATE_125
#define CIA305_CAN_BITRATE_125  4
#endif
#ifndef CIA305_CAN_BITRATE_50
#define CIA305_CAN_BITRATE_50   6
#endif
#ifndef CIA305_CAN_BITRATE_20
#define CIA305_CAN_BITRATE_20   7
#endif
#ifndef CIA305_CAN_BITRATE_10
#define CIA305_CAN_BITRATE_10   8
#endif
#ifndef CIA305_CAN_BITRATE_AUTO
#define CIA305_CAN_BITRATE_AUTO 9
#endif

// CAN bitrates supported by this device
#define CAN_BITRATE_SUPPORTED ( \
  (1U << CIA305_CAN_BITRATE_1000) | \
  (1U << CIA305_CAN_BITRATE_800 ) | \
  (1U << CIA305_CAN_BITRATE_500 ) | \
  (1U << CIA305_CAN_BITRATE_250 ) | \
  (1U << CIA305_CAN_BITRATE_125 ) | \
  (1U << CIA305_CAN_BITRATE_50  ) | \
  (1U << CIA305_CAN_BITRATE_20  ) | \
  (1U << CIA305_CAN_BITRATE_10  )   \
)

// Default CAN bitrate (kbps)
#define CAN_BITRATE_DCF 250


#ifdef MCO_USE_HANDLE
#define INITPDOS_CALLS \
MCO_InitRPDO(handle, 1, NODEID+0x00000200, 8, P604000_ControlWord); \
MCO_InitTPDOFull(handle, 1, NODEID+0x00000180, 0, 0, 1, 4, P604100_StatusWord); \
MCO_InitTPDOFull(handle, 2, NODEID+0x00000280, 0, 0, 1, 6, P240000_PumpState); \

#else
#define INITPDOS_CALLS \
MCO_InitRPDO(1, NODEID+0x00000200, 8, P604000_ControlWord); \
MCO_InitTPDOFull(1, NODEID+0x00000180, 0, 0, 1, 4, P604100_StatusWord); \
MCO_InitTPDOFull(2, NODEID+0x00000280, 0, 0, 1, 6, P240000_PumpState); \

#endif

#ifdef MCO_USE_HANDLE
#define INITHBCONSUMER_CALLS \

#else
#define INITHBCONSUMER_CALLS \

#endif

#ifdef MCO_USE_HANDLE
#define INITEMCYCONSUMER_CALLS \
MCOP_InitEMCYConsumer(handle, 1, 0x00000000); \
MCOP_InitEMCYConsumer(handle, 2, 0x00000000); \
MCOP_InitEMCYConsumer(handle, 3, 0x00000000); \
MCOP_InitEMCYConsumer(handle, 4, 0x00000000); \

#else
#define INITEMCYCONSUMER_CALLS \
MCOP_InitEMCYConsumer(1, 0x00000000); \
MCOP_InitEMCYConsumer(2, 0x00000000); \
MCOP_InitEMCYConsumer(3, 0x00000000); \
MCOP_InitEMCYConsumer(4, 0x00000000); \

#endif

#endif // _STACKINITH_
