// Process Image File
// Generated by CANopen Architect Professional 11.62.6737 on 5/24/2026 9:03:36 AM
// Generated from project E:\ursaScience\Modules\Modules-1000kbs.cax
// Generated from EDS 'Valve Module-n09-250kbs' 05-24-2026 09:02AM by Dakota Ward
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _PIMGH_
#define _PIMGH_

// EDS configuration usage
// 1 = configuration was used when this file was generated
#define EDSCONFIGURATION_ALL_ENTRIES 1

// EDS group usage
// 1 = group was used when this file was generated

// set to 1 to use this stack config
#define AUTO_GENERATED_STACK_CONFIG 1

#if (AUTO_GENERATED_STACK_CONFIG == 1)
// stack configuration

// if no stack version defined then assume version 5.xx
#ifndef _MCOPVERSION_
#define _MCOPVERSION_ 5
#endif

// Maximum number of receive PDOs
#define NR_OF_RPDOS       1

// Maximum number of transmit PDOs
#define NR_OF_TPDOS       2

// Default Node ID of this node
#if _MCOPVERSION_ >= 6
#define NODEID_DCF         0x09
#define DEFAULT_EMCY_COBID 0x00000080L + NODEID_DCF
#else
#define NODE_ID            0x09
#define DEFAULT_EMCY_COBID 0x00000080L + NODE_ID
#endif

// device type
#define OD_DEVICE_TYPE    0x00000408L

// Identity Object data [1018]
// Note: the values in Device -> Information are not used for this piece of code,
// only the values in [1018] are used
#define OD_VENDOR_ID      0x00000123L
#define OD_PRODUCT_CODE   0x00000005L
#define OD_REVISION       0x00010001L
#define OD_SERIAL_NUMBER  0x00123444L

// Specify the default heartbeat here
#define DEFAULT_HEARTBEAT 1000

// Defines the maximum number of heartbeat consumers
#define NR_OF_HB_CONSUMER 1

// Defines the maximum number of emergency consumers
#define NR_OF_EMCY_CONSUMERS 0

// Defines the emergency inhibit time (x100us)
#define EMCY_INHIBIT_TIME 0

#endif // AUTO_GENERATED_STACK_CONFIG == 1

// [6040,00] Unsigned16
#define P604000_ControlWord 0x00000000
#define PControlWord_604000 P604000_ControlWord
#define P604000 P604000_ControlWord
#define P0x60400x00 P604000_ControlWord
// The uppercase versions are deprecated
#define P604000_CONTROLWORD P604000_ControlWord
#define PCONTROLWORD_604000 P604000_ControlWord
// [6041,00] Unsigned16
#define P604100_StatusWord 0x00000004
#define PStatusWord_604100 P604100_StatusWord
#define P604100 P604100_StatusWord
#define P0x60410x00 P604100_StatusWord
// The uppercase versions are deprecated
#define P604100_STATUSWORD P604100_StatusWord
#define PSTATUSWORD_604100 P604100_StatusWord
// [6042,00] Unsigned8
#define P604200_ValveState 0x00000006
#define PValveState_604200 P604200_ValveState
#define P604200 P604200_ValveState
#define P0x60420x00 P604200_ValveState
// The uppercase versions are deprecated
#define P604200_VALVESTATE P604200_ValveState
#define PVALVESTATE_604200 P604200_ValveState
// [1001,00] Unsigned8
#define P100100_Error_Register 0x00000008
#define PError_Register_100100 P100100_Error_Register
#define P100100 P100100_Error_Register
#define P0x10010x00 P100100_Error_Register
// The uppercase versions are deprecated
#define P100100_ERROR_REGISTER P100100_Error_Register
#define PERROR_REGISTER_100100 P100100_Error_Register
// [1006,00] Unsigned32
#define P100600_Communication_Cycle_Period 0x0000000C
#define PCommunication_Cycle_Period_100600 P100600_Communication_Cycle_Period
#define P100600 P100600_Communication_Cycle_Period
#define P0x10060x00 P100600_Communication_Cycle_Period
// The uppercase versions are deprecated
#define P100600_COMMUNICATION_CYCLE_PERIOD P100600_Communication_Cycle_Period
#define PCOMMUNICATION_CYCLE_PERIOD_100600 P100600_Communication_Cycle_Period
// [1007,00] Unsigned32
#define P100700_Synchronous_Window_Length 0x00000010
#define PSynchronous_Window_Length_100700 P100700_Synchronous_Window_Length
#define P100700 P100700_Synchronous_Window_Length
#define P0x10070x00 P100700_Synchronous_Window_Length
// The uppercase versions are deprecated
#define P100700_SYNCHRONOUS_WINDOW_LENGTH P100700_Synchronous_Window_Length
#define PSYNCHRONOUS_WINDOW_LENGTH_100700 P100700_Synchronous_Window_Length
// [1008,00] VisibleString
#define P100800_Manufacturer_Device_Name 0x00000014
#define PManufacturer_Device_Name_100800 P100800_Manufacturer_Device_Name
#define P100800 P100800_Manufacturer_Device_Name
#define P0x10080x00 P100800_Manufacturer_Device_Name
// The uppercase versions are deprecated
#define P100800_MANUFACTURER_DEVICE_NAME P100800_Manufacturer_Device_Name
#define PMANUFACTURER_DEVICE_NAME_100800 P100800_Manufacturer_Device_Name
// [1009,00] VisibleString
#define P100900_Manufacturer_Hardware_Version 0x00000020
#define PManufacturer_Hardware_Version_100900 P100900_Manufacturer_Hardware_Version
#define P100900 P100900_Manufacturer_Hardware_Version
#define P0x10090x00 P100900_Manufacturer_Hardware_Version
// The uppercase versions are deprecated
#define P100900_MANUFACTURER_HARDWARE_VERSION P100900_Manufacturer_Hardware_Version
#define PMANUFACTURER_HARDWARE_VERSION_100900 P100900_Manufacturer_Hardware_Version
// [100A,00] VisibleString
#define P100A00_Manufacturer_Software_Version 0x00000023
#define PManufacturer_Software_Version_100A00 P100A00_Manufacturer_Software_Version
#define P100A00 P100A00_Manufacturer_Software_Version
#define P0x100A0x00 P100A00_Manufacturer_Software_Version
// The uppercase versions are deprecated
#define P100A00_MANUFACTURER_SOFTWARE_VERSION P100A00_Manufacturer_Software_Version
#define PMANUFACTURER_SOFTWARE_VERSION_100A00 P100A00_Manufacturer_Software_Version
// [1018,01] Unsigned32
#define P101801_Vendor_ID 0x00000026
#define PVendor_ID_101801 P101801_Vendor_ID
#define P101801 P101801_Vendor_ID
#define P0x10180x01 P101801_Vendor_ID
// The uppercase versions are deprecated
#define P101801_VENDOR_ID P101801_Vendor_ID
#define PVENDOR_ID_101801 P101801_Vendor_ID
// [1018,02] Unsigned32
#define P101802_Product_Code 0x0000002A
#define PProduct_Code_101802 P101802_Product_Code
#define P101802 P101802_Product_Code
#define P0x10180x02 P101802_Product_Code
// The uppercase versions are deprecated
#define P101802_PRODUCT_CODE P101802_Product_Code
#define PPRODUCT_CODE_101802 P101802_Product_Code
// [1018,03] Unsigned32
#define P101803_Revision_Number 0x0000002E
#define PRevision_Number_101803 P101803_Revision_Number
#define P101803 P101803_Revision_Number
#define P0x10180x03 P101803_Revision_Number
// The uppercase versions are deprecated
#define P101803_REVISION_NUMBER P101803_Revision_Number
#define PREVISION_NUMBER_101803 P101803_Revision_Number
// [1018,04] Unsigned32
#define P101804_Serial_Number 0x00000032
#define PSerial_Number_101804 P101804_Serial_Number
#define P101804 P101804_Serial_Number
#define P0x10180x04 P101804_Serial_Number
// The uppercase versions are deprecated
#define P101804_SERIAL_NUMBER P101804_Serial_Number
#define PSERIAL_NUMBER_101804 P101804_Serial_Number
// [1020,01] Unsigned32
#define P102001_Configuration_Date 0x00000036
#define PConfiguration_Date_102001 P102001_Configuration_Date
#define P102001 P102001_Configuration_Date
#define P0x10200x01 P102001_Configuration_Date
// The uppercase versions are deprecated
#define P102001_CONFIGURATION_DATE P102001_Configuration_Date
#define PCONFIGURATION_DATE_102001 P102001_Configuration_Date
// [1020,02] Unsigned32
#define P102002_Configuration_Time 0x0000003A
#define PConfiguration_Time_102002 P102002_Configuration_Time
#define P102002 P102002_Configuration_Time
#define P0x10200x02 P102002_Configuration_Time
// The uppercase versions are deprecated
#define P102002_CONFIGURATION_TIME P102002_Configuration_Time
#define PCONFIGURATION_TIME_102002 P102002_Configuration_Time
// [2000,00] Unsigned8
#define P200000_LEDControl 0x0000003E
#define PLEDControl_200000 P200000_LEDControl
#define P200000 P200000_LEDControl
#define P0x20000x00 P200000_LEDControl
// The uppercase versions are deprecated
#define P200000_LEDCONTROL P200000_LEDControl
#define PLEDCONTROL_200000 P200000_LEDControl
// [2100,00] Unsigned8
#define P210000_FailSafePosition 0x0000003F
#define PFailSafePosition_210000 P210000_FailSafePosition
#define P210000 P210000_FailSafePosition
#define P0x21000x00 P210000_FailSafePosition
// The uppercase versions are deprecated
#define P210000_FAILSAFEPOSITION P210000_FailSafePosition
#define PFAILSAFEPOSITION_210000 P210000_FailSafePosition
// [2101,00] Boolean
#define P210100_ManaualOverride 0x00000040
#define PManaualOverride_210100 P210100_ManaualOverride
#define P210100 P210100_ManaualOverride
#define P0x21010x00 P210100_ManaualOverride
// The uppercase versions are deprecated
#define P210100_MANAUALOVERRIDE P210100_ManaualOverride
#define PMANAUALOVERRIDE_210100 P210100_ManaualOverride
// [2300,00] Unsigned16
#define P230000_MotionTimeout 0x00000041
#define PMotionTimeout_230000 P230000_MotionTimeout
#define P230000 P230000_MotionTimeout
#define P0x23000x00 P230000_MotionTimeout
// The uppercase versions are deprecated
#define P230000_MOTIONTIMEOUT P230000_MotionTimeout
#define PMOTIONTIMEOUT_230000 P230000_MotionTimeout

// last byte used in process image
#define PIMGEND 0x00000042

// sizes for entries in the process image in bytes
#define SIZEOF_6040_00_CONTROLWORD 2
#define SIZEOF_6041_00_STATUSWORD 2
#define SIZEOF_6042_00_VALVESTATE 1
#define SIZEOF_1001_00_ERROR_REGISTER 1
#define SIZEOF_1006_00_COMMUNICATION_CYCLE_PERIOD 4
#define SIZEOF_1007_00_SYNCHRONOUS_WINDOW_LENGTH 4
#define SIZEOF_1008_00_MANUFACTURER_DEVICE_NAME 12
#define SIZEOF_1009_00_MANUFACTURER_HARDWARE_VERSION 3
#define SIZEOF_100A_00_MANUFACTURER_SOFTWARE_VERSION 3
#define SIZEOF_1018_01_VENDOR_ID 4
#define SIZEOF_1018_02_PRODUCT_CODE 4
#define SIZEOF_1018_03_REVISION_NUMBER 4
#define SIZEOF_1018_04_SERIAL_NUMBER 4
#define SIZEOF_1020_01_CONFIGURATION_DATE 4
#define SIZEOF_1020_02_CONFIGURATION_TIME 4
#define SIZEOF_2000_00_LEDCONTROL 1
#define SIZEOF_2100_00_FAILSAFEPOSITION 1
#define SIZEOF_2101_00_MANAUALOVERRIDE 1
#define SIZEOF_2300_00_MOTIONTIMEOUT 2

// default values for process image
#define PIMGDEFAULTS { \
/*[6040,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[6041,00]*/        0x00, 0x00, \
/*[6042,00]*/        0x01, \
/* padding */        0x00, \
/*[1001,00]*/        0x00, \
/* padding */        0x00, 0x00, 0x00, \
/*[1006,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1007,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x56, 0x61, 0x6C, 0x76, 0x65, 0x20, 0x4D, 0x6F, 0x64, 0x75, \
                     0x6C, 0x65, \
/*[1009,00]*/        0x31, 0x2E, 0x30, \
/*[100A,00]*/        0x31, 0x2E, 0x30, \
/*[1018,01]*/        0x23, 0x01, 0x00, 0x00, \
/*[1018,02]*/        0x05, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x01, 0x00, 0x01, 0x00, \
/*[1018,04]*/        0x44, 0x34, 0x12, 0x00, \
/*[1020,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[2100,00]*/        0x00, \
/*[2101,00]*/        0x00, \
/*[2300,00]*/        0x0A, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGDEFAULTS 

// minimum values for process image
#define PIMGMINS { \
/*[6040,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[6041,00]*/        0x00, 0x00, \
/*[6042,00]*/        0x00, \
/* padding */        0x00, \
/*[1001,00]*/        0x00, \
/* padding */        0x00, 0x00, 0x00, \
/*[1006,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1007,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1009,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[100A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[2100,00]*/        0x00, \
/*[2101,00]*/        0x00, \
/*[2300,00]*/        0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMINS 

// maximum values for process image
#define PIMGMAXS { \
/*[6040,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[6041,00]*/        0x00, 0x00, \
/*[6042,00]*/        0x00, \
/* padding */        0x00, \
/*[1001,00]*/        0x00, \
/* padding */        0x00, 0x00, 0x00, \
/*[1006,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1007,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1009,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[100A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1018,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1020,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[2000,00]*/        0x00, \
/*[2100,00]*/        0x00, \
/*[2101,00]*/        0x00, \
/*[2300,00]*/        0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMAXS 

// Example usage: PIMG_OFFSET(0x1000, 0x00)
#define PIMG_OFFSET(index, subindex) P##index##subindex

#endif // _PIMGH_
