/**
 ******************************************************************************
 * @file    sensor_control.c
 * @brief   Sensor Control Bridge — CiA 404 State Machine + process image
 * @note    Full CiA 404 implementation:
 *          - NMT-gated state machine: DISABLED → WARMING_UP → RUNNING → FAULT
 *          - StatusWord (0x6041) generation from sensor states + NMT
 *          - ControlWord (0x6040) rising-edge processing (fault reset)
 *          - TPDO transmission is the STACK's change-of-state scan (any
 *            mapped PI byte changes → send after the inhibit time; event
 *            timer guarantees a frame). No app-level delta thresholds:
 *            0x2400-0x2402 were removed 2026-09-30 — they never reduced
 *            traffic (the stack sends on every PI change regardless) and
 *            only produced stale duplicate frames. Cadence knobs are the
 *            standard 0x1800/0x1801 inhibit + event timers.
 *          - ErrorRegister (0x1001) written to BOTH homes (process image for
 *            TPDO2, gMCOConfig for SDO + EMCY) and EMCYs on sensor loss /
 *            FAULT / reset (see the ERREG_* / EMCY_* defines below)
 *
 *          "Dumb module" (docs/PHTEMP_REFACTOR_PLAN.md): raw electrode mV +
 *          temperature + health only. No pH/Nernst/calibration on-module —
 *          the MIK owns all of that and its persistence.
 *
 *          SDO-readable objects:
 *            0x6003 pHMillivolts       (UINT16, mV × 10 — primary electrode output)
 *            0x6001 pHSignalQuality    (UINT8, 0-100%)
 *            0x6002 pHSensorStatus     (UINT8, pH_State_t)
 *            0x6010 Temperature        (INT16, °C × 10, raw)
 *            0x6011 TempSignalQuality  (UINT8, 0-100%)
 *            0x6012 TempSensorStatus   (UINT8, Temp_State_t)
 *            0x6040 ControlWord        (UINT16, writable — fault reset)
 *            0x6041 StatusWord         (UINT16, read-only)
 *            0x2300 SensorStatus       (UINT8, bitfield)
 *
 * @date    2026
 ******************************************************************************
 */

/* Includes ------------------------------------------------------------------*/
#include "sensor_control.h"
#include "temp_sensor.h"
#include "ph_sensor.h"
#include "led_control.h"
#include "mco_events.h"
#include "procimg_api.h"
#include "log.h"
#include "main.h"       /* DQ_Pin, DQ_GPIO_Port */
#include "mcop_inc.h"
#include <string.h>

/* External timer handles for tri-LED PWM control (defined in main.c) */
extern TIM_HandleTypeDef htim2; /* Red LED   - TIM2 CH1 */
extern TIM_HandleTypeDef htim3; /* Blue LED  - TIM3 CH2 */
extern TIM_HandleTypeDef htim4; /* Green LED - TIM4 CH1 */

/* External I2C handle (defined in main.c, generated by CubeMX) */
extern I2C_HandleTypeDef hi2c1;

/* Private defines -----------------------------------------------------------*/
/* NMTSTATE_OP (5) and NMTSTATE_PREOP (127) are provided by mco.h via mcop_inc.h */

/* Private macros ------------------------------------------------------------*/

/**
 * @brief  Check if temperature sensor is actively working (not idle/error)
 * @note   DS18B20 cycles: IDLE→CONVERTING(750ms)→READING→READY→IDLE→...
 *         During CONVERTING the sensor is perfectly healthy, just waiting.
 *         For status reporting we treat any non-error, non-idle state as "ready"
 *         so that StatusWord/SensorStatus don't flap every conversion cycle.
 *         READY itself is visible for only ONE main-loop iteration per cycle
 *         (Temp_Process() restarts a conversion on the next call), so never
 *         gate on Temp_GetState() == TEMP_STATE_READY at a single instant —
 *         the warm-up gate latches it instead (temp_seen_ready).
 */
#define TEMP_IS_ACTIVE() \
	(sensor_ctrl.temp_initialized && \
	 Temp_GetState() != TEMP_STATE_ERROR && \
	 Temp_GetState() != TEMP_STATE_IDLE)

/** A measurement channel is faulted if its driver is in ERROR *or* it never
 *  came up at init (probe absent at boot). Init failure used to be silent
 *  because every fault check was gated on the initialized flag. */
#define TEMP_IS_FAULTED() \
	(!sensor_ctrl.temp_initialized || Temp_GetState() == TEMP_STATE_ERROR)
#define PH_IS_FAULTED() \
	(!sensor_ctrl.ph_initialized || pH_GetState() == PH_STATE_ERROR)

/* ── ErrorRegister (0x1001) bits this application owns — CiA 301 layout ──
 * bit 0 generic:           set whenever any other bit is set (spec requirement)
 * bit 5 profile-specific:  a measurement channel (pH ADC / temp probe) is faulted
 * Bits 1-4 (current/voltage/temperature/communication) are deliberately NOT
 * used: bit 3 would mean the *device* overheats, bit 4 means CAN, not I2C/1-Wire.
 * The stack owns bit 0 too (sets it on its own EMCYs); we only add/remove our
 * contribution edge-wise so a stack-set bit 0 is not stomped every loop. */
#define ERREG_GENERIC          0x01u
#define ERREG_PROFILE          0x20u
#define ERREG_APP_BITS         (ERREG_GENERIC | ERREG_PROFILE)

/* ── EMCY codes (CiA 301 generic ranges; no pump/motor codes) ──
 * 0x5000 device hardware:   a sensor went into ERROR / was absent at init.
 *                           MSEF[0] = EMCY_SENSOR_*, MSEF[1] = driver state.
 * 0xFF00 device specific:   application FAULT entered. MSEF[0] = FAULT_CAUSE_*,
 *                           MSEF[1] = pH state, MSEF[2] = temp state.
 * 0x0000 (EMCY_NO_ERROR):   ControlWord bit-7 fault reset. */
#define EMCY_CODE_DEVICE_HW        0x5000u
#define EMCY_CODE_DEVICE_SPECIFIC  0xFF00u
#define EMCY_SENSOR_PH             1u
#define EMCY_SENSOR_TEMP           2u
#define FAULT_CAUSE_NO_SENSOR_READY 1u  /**< warm-up expired, no channel ever READY */
#define FAULT_CAUSE_BOTH_SENSORS    2u  /**< both channels faulted while RUNNING */
#define FAULT_CAUSE_EMERGENCY_STOP  3u  /**< stack fatal error / heartbeat lost */

/** Minimum quality change (%) before updating process image.
 *  Suppresses MCO stack CoS triggering from ADC noise.
 *  No-probe pH quality swings ~73-93% (±10 around center).
 *  15% dead-band covers the full noise envelope so the byte
 *  stays frozen until a genuine signal condition change. */
#define QUALITY_HYSTERESIS  15

/** Same concept for pH — PH_STATE_SAMPLING is normal operation */
#define PH_IS_ACTIVE() \
	(sensor_ctrl.ph_initialized && \
	 pH_GetState() != PH_STATE_ERROR && \
	 pH_GetState() != PH_STATE_IDLE)

/* Private variables ---------------------------------------------------------*/
static struct {
	bool initialized;
	SensorState_t current_state;
	uint32_t last_diag_ms;

	/* Temperature sensor tracking */
	bool temp_initialized;

	/* pH (electrode mV) sensor tracking */
	bool ph_initialized;

	/* CiA 404 state machine */
	uint32_t warmup_start_ms; /**< Timestamp when WARMING_UP entered */
	bool temp_seen_ready; /**< Latched during WARMING_UP: temp reached READY */
	bool ph_seen_ready; /**< Latched during WARMING_UP: pH reached READY */
	uint16_t last_control_word; /**< For rising-edge detection */
	uint16_t last_status_word; /**< Last StatusWord written (diagnostics) */

	/* ErrorRegister / EMCY edge tracking */
	uint8_t last_err_reg; /**< App-owned 0x1001 bits as last applied */
	bool ph_err_reported; /**< 0x5000 EMCY sent for the current pH fault */
	bool temp_err_reported; /**< 0x5000 EMCY sent for the current temp fault */

	/* Quality hysteresis — suppress MCO CoS from ADC noise */
	uint8_t pimg_ph_quality; /**< Last pH quality written to pimg   */
	uint8_t pimg_temp_quality; /**< Last temp quality written to pimg */
} sensor_ctrl;

/* Private function prototypes -----------------------------------------------*/
static void SensorControl_HandleMCOEvent(const MCO_Event_t *event);
static void SensorControl_UpdateProcessImage(void);
static uint16_t SensorControl_GenerateStatusWord(void);
static void SensorControl_ProcessControlWord(uint16_t control_word);
static void SensorControl_UpdateErrorRegister(void);
static void SensorControl_ReportSensorErrors(void);
static void SensorControl_EnterFault(uint8_t cause);
static void SensorControl_ClearFault(void);

/* Exported functions --------------------------------------------------------*/

bool SensorControl_Init(void) {
	memset(&sensor_ctrl, 0, sizeof(sensor_ctrl));
	sensor_ctrl.current_state = SENSOR_STATE_DISABLED;
	sensor_ctrl.initialized = true;
	sensor_ctrl.temp_initialized = false;
	sensor_ctrl.ph_initialized = false;
	sensor_ctrl.last_control_word = 0;
	sensor_ctrl.last_status_word = 0;

	/* Initialize DS18B20 temperature sensor on the DQ pin (PA6, see main.h) */
	if (Temp_Init(DQ_GPIO_Port, DQ_Pin) == HAL_OK) {
		sensor_ctrl.temp_initialized = true;
		DBG_PRINT(SENSOR, "Init: DS18B20 OK");
	} else {
		DBG_ERROR(SENSOR, "Init: DS18B20 FAILED (no presence)");
	}

	/* Initialize MCP3221 pH sensor on I2C1 */
	if (pH_Init(&hi2c1) == HAL_OK) {
		sensor_ctrl.ph_initialized = true;
		DBG_PRINT(SENSOR, "Init: MCP3221 pH OK");
	} else {
		DBG_ERROR(SENSOR, "Init: MCP3221 pH FAILED (not responding)");
	}

	/* Initialize tri-LED PWM control (starts TIM2/TIM3/TIM4 PWM outputs).
	 * This enables both the MCO stack's CiA 303 LED patterns (green/red)
	 * and the application-level LED control via OD 0x2000. */
	if (!LEDControl_Init(&htim2, TIM_CHANNEL_1, &htim3, TIM_CHANNEL_2, &htim4,
			TIM_CHANNEL_1)) {
		DBG_ERROR(SENSOR, "Init: LEDControl FAILED");
	} else {
		DBG_PRINT(SENSOR, "Init: LEDControl OK");
	}

	DBG_PRINT(SENSOR, "SensorControl_Init complete (temp=%s, pH=%s)",
			sensor_ctrl.temp_initialized ? "OK" : "FAIL",
			sensor_ctrl.ph_initialized ? "OK" : "FAIL");
	return true;
}

void SensorControl_Process(void) {
	if (!sensor_ctrl.initialized) {
		return;
	}

	/* ── Always tick sensor drivers (they need processing regardless) ── */

	/* Temperature sensor: report raw °C×10 (MIK owns any per-probe trim) */
	if (sensor_ctrl.temp_initialized) {
		Temp_Process();
	}

	/* Electrode ADC: acquire raw millivolts (MIK owns pH/Nernst/cal) */
	if (sensor_ctrl.ph_initialized) {
		pH_Process();
	}

	/* ── NMT gate: if not OPERATIONAL, force DISABLED ──────────────── */
	if (MY_NMT_STATE != NMTSTATE_OP) {
		if (sensor_ctrl.current_state != SENSOR_STATE_DISABLED) {
			DBG_STATE(SENSOR, "NMT not OP (0x%02X) -> DISABLED", MY_NMT_STATE);
			sensor_ctrl.current_state = SENSOR_STATE_DISABLED;
		}
		/* Still update process image so SDO reads reflect sensor data */
		SensorControl_UpdateProcessImage();
		return;
	}

	/* ── Process ControlWord (rising-edge detection) ───────────────── */
	SensorControl_ProcessControlWord(ProcImg_GetControlWord());

	/* ── CiA 404 State Machine ─────────────────────────────────────── */
	switch (sensor_ctrl.current_state) {

	case SENSOR_STATE_DISABLED:
		/* Transition to WARMING_UP when NMT is Operational */
		sensor_ctrl.warmup_start_ms = HAL_GetTick();
		sensor_ctrl.temp_seen_ready = false;
		sensor_ctrl.ph_seen_ready = false;
		sensor_ctrl.current_state = SENSOR_STATE_WARMING_UP;
		DBG_STATE(SENSOR, "DISABLED -> WARMING_UP (2s warmup)");
		break;

	case SENSOR_STATE_WARMING_UP: {
		/* Latch READY on every iteration. The DS18B20 driver shows READY for a
		 * single loop per ~750 ms cycle, so sampling its state once at the
		 * 2 s mark would miss it and fault a healthy temp-only module. */
		if (sensor_ctrl.temp_initialized
				&& Temp_GetState() == TEMP_STATE_READY) {
			sensor_ctrl.temp_seen_ready = true;
		}
		if (sensor_ctrl.ph_initialized && pH_GetState() == PH_STATE_READY) {
			sensor_ctrl.ph_seen_ready = true;
		}

		uint32_t elapsed = HAL_GetTick() - sensor_ctrl.warmup_start_ms;
		if (elapsed >= WARMUP_TIME_MS) {
			if (sensor_ctrl.temp_seen_ready || sensor_ctrl.ph_seen_ready) {
				sensor_ctrl.current_state = SENSOR_STATE_RUNNING;
				DBG_STATE(SENSOR, "WARMING_UP -> RUNNING (temp=%s pH=%s)",
						sensor_ctrl.temp_seen_ready ? "ready" : "absent",
						sensor_ctrl.ph_seen_ready ? "ready" : "absent");
			} else {
				DBG_ERROR(SENSOR,
						"WARMING_UP -> FAULT (no sensors ready after warmup)");
				SensorControl_EnterFault(FAULT_CAUSE_NO_SENSOR_READY);
			}
		}
		break;
	}

	case SENSOR_STATE_RUNNING:
		/* Measurements reach the bus through the stack's change-of-state scan
		 * on the process image (written below); nothing to trigger here. */

		/* Both channels faulted (in ERROR, or absent since init) → FAULT.
		 * A single faulted channel is reported (SW bit, 0x1001 bit 5, EMCY
		 * 0x5000) but does not fault the module. */
		if (TEMP_IS_FAULTED() && PH_IS_FAULTED()) {
			DBG_ERROR(SENSOR, "RUNNING -> FAULT (both sensors faulted)");
			SensorControl_EnterFault(FAULT_CAUSE_BOTH_SENSORS);
		}
		break;

	case SENSOR_STATE_FAULT:
		/* Wait for ControlWord fault reset (handled in ProcessControlWord) */
		break;
	}

	/* ── Update process image with latest readings + StatusWord ─────── */
	SensorControl_UpdateProcessImage();

	/* ── Process application-level LED control (reads mode from OD 0x2000) ── */
	LEDControl_Process();
}

bool SensorControl_IsOperational(void) {
	return sensor_ctrl.current_state == SENSOR_STATE_RUNNING;
}

void SensorControl_EmergencyStop(void) {
	if (!sensor_ctrl.initialized) {
		return;
	}
	DBG_ERROR(SENSOR, "EmergencyStop called");
	SensorControl_EnterFault(FAULT_CAUSE_EMERGENCY_STOP);
}

void SensorControl_RegisterMCOEvents(void) {
	MCO_Events_Register(SensorControl_HandleMCOEvent);
	DBG_PRINT(SENSOR, "Registered as MCO event listener");
}

void SensorControl_RunDiagnostics(void) {
	if (!sensor_ctrl.initialized) {
		return;
	}

	uint32_t now = HAL_GetTick();
	if (now - sensor_ctrl.last_diag_ms < 5000) {
		return; /* Throttle to every 5 seconds */
	}
	sensor_ctrl.last_diag_ms = now;

	/* Temperature diagnostics */
	int16_t temp = Temp_GetValue();
	uint8_t tq = Temp_GetSignalQuality();
	Temp_State_t ts = Temp_GetState();

	/* Electrode (mV × 10) diagnostics */
	uint16_t mv10 = pH_GetMillivoltsX10();
	uint8_t pq = pH_GetSignalQuality();
	pH_State_t ps = pH_GetState();

	/* StatusWord + error register (both homes should agree) */
	uint16_t sw = sensor_ctrl.last_status_word;

	DBG_PRINT(SENSOR,
			"DIAG: state=%d SW=0x%04X ER=0x%02X | temp=%d.%d C q=%u%% s=%d | mV=%u.%u q=%u%% s=%d",
			sensor_ctrl.current_state, sw, gMCOConfig.error_register, temp / 10,
			(temp >= 0 ? temp : -temp) % 10, tq, ts, mv10 / 10, mv10 % 10, pq,
			ps);
}

SensorState_t SensorControl_GetState(void) {
	return sensor_ctrl.current_state;
}

/* Private functions ---------------------------------------------------------*/

/**
 * @brief  Generate CiA 404 StatusWord from current sensor states
 * @retval 16-bit StatusWord for process image (0x6041)
 */
static uint16_t SensorControl_GenerateStatusWord(void) {
	uint16_t sw = 0;

	/* Bit 0: pH sensor ready (active, not idle/error) */
	if (PH_IS_ACTIVE()) {
		sw |= SW_PH_READY;
	}

	/* Bit 1: Temperature sensor ready (active, not idle/error) */
	if (TEMP_IS_ACTIVE()) {
		sw |= SW_TEMP_READY;
	}

	/* Bit 3: General fault */
	if (sensor_ctrl.current_state == SENSOR_STATE_FAULT) {
		sw |= SW_FAULT;
	}

	/* Bit 4: pH sensor fault (in ERROR, or absent since init) */
	if (PH_IS_FAULTED()) {
		sw |= SW_PH_FAULT;
	}

	/* Bit 5: Temperature sensor fault (in ERROR, or absent since init) */
	if (TEMP_IS_FAULTED()) {
		sw |= SW_TEMP_FAULT;
	}

	/* Bit 6: Warming up */
	if (sensor_ctrl.current_state == SENSOR_STATE_WARMING_UP) {
		sw |= SW_WARMING_UP;
	}

	/* Bit 9: Remote (NMT Operational) */
	if (MY_NMT_STATE == NMTSTATE_OP) {
		sw |= SW_REMOTE;
	}

	return sw;
}

/**
 * @brief  Process ControlWord with rising-edge detection
 * @param  control_word  Current ControlWord read from process image (0x6040)
 * @note   Detects rising edges (0→1 transitions) and dispatches:
 *         - Bit 7: Fault reset → clear errors, state → DISABLED
 *         (Calibration ControlWord bits are gone — the MIK owns calibration.)
 */
static void SensorControl_ProcessControlWord(uint16_t control_word) {
	/* Detect rising edges */
	uint16_t rising = control_word & ~sensor_ctrl.last_control_word;
	sensor_ctrl.last_control_word = control_word;

	if (rising == 0) {
		return; /* No new edges */
	}

	/* Fault reset (bit 7) */
	if (rising & CW_FAULT_RESET) {
		DBG_STATE(SENSOR, "ControlWord: FAULT_RESET");
		sensor_ctrl.current_state = SENSOR_STATE_DISABLED;

		/* Clear sensor errors; a channel that was absent at init gets ONE
		 * re-init attempt here so a probe plugged in later is picked up
		 * without a power cycle. */
		if (sensor_ctrl.temp_initialized) {
			Temp_ClearError();
		} else if (Temp_Init(DQ_GPIO_Port, DQ_Pin) == HAL_OK) {
			sensor_ctrl.temp_initialized = true;
			DBG_PRINT(SENSOR, "FAULT_RESET: DS18B20 now present");
		}
		if (sensor_ctrl.ph_initialized) {
			pH_ClearError();
		} else if (pH_Init(&hi2c1) == HAL_OK) {
			sensor_ctrl.ph_initialized = true;
			DBG_PRINT(SENSOR, "FAULT_RESET: MCP3221 now present");
		}

		/* Clear our 0x1001 bits in both homes + EMCY 0x0000 (error reset).
		 * If a channel is still faulted, the next UpdateProcessImage() re-sets
		 * the bit and re-announces it with a fresh 0x5000 EMCY. */
		SensorControl_ClearFault();
	}
}

/**
 * @brief  Write current sensor readings + status into MCO process image
 * @note   Called every SensorControl_Process() iteration.
 *         The MCO stack serves these values to SDO reads and TPDO mappings.
 */
static void SensorControl_UpdateProcessImage(void) {
	/* ── Temperature objects ──────────────────────────────────── */
	ProcImg_SetTemperature(Temp_GetValue());
	ProcImg_SetTempSensorStatus((uint8_t) Temp_GetState());

	/* Temp quality: only update process image if change > hysteresis */
	{
		uint8_t tq = Temp_GetSignalQuality();
		uint8_t diff =
				(tq >= sensor_ctrl.pimg_temp_quality) ?
						(tq - sensor_ctrl.pimg_temp_quality) :
						(sensor_ctrl.pimg_temp_quality - tq);
		if (diff >= QUALITY_HYSTERESIS) {
			sensor_ctrl.pimg_temp_quality = tq;
			ProcImg_SetTempSignalQuality(tq);
		}
	}

	/* ── Electrode (mV × 10) objects ──────────────────────────── */
	ProcImg_SetpHMillivolts(pH_GetMillivoltsX10());
	ProcImg_SetpHSensorStatus((uint8_t) pH_GetState());

	/* pH quality: only update process image if change > hysteresis */
	{
		uint8_t pq = pH_GetSignalQuality();
		uint8_t diff =
				(pq >= sensor_ctrl.pimg_ph_quality) ?
						(pq - sensor_ctrl.pimg_ph_quality) :
						(sensor_ctrl.pimg_ph_quality - pq);
		if (diff >= QUALITY_HYSTERESIS) {
			sensor_ctrl.pimg_ph_quality = pq;
			ProcImg_SetpHSignalQuality(pq);
		}
	}

	/* ── StatusWord (0x6041) ──────────────────────────────────── */
	uint16_t sw = SensorControl_GenerateStatusWord();
	ProcImg_SetStatusWord(sw);
	sensor_ctrl.last_status_word = sw;

	/* ── SensorStatus bitfield (0x2300) ──────────────────────── */
	uint8_t sensor_status = 0;
	if (PH_IS_ACTIVE()) {
		sensor_status |= 0x01; /* bit 0: electrode OK */
	}
	if (TEMP_IS_ACTIVE()) {
		sensor_status |= 0x02; /* bit 1: temp OK */
	}
	if (sensor_ctrl.current_state == SENSOR_STATE_FAULT) {
		sensor_status |= 0x08; /* bit 3: fault */
	}
	ProcImg_SetSensorStatus(sensor_status);

	/* ── ErrorRegister (0x1001), both homes, then sensor-loss EMCYs ── */
	SensorControl_UpdateErrorRegister();
	SensorControl_ReportSensorErrors();
}

/**
 * @brief  Compute the app-owned 0x1001 bits and apply them to BOTH homes.
 * @note   The stack serves SDO reads of 0x1001 and the EMCY error-register
 *         byte from gMCOConfig.error_register (mco.c); TPDO2 carries the
 *         process-image copy. Writing only the PI (the old code) made an SDO
 *         read say 0x00 while TPDO2 showed the fault — the same dual-source
 *         bug the pump's Phase 0a bench caught. Edge-wise set/clear so a
 *         stack-set generic bit (its own EMCYs) is not stomped each loop; the
 *         PI copy mirrors the merged register so both homes always agree.
 */
static void SensorControl_UpdateErrorRegister(void) {
	uint8_t err = 0;
	if (PH_IS_FAULTED() || TEMP_IS_FAULTED()) {
		err |= ERREG_PROFILE;
	}
	if (sensor_ctrl.current_state == SENSOR_STATE_FAULT || err != 0) {
		err |= ERREG_GENERIC; /* CiA 301: bit 0 set if any other bit is set */
	}

	uint8_t set_bits = err & (uint8_t) ~sensor_ctrl.last_err_reg;
	uint8_t clr_bits = sensor_ctrl.last_err_reg & (uint8_t) ~err;
	if (set_bits) {
		gMCOConfig.error_register |= set_bits;
	}
	if (clr_bits) {
		gMCOConfig.error_register &= (uint8_t) ~clr_bits;
	}
	sensor_ctrl.last_err_reg = err;

	ProcImg_SetErrorRegister(gMCOConfig.error_register);
}

/**
 * @brief  EMCY 0x5000 (device hardware) once per sensor fault episode.
 * @note   Sensor errors only clear through the ControlWord fault-reset path,
 *         which sends EMCY 0x0000 and re-arms these flags — so a still-faulted
 *         channel is re-announced after a reset. Called after
 *         SensorControl_UpdateErrorRegister() so the EMCY frame carries the
 *         updated register byte.
 */
static void SensorControl_ReportSensorErrors(void) {
	bool ph_faulted = PH_IS_FAULTED();
	if (ph_faulted && !sensor_ctrl.ph_err_reported) {
		sensor_ctrl.ph_err_reported = true;
		DBG_ERROR(SENSOR, "EMCY 0x5000: pH ADC faulted (state=%d)",
				pH_GetState());
		(void) MCOP_PushEMCY(EMCY_CODE_DEVICE_HW, EMCY_SENSOR_PH,
				(uint8_t) pH_GetState(), 0, 0, 0);
	} else if (!ph_faulted) {
		sensor_ctrl.ph_err_reported = false;
	}

	bool temp_faulted = TEMP_IS_FAULTED();
	if (temp_faulted && !sensor_ctrl.temp_err_reported) {
		sensor_ctrl.temp_err_reported = true;
		DBG_ERROR(SENSOR, "EMCY 0x5000: temp probe faulted (state=%d)",
				Temp_GetState());
		(void) MCOP_PushEMCY(EMCY_CODE_DEVICE_HW, EMCY_SENSOR_TEMP,
				(uint8_t) Temp_GetState(), 0, 0, 0);
	} else if (!temp_faulted) {
		sensor_ctrl.temp_err_reported = false;
	}
}

/**
 * @brief  Enter the application FAULT state with an EMCY 0xFF00 (cause-coded).
 * @param  cause  FAULT_CAUSE_* (MSEF[0]); MSEF[1]/[2] = pH / temp driver state
 * @note   Idempotent: re-entering while already in FAULT sends nothing.
 *         Error register is updated first so the EMCY carries bit 0 set.
 */
static void SensorControl_EnterFault(uint8_t cause) {
	if (sensor_ctrl.current_state == SENSOR_STATE_FAULT) {
		return;
	}
	sensor_ctrl.current_state = SENSOR_STATE_FAULT;
	SensorControl_UpdateErrorRegister();
	DBG_ERROR(SENSOR, "EMCY 0xFF00: FAULT cause=%u", cause);
	(void) MCOP_PushEMCY(EMCY_CODE_DEVICE_SPECIFIC, cause,
			(uint8_t) pH_GetState(), (uint8_t) Temp_GetState(), 0, 0);
}

/**
 * @brief  ControlWord fault reset: clear our 0x1001 bits in both homes, re-arm
 *         the sensor EMCY edges, send EMCY 0x0000 if there was anything to clear.
 */
static void SensorControl_ClearFault(void) {
	bool had_error = (sensor_ctrl.last_err_reg != 0);

	gMCOConfig.error_register &= (uint8_t) ~ERREG_APP_BITS;
	sensor_ctrl.last_err_reg = 0;
	ProcImg_SetErrorRegister(gMCOConfig.error_register);
	sensor_ctrl.ph_err_reported = false;
	sensor_ctrl.temp_err_reported = false;

	if (had_error) {
		DBG_STATE(SENSOR, "EMCY 0x0000: error reset");
		(void) MCOP_PushEMCY(EMCY_NO_ERROR, 0, 0, 0, 0, 0);
	}
}

/**
 * @brief Handle MCO events (same pattern as pump's MotorControl)
 */
static void SensorControl_HandleMCOEvent(const MCO_Event_t *event) {
	switch (event->type) {
	case MCO_EVENT_FATAL_ERROR:
		DBG_ERROR(SENSOR, "MCO fatal error: code=%u", event->error_code);
		SensorControl_EmergencyStop();
		break;

	case MCO_EVENT_COMM_RESET:
		if (event->init_result) {
			DBG_PRINT(SENSOR,
					"COMM_RESET: stack init OK, initializing sensors");
			if (!SensorControl_Init()) {
				DBG_ERROR(SENSOR, "SensorControl_Init failed");
			}
		} else {
			DBG_ERROR(SENSOR, "COMM_RESET: stack init FAILED");
		}
		break;

	case MCO_EVENT_NMT_CHANGE:
		DBG_STATE(SENSOR, "NMT change: state=0x%02X", event->nmt_state);
		/* NMT gate in Process() handles state transitions.
		 * No explicit Reset here — avoids clearing state prematurely
		 * when the NMT gate will handle it next cycle. */
		break;

	case MCO_EVENT_HEARTBEAT_LOST:
		DBG_ERROR(SENSOR, "Heartbeat lost: node=%u", event->node_id);
		SensorControl_EmergencyStop();
		break;
	}
}
