/**
 ******************************************************************************
 * @file    sensor_control.c
 * @brief   Sensor Control Bridge — CiA 404 State Machine + TPDO Triggering
 * @note    Full CiA 404 implementation:
 *          - NMT-gated state machine: DISABLED → WARMING_UP → RUNNING → FAULT
 *          - StatusWord (0x6041) generation from sensor states + NMT
 *          - ControlWord (0x6040) rising-edge processing (cal, fault reset)
 *          - Delta-threshold TPDO triggering for TPDO1 (measurements)
 *            and TPDO2 (status)
 *
 *          SDO-readable objects:
 *            0x6000 pHValue            (UINT16, pH × 100)
 *            0x6001 pHSignalQuality    (UINT8, 0-100%)
 *            0x6002 pHSensorStatus     (UINT8, pH_State_t)
 *            0x6010 Temperature        (INT16, °C × 10)
 *            0x6011 TempSignalQuality  (UINT8, 0-100%)
 *            0x6012 TempSensorStatus   (UINT8, Temp_State_t)
 *            0x6040 ControlWord        (UINT16, writable)
 *            0x6041 StatusWord         (UINT16, read-only)
 *            0x2200 CalibrationCommand (UINT8, WO from master)
 *            0x2201 CalibrationStatus  (UINT8, RO)
 *            0x2210 TempOffset         (INT16, °C × 10, writable)
 *            0x2300 SensorStatus       (UINT8, bitfield)
 *            0x2400 pHDeltaThreshold   (UINT16, pH × 100)
 *            0x2401 TempDeltaThreshold (INT16, °C × 10)
 *            0x2402 StatusDeltaThreshold (UINT8, bit-change)
 *
 * @date    2026
 ******************************************************************************
 */

/* Includes ------------------------------------------------------------------*/
#include "sensor_control.h"
#include "temp_sensor.h"
#include "ph_sensor.h"
#include "led_control.h"
#include "mco_events.h"
#include "procimg_api.h"
#include "log.h"
#include "main.h"       /* DQ_Pin, DQ_GPIO_Port */
#include "mcop_inc.h"
#include <string.h>

/* External timer handles for tri-LED PWM control (defined in main.c) */
extern TIM_HandleTypeDef htim2; /* Red LED   - TIM2 CH1 */
extern TIM_HandleTypeDef htim3; /* Blue LED  - TIM3 CH2 */
extern TIM_HandleTypeDef htim4; /* Green LED - TIM4 CH1 */

/* External I2C handle (defined in main.c, generated by CubeMX) */
extern I2C_HandleTypeDef hi2c1;

/* Private defines -----------------------------------------------------------*/
/* NMTSTATE_OP (5) and NMTSTATE_PREOP (127) are provided by mco.h via mcop_inc.h */

/* Private macros ------------------------------------------------------------*/

/**
 * @brief  Check if temperature sensor is actively working (not idle/error)
 * @note   DS18B20 cycles: IDLE→CONVERTING(750ms)→READING→READY→IDLE→...
 *         During CONVERTING the sensor is perfectly healthy, just waiting.
 *         For status reporting we treat any non-error, non-idle state as "ready"
 *         so that StatusWord/SensorStatus don't flap every conversion cycle.
 *         Use Temp_GetState() == TEMP_STATE_READY only when you need a valid
 *         reading available RIGHT NOW (e.g., warmup gate, feeding pH compensation).
 */
#define TEMP_IS_ACTIVE() \
	(sensor_ctrl.temp_initialized && \
	 Temp_GetState() != TEMP_STATE_ERROR && \
	 Temp_GetState() != TEMP_STATE_IDLE)

/** Minimum quality change (%) before updating process image.
 *  Suppresses MCO stack CoS triggering from ADC noise.
 *  No-probe pH quality swings ~73-93% (±10 around center).
 *  15% dead-band covers the full noise envelope so the byte
 *  stays frozen until a genuine signal condition change. */
#define QUALITY_HYSTERESIS  15

/** Same concept for pH — PH_STATE_SAMPLING is normal operation */
#define PH_IS_ACTIVE() \
	(sensor_ctrl.ph_initialized && \
	 pH_GetState() != PH_STATE_ERROR && \
	 pH_GetState() != PH_STATE_IDLE)

/* Private variables ---------------------------------------------------------*/
static struct {
	bool initialized;
	SensorState_t current_state;
	uint32_t last_diag_ms;

	/* Temperature sensor tracking */
	bool temp_initialized;
	int16_t last_applied_offset; /**< Track offset to detect SDO writes */

	/* pH sensor tracking */
	bool ph_initialized;
	uint8_t last_cal_command; /**< Track cal command to detect SDO writes */

	/* CiA 404 state machine */
	uint32_t warmup_start_ms; /**< Timestamp when WARMING_UP entered */
	uint16_t last_control_word; /**< For rising-edge detection */
	uint16_t last_status_word; /**< For delta trigger comparison */

	/* Delta-threshold TPDO tracking */
	uint16_t last_tpdo_ph; /**< Last pH value sent via TPDO1 */
	int16_t last_tpdo_temp; /**< Last temp value sent via TPDO1 */
	uint8_t last_tpdo_status; /**< Last SensorStatus sent via TPDO2 */

	/* Quality hysteresis — suppress MCO CoS from ADC noise */
	uint8_t pimg_ph_quality; /**< Last pH quality written to pimg   */
	uint8_t pimg_temp_quality; /**< Last temp quality written to pimg */
} sensor_ctrl;

/* Private function prototypes -----------------------------------------------*/
static void SensorControl_HandleMCOEvent(const MCO_Event_t *event);
static void SensorControl_UpdateProcessImage(void);
static void SensorControl_CheckCalibrationCommand(void);
static uint16_t SensorControl_GenerateStatusWord(void);
static void SensorControl_ProcessControlWord(uint16_t control_word);
static void SensorControl_CheckDeltaTrigger(void);

/* Exported functions --------------------------------------------------------*/

bool SensorControl_Init(void) {
	memset(&sensor_ctrl, 0, sizeof(sensor_ctrl));
	sensor_ctrl.current_state = SENSOR_STATE_DISABLED;
	sensor_ctrl.initialized = true;
	sensor_ctrl.temp_initialized = false;
	sensor_ctrl.ph_initialized = false;
	sensor_ctrl.last_applied_offset = 0;
	sensor_ctrl.last_cal_command = PH_CAL_CMD_NONE;
	sensor_ctrl.last_control_word = 0;
	sensor_ctrl.last_status_word = 0;
	sensor_ctrl.last_tpdo_ph = 0;
	sensor_ctrl.last_tpdo_temp = 0;
	sensor_ctrl.last_tpdo_status = 0;

	/* Initialize DS18B20 temperature sensor on DQ pin (PB0) */
	if (Temp_Init(DQ_GPIO_Port, DQ_Pin) == HAL_OK) {
		sensor_ctrl.temp_initialized = true;
		DBG_PRINT(SENSOR, "Init: DS18B20 OK");
	} else {
		DBG_ERROR(SENSOR, "Init: DS18B20 FAILED (no presence)");
	}

	/* Initialize MCP3221 pH sensor on I2C1 */
	if (pH_Init(&hi2c1) == HAL_OK) {
		sensor_ctrl.ph_initialized = true;
		DBG_PRINT(SENSOR, "Init: MCP3221 pH OK");
	} else {
		DBG_ERROR(SENSOR, "Init: MCP3221 pH FAILED (not responding)");
	}

	/* Initialize tri-LED PWM control (starts TIM2/TIM3/TIM4 PWM outputs).
	 * This enables both the MCO stack's CiA 303 LED patterns (green/red)
	 * and the application-level LED control via OD 0x2000. */
	if (!LEDControl_Init(&htim2, TIM_CHANNEL_1, &htim3, TIM_CHANNEL_2, &htim4,
			TIM_CHANNEL_1)) {
		DBG_ERROR(SENSOR, "Init: LEDControl FAILED");
	} else {
		DBG_PRINT(SENSOR, "Init: LEDControl OK");
	}

	DBG_PRINT(SENSOR, "SensorControl_Init complete (temp=%s, pH=%s)",
			sensor_ctrl.temp_initialized ? "OK" : "FAIL",
			sensor_ctrl.ph_initialized ? "OK" : "FAIL");
	return true;
}

void SensorControl_Process(void) {
	if (!sensor_ctrl.initialized) {
		return;
	}

	/* ── Always tick sensor drivers (they need processing regardless) ── */

	/* Temperature sensor: check for offset writes, then process */
	if (sensor_ctrl.temp_initialized) {
		int16_t offset = ProcImg_GetTempOffset();
		if (offset != sensor_ctrl.last_applied_offset) {
			Temp_SetOffset(offset);
			sensor_ctrl.last_applied_offset = offset;
		}
		Temp_Process();
	}

	/* pH sensor: feed temperature compensation, then process */
	if (sensor_ctrl.ph_initialized) {
		if (sensor_ctrl.temp_initialized
				&& Temp_GetState() == TEMP_STATE_READY) {
			pH_SetTemperature(Temp_GetValue());
		}
		pH_Process();
	}

	/* ── NMT gate: if not OPERATIONAL, force DISABLED ──────────────── */
	if (MY_NMT_STATE != NMTSTATE_OP) {
		if (sensor_ctrl.current_state != SENSOR_STATE_DISABLED) {
			DBG_STATE(SENSOR, "NMT not OP (0x%02X) -> DISABLED", MY_NMT_STATE);
			sensor_ctrl.current_state = SENSOR_STATE_DISABLED;
		}
		/* Still update process image so SDO reads reflect sensor data */
		SensorControl_UpdateProcessImage();
		return;
	}

	/* ── Process ControlWord (rising-edge detection) ───────────────── */
	SensorControl_ProcessControlWord(ProcImg_GetControlWord());

	/* ── CiA 404 State Machine ─────────────────────────────────────── */
	switch (sensor_ctrl.current_state) {

	case SENSOR_STATE_DISABLED:
		/* Transition to WARMING_UP when NMT is Operational */
		sensor_ctrl.warmup_start_ms = HAL_GetTick();
		sensor_ctrl.current_state = SENSOR_STATE_WARMING_UP;
		DBG_STATE(SENSOR, "DISABLED -> WARMING_UP (2s warmup)");
		break;

	case SENSOR_STATE_WARMING_UP: {
		uint32_t elapsed = HAL_GetTick() - sensor_ctrl.warmup_start_ms;
		if (elapsed >= WARMUP_TIME_MS) {
			/* Check if at least one sensor is ready */
			bool temp_ready = sensor_ctrl.temp_initialized
					&& Temp_GetState() == TEMP_STATE_READY;
			bool ph_ready = sensor_ctrl.ph_initialized
					&& pH_GetState() == PH_STATE_READY;

			if (temp_ready || ph_ready) {
				sensor_ctrl.current_state = SENSOR_STATE_RUNNING;
				DBG_STATE(SENSOR, "WARMING_UP -> RUNNING (temp=%s pH=%s)",
						temp_ready ? "ready" : "wait",
						ph_ready ? "ready" : "wait");
			} else {
				sensor_ctrl.current_state = SENSOR_STATE_FAULT;
				DBG_ERROR(SENSOR,
						"WARMING_UP -> FAULT (no sensors ready after warmup)");
			}
		}
		break;
	}

	case SENSOR_STATE_RUNNING:
		/* Check for calibration commands from master (0x2200) */
		if (sensor_ctrl.ph_initialized) {
			SensorControl_CheckCalibrationCommand();
		}

		/* Delta-threshold TPDO triggering */
		SensorControl_CheckDeltaTrigger();

		/* Check for dual sensor failure → FAULT */
		{
			bool temp_error = sensor_ctrl.temp_initialized
					&& Temp_GetState() == TEMP_STATE_ERROR;
			bool ph_error = sensor_ctrl.ph_initialized
					&& pH_GetState() == PH_STATE_ERROR;

			if (temp_error && ph_error) {
				sensor_ctrl.current_state = SENSOR_STATE_FAULT;
				DBG_ERROR(SENSOR, "RUNNING -> FAULT (both sensors in error)");
			}
			/* Single sensor failure: log but don't fault */
		}
		break;

	case SENSOR_STATE_FAULT:
		/* Wait for ControlWord fault reset (handled in ProcessControlWord) */
		break;
	}

	/* ── Update process image with latest readings + StatusWord ─────── */
	SensorControl_UpdateProcessImage();

	/* ── Process application-level LED control (reads mode from OD 0x2000) ── */
	LEDControl_Process();
}

bool SensorControl_IsOperational(void) {
	return sensor_ctrl.current_state == SENSOR_STATE_RUNNING;
}

void SensorControl_EmergencyStop(void) {
	if (!sensor_ctrl.initialized) {
		return;
	}
	sensor_ctrl.current_state = SENSOR_STATE_FAULT;
	DBG_ERROR(SENSOR, "EmergencyStop called");
}

void SensorControl_Reset(void) {
	if (!sensor_ctrl.initialized) {
		return;
	}
	sensor_ctrl.current_state = SENSOR_STATE_DISABLED;
	sensor_ctrl.last_control_word = 0;
	sensor_ctrl.last_cal_command = PH_CAL_CMD_NONE;
	sensor_ctrl.last_tpdo_ph = 0;
	sensor_ctrl.last_tpdo_temp = 0;
	sensor_ctrl.last_tpdo_status = 0;
	sensor_ctrl.last_status_word = 0;

	/* Clear sensor errors so they can retry */
	if (sensor_ctrl.temp_initialized) {
		Temp_ClearError();
	}
	if (sensor_ctrl.ph_initialized) {
		pH_ClearError();
	}

	DBG_STATE(SENSOR, "SensorControl_Reset: state -> DISABLED");
}

void SensorControl_RegisterMCOEvents(void) {
	MCO_Events_Register(SensorControl_HandleMCOEvent);
	DBG_PRINT(SENSOR, "Registered as MCO event listener");
}

void SensorControl_RunDiagnostics(void) {
	if (!sensor_ctrl.initialized) {
		return;
	}

	uint32_t now = HAL_GetTick();
	if (now - sensor_ctrl.last_diag_ms < 5000) {
		return; /* Throttle to every 5 seconds */
	}
	sensor_ctrl.last_diag_ms = now;

	/* Temperature diagnostics */
	int16_t temp = Temp_GetValue();
	uint8_t tq = Temp_GetSignalQuality();
	Temp_State_t ts = Temp_GetState();

	/* pH diagnostics */
	uint16_t ph = pH_GetValue();
	uint8_t pq = pH_GetSignalQuality();
	pH_State_t ps = pH_GetState();

	/* StatusWord */
	uint16_t sw = sensor_ctrl.last_status_word;

	DBG_PRINT(SENSOR,
			"DIAG: state=%d SW=0x%04X | temp=%d.%d C q=%u%% s=%d | pH=%u.%02u q=%u%% s=%d",
			sensor_ctrl.current_state, sw, temp / 10,
			(temp >= 0 ? temp : -temp) % 10, tq, ts, ph / 100, ph % 100, pq,
			ps);
}

SensorState_t SensorControl_GetState(void) {
	return sensor_ctrl.current_state;
}

/* Private functions ---------------------------------------------------------*/

/**
 * @brief  Generate CiA 404 StatusWord from current sensor states
 * @retval 16-bit StatusWord for process image (0x6041)
 */
static uint16_t SensorControl_GenerateStatusWord(void) {
	uint16_t sw = 0;

	/* Bit 0: pH sensor ready (active, not idle/error) */
	if (PH_IS_ACTIVE()) {
		sw |= SW_PH_READY;
	}

	/* Bit 1: Temperature sensor ready (active, not idle/error) */
	if (TEMP_IS_ACTIVE()) {
		sw |= SW_TEMP_READY;
	}

	/* Bit 2: Calibration in progress */
	if (sensor_ctrl.ph_initialized && pH_GetState() == PH_STATE_CALIBRATING) {
		sw |= SW_CALIBRATING;
	}

	/* Bit 3: General fault */
	if (sensor_ctrl.current_state == SENSOR_STATE_FAULT) {
		sw |= SW_FAULT;
	}

	/* Bit 4: pH sensor fault */
	if (sensor_ctrl.ph_initialized && pH_GetState() == PH_STATE_ERROR) {
		sw |= SW_PH_FAULT;
	}

	/* Bit 5: Temperature sensor fault */
	if (sensor_ctrl.temp_initialized && Temp_GetState() == TEMP_STATE_ERROR) {
		sw |= SW_TEMP_FAULT;
	}

	/* Bit 6: Warming up */
	if (sensor_ctrl.current_state == SENSOR_STATE_WARMING_UP) {
		sw |= SW_WARMING_UP;
	}

	/* Bit 9: Remote (NMT Operational) */
	if (MY_NMT_STATE == NMTSTATE_OP) {
		sw |= SW_REMOTE;
	}

	return sw;
}

/**
 * @brief  Process ControlWord with rising-edge detection
 * @param  control_word  Current ControlWord read from process image (0x6040)
 * @note   Detects rising edges (0→1 transitions) and dispatches:
 *         - Bit 7: Fault reset → clear errors, state → DISABLED
 *         - Bit 0: pH calibration → read command from 0x2200, execute
 *         - Bit 1: Temp calibration → read offset from 0x2210, apply
 */
static void SensorControl_ProcessControlWord(uint16_t control_word) {
	/* Detect rising edges */
	uint16_t rising = control_word & ~sensor_ctrl.last_control_word;
	sensor_ctrl.last_control_word = control_word;

	if (rising == 0) {
		return; /* No new edges */
	}

	/* Priority 1: Fault reset (bit 7) */
	if (rising & CW_FAULT_RESET) {
		DBG_STATE(SENSOR, "ControlWord: FAULT_RESET");
		sensor_ctrl.current_state = SENSOR_STATE_DISABLED;

		/* Clear sensor errors */
		if (sensor_ctrl.temp_initialized) {
			Temp_ClearError();
		}
		if (sensor_ctrl.ph_initialized) {
			pH_ClearError();
		}
		return; /* Fault reset takes priority */
	}

	/* Priority 2: pH calibration (bit 0) */
	if (rising & CW_START_PH_CAL) {
		if (sensor_ctrl.ph_initialized) {
			uint8_t cmd = ProcImg_GetCalibrationCommand();
			DBG_PRINT(CAL, "ControlWord: START_PH_CAL, cmd=0x%02X", cmd);

			ProcImg_SetCalibrationStatus(PH_CAL_STATUS_BUSY);
			HAL_StatusTypeDef result = pH_Calibrate(cmd);

			if (result == HAL_OK) {
				ProcImg_SetCalibrationStatus(PH_CAL_STATUS_OK);
				DBG_PRINT(CAL, "pH cal OK");
			} else {
				ProcImg_SetCalibrationStatus(PH_CAL_STATUS_FAIL);
				DBG_ERROR(CAL, "pH cal FAILED");
			}
		}
	}

	/* Priority 3: Temp calibration / offset (bit 1) */
	if (rising & CW_START_TEMP_CAL) {
		if (sensor_ctrl.temp_initialized) {
			int16_t offset = ProcImg_GetTempOffset();
			Temp_SetOffset(offset);
			sensor_ctrl.last_applied_offset = offset;
			DBG_PRINT(CAL, "ControlWord: TEMP_CAL, offset=%d", offset);
		}
	}
}

/**
 * @brief  Check delta thresholds and trigger TPDOs if exceeded
 * @note   Compares current pH/temp/status against last TPDO'd values.
 *         TPDO1 (0x184): pHValue + Temperature (measurement data)
 *         TPDO2 (0x284): SensorStatus + Quality + Error + StatusWord
 */
static void SensorControl_CheckDeltaTrigger(void) {
	bool trigger_tpdo1 = false;
	bool trigger_tpdo2 = false;

	/* ── TPDO1: pH + Temperature delta check ──────────────────────── */
	uint16_t cur_ph = pH_GetValue();
	int16_t cur_temp = Temp_GetValue();

	uint16_t ph_threshold = ProcImg_GetpHDeltaThreshold();
	int16_t temp_threshold = ProcImg_GetTempDeltaThreshold();

	/* pH delta (unsigned comparison) */
	if (ph_threshold > 0) {
		uint16_t ph_diff;
		if (cur_ph >= sensor_ctrl.last_tpdo_ph) {
			ph_diff = cur_ph - sensor_ctrl.last_tpdo_ph;
		} else {
			ph_diff = sensor_ctrl.last_tpdo_ph - cur_ph;
		}
		if (ph_diff >= ph_threshold) {
			trigger_tpdo1 = true;
		}
	}

	/* Temperature delta (signed, compare absolute difference) */
	if (temp_threshold > 0) {
		int16_t temp_diff = cur_temp - sensor_ctrl.last_tpdo_temp;
		if (temp_diff < 0)
			temp_diff = -temp_diff;
		if (temp_diff >= temp_threshold) {
			trigger_tpdo1 = true;
		}
	}

	if (trigger_tpdo1) {
		MCO_TriggerTPDO(1); /* TPDO1 (1-indexed per MCO API) */
		sensor_ctrl.last_tpdo_ph = cur_ph;
		sensor_ctrl.last_tpdo_temp = cur_temp;
		DBG_PRINT_V(SENSOR, "TPDO1 delta trigger: pH=%u temp=%d", cur_ph,
				cur_temp);
	}

	/* ── TPDO2: SensorStatus + StatusWord delta check ─────────────── */
	uint8_t status_threshold = ProcImg_GetStatusDeltaThreshold();
	uint16_t cur_sw = sensor_ctrl.last_status_word;

	/* Build SensorStatus bitfield for comparison (must match UpdateProcessImage) */
	uint8_t cur_status = 0;
	if (PH_IS_ACTIVE()) {
		cur_status |= 0x01; /* bit 0: pH OK */
	}
	if (TEMP_IS_ACTIVE()) {
		cur_status |= 0x02; /* bit 1: temp OK */
	}
	if (sensor_ctrl.ph_initialized && pH_GetState() == PH_STATE_CALIBRATING) {
		cur_status |= 0x04; /* bit 2: calibrating */
	}
	if (sensor_ctrl.current_state == SENSOR_STATE_FAULT) {
		cur_status |= 0x08; /* bit 3: fault */
	}

	/* Check status byte change */
	if (status_threshold > 0) {
		uint8_t status_diff;
		if (cur_status >= sensor_ctrl.last_tpdo_status) {
			status_diff = cur_status - sensor_ctrl.last_tpdo_status;
		} else {
			status_diff = sensor_ctrl.last_tpdo_status - cur_status;
		}
		if (status_diff >= status_threshold) {
			trigger_tpdo2 = true;
		}
	}

	/* Also trigger TPDO2 if StatusWord changed (any bit flip).
	 * Note: last_status_word reflects the value from the previous cycle's
	 * UpdateProcessImage(), so cur_sw here is still the old value.
	 * We compare current computed status against what was last TPDO'd. */
	if (cur_status != sensor_ctrl.last_tpdo_status) {
		trigger_tpdo2 = true;
	}

	if (trigger_tpdo2) {
		MCO_TriggerTPDO(2); /* TPDO2 (1-indexed per MCO API) */
		sensor_ctrl.last_tpdo_status = cur_status;
		DBG_PRINT_V(SENSOR, "TPDO2 delta trigger: status=0x%02X SW=0x%04X",
				cur_status, cur_sw);
	}
}

/**
 * @brief  Check for calibration commands written by master via SDO (0x2200)
 * @note   Detects rising edge (command change from NONE) and dispatches.
 *         Master writes command byte, firmware executes and reports status
 *         via 0x2201. Master must write 0x00 before next command.
 */
static void SensorControl_CheckCalibrationCommand(void) {
	uint8_t cmd = ProcImg_GetCalibrationCommand();

	/* Only trigger on change from last seen value */
	if (cmd == sensor_ctrl.last_cal_command) {
		return;
	}
	sensor_ctrl.last_cal_command = cmd;

	/* Ignore transition back to NONE (master clearing the command) */
	if (cmd == PH_CAL_CMD_NONE) {
		return;
	}

	DBG_PRINT(CAL, "Cal command received: 0x%02X", cmd);

	/* Set status to BUSY */
	ProcImg_SetCalibrationStatus(PH_CAL_STATUS_BUSY);

	/* Execute calibration */
	HAL_StatusTypeDef result = pH_Calibrate(cmd);

	/* Update calibration status */
	if (result == HAL_OK) {
		ProcImg_SetCalibrationStatus(PH_CAL_STATUS_OK);
		DBG_PRINT(CAL, "Cal command 0x%02X completed OK", cmd);
	} else {
		ProcImg_SetCalibrationStatus(PH_CAL_STATUS_FAIL);
		DBG_ERROR(CAL, "Cal command 0x%02X FAILED", cmd);
	}
}

/**
 * @brief  Write current sensor readings + status into MCO process image
 * @note   Called every SensorControl_Process() iteration.
 *         The MCO stack serves these values to SDO reads and TPDO mappings.
 */
static void SensorControl_UpdateProcessImage(void) {
	/* ── Temperature objects ──────────────────────────────────── */
	ProcImg_SetTemperature(Temp_GetValue());
	ProcImg_SetTempSensorStatus((uint8_t) Temp_GetState());

	/* Temp quality: only update process image if change > hysteresis */
	{
		uint8_t tq = Temp_GetSignalQuality();
		uint8_t diff =
				(tq >= sensor_ctrl.pimg_temp_quality) ?
						(tq - sensor_ctrl.pimg_temp_quality) :
						(sensor_ctrl.pimg_temp_quality - tq);
		if (diff >= QUALITY_HYSTERESIS) {
			sensor_ctrl.pimg_temp_quality = tq;
			ProcImg_SetTempSignalQuality(tq);
		}
	}

	/* ── pH objects ───────────────────────────────────────────── */
	ProcImg_SetpHValue(pH_GetValue());
	ProcImg_SetpHMillivolts(pH_GetMillivolts());
	ProcImg_SetpHSensorStatus((uint8_t) pH_GetState());
	ProcImg_SetCalibrationMode((uint8_t) pH_GetCalMode());

	/* pH quality: only update process image if change > hysteresis */
	{
		uint8_t pq = pH_GetSignalQuality();
		uint8_t diff =
				(pq >= sensor_ctrl.pimg_ph_quality) ?
						(pq - sensor_ctrl.pimg_ph_quality) :
						(sensor_ctrl.pimg_ph_quality - pq);
		if (diff >= QUALITY_HYSTERESIS) {
			sensor_ctrl.pimg_ph_quality = pq;
			ProcImg_SetpHSignalQuality(pq);
		}
	}

	/* ── Electrode status (0x2220) ────────────────────────────── */
	ProcImg_SetElectrodeStatus(pH_GetElectrodeStatus());

	/* ── StatusWord (0x6041) ──────────────────────────────────── */
	uint16_t sw = SensorControl_GenerateStatusWord();
	ProcImg_SetStatusWord(sw);
	sensor_ctrl.last_status_word = sw;

	/* ── SensorStatus bitfield (0x2300) ──────────────────────── */
	uint8_t sensor_status = 0;
	if (PH_IS_ACTIVE()) {
		sensor_status |= 0x01; /* bit 0: pH OK */
	}
	if (TEMP_IS_ACTIVE()) {
		sensor_status |= 0x02; /* bit 1: temp OK */
	}
	if (sensor_ctrl.ph_initialized && pH_GetState() == PH_STATE_CALIBRATING) {
		sensor_status |= 0x04; /* bit 2: calibrating */
	}
	if (sensor_ctrl.current_state == SENSOR_STATE_FAULT) {
		sensor_status |= 0x08; /* bit 3: fault */
	}
	ProcImg_SetSensorStatus(sensor_status);

	/* ── ErrorRegister (0x1001) ──────────────────────────────── */
	uint8_t err_reg = 0;
	if (sensor_ctrl.current_state == SENSOR_STATE_FAULT) {
		err_reg |= 0x01; /* generic error */
	}
	if ((sensor_ctrl.ph_initialized && pH_GetState() == PH_STATE_ERROR)
			|| (sensor_ctrl.temp_initialized
					&& Temp_GetState() == TEMP_STATE_ERROR)) {
		err_reg |= 0x20; /* device-specific error */
	}
	ProcImg_SetErrorRegister(err_reg);
}

/**
 * @brief Handle MCO events (same pattern as pump's MotorControl)
 */
static void SensorControl_HandleMCOEvent(const MCO_Event_t *event) {
	switch (event->type) {
	case MCO_EVENT_FATAL_ERROR:
		DBG_ERROR(SENSOR, "MCO fatal error: code=%u", event->error_code);
		SensorControl_EmergencyStop();
		break;

	case MCO_EVENT_COMM_RESET:
		if (event->init_result) {
			DBG_PRINT(SENSOR,
					"COMM_RESET: stack init OK, initializing sensors");
			if (!SensorControl_Init()) {
				DBG_ERROR(SENSOR, "SensorControl_Init failed");
			}
		} else {
			DBG_ERROR(SENSOR, "COMM_RESET: stack init FAILED");
		}
		break;

	case MCO_EVENT_NMT_CHANGE:
		DBG_STATE(SENSOR, "NMT change: state=0x%02X", event->nmt_state);
		/* NMT gate in Process() handles state transitions.
		 * No explicit Reset here — avoids clearing state prematurely
		 * when the NMT gate will handle it next cycle. */
		break;

	case MCO_EVENT_HEARTBEAT_LOST:
		DBG_ERROR(SENSOR, "Heartbeat lost: node=%u", event->node_id);
		SensorControl_EmergencyStop();
		break;
	}
}
