/**************************************************************************
MODULE:    USER_OD - Here: STANDARD USAGE OF GENERATED OD TABLES
CONTAINS:  MicroCANopen Object Dictionary and Process Image implementation
COPYRIGHT: Embedded Systems Academy (EmSA) 2002-2024
           All rights reserved. esacademy.com
DISCLAIM:  Read and understand our disclaimer before using this code!
           www.esacademy.com/disclaim.htm
           This software was written in accordance to the guidelines at
           www.esacademy.com/software/softwarestyleguide.pdf
LICENSE:   THIS IS THE COMMERCIAL VERSION OF MICRO CANOPEN PLUS
           ONLY USERS WHO PURCHASED A LICENSE MAY USE THIS SOFTWARE
           See file license_commercial_plus.txt or
           www.microcanopen.com/license_commercial_plus.txt
VERSION:   7.17, EmSA 04-MAR-24
           $LastChangedDate: 2024-03-04 12:55:21 +0100 (Mon, 04 Mar 2024) $
           $LastChangedRevision: 5559 $
***************************************************************************/ 

#include "mcop_inc.h"

#include "entriesandreplies.h"


/**************************************************************************
GLOBAL VARIABLES
***************************************************************************/ 

uint8_t MEM_PROC gProcImg[PROCIMG_SIZE] = 
  PIMGDEFAULTS
#if defined(PIMGDEFAULTS2)
  PIMGDEFAULTS2
#endif
#if defined(PIMGDEFAULTS3)
  PIMGDEFAULTS3
#endif
#if defined(PIMGDEFAULTS4)
  PIMGDEFAULTS4
#endif
#if defined(PIMGDEFAULTS5)
  PIMGDEFAULTS5
#endif
#if defined(PIMGDEFAULTS6)
  PIMGDEFAULTS6
#endif
#if defined(PIMGDEFAULTS7)
  PIMGDEFAULTS7
#endif
#if defined(PIMGDEFAULTS8)
  PIMGDEFAULTS8
#endif
#if defined(PIMGDEFAULTS9)
  PIMGDEFAULTS9
#endif
#if defined(PIMGDEFAULTS10)
  #error Did not expect so many PI default initializers, add all "PIMGDEFAULTSn" initializers here
#endif
;


// Table with SDO Responses for read requests to OD
uint8_t MEM_CONST gSDOResponseTable[] = {
// Each Row has 8 Bytes:
// Command Specifier for SDO Response (1 byte)
//   bits 2+3 contain: '4' – {number of data bytes}
// Object Dictionary Index (2 bytes, low first)
// Object Dictionary Subindex (1 byte)
// Data (4 bytes, lowest bytes first)

  // Include file generated by CANopen Architect
  SDOREPLY_ENTRIES
#if defined(SDOREPLY_ENTRIES2)
  SDOREPLY_ENTRIES2
#endif
#if defined(SDOREPLY_ENTRIES3)
  SDOREPLY_ENTRIES3
#endif
#if defined(SDOREPLY_ENTRIES4)
  SDOREPLY_ENTRIES4
#endif
#if defined(SDOREPLY_ENTRIES5)
  SDOREPLY_ENTRIES5
#endif
#if defined(SDOREPLY_ENTRIES6)
  SDOREPLY_ENTRIES6
#endif
#if defined(SDOREPLY_ENTRIES7)
  SDOREPLY_ENTRIES7
#endif
#if defined(SDOREPLY_ENTRIES8)
  SDOREPLY_ENTRIES8
#endif
#if defined(SDOREPLY_ENTRIES9)
  SDOREPLY_ENTRIES9
#endif
#if defined(SDOREPLY_ENTRIES10)
  #error Did not expect so many OD entries, add all "SDOREPLY_ENTRIESn" initializers here
#endif

  // End-of-table marker
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
};


// Table with Object Dictionary entries to process Data
OD_PROCESS_DATA_ENTRY MEM_CONST gODProcTable[] = 
{
  // Include automatically generated files from CANopenArchitect EDS
  ODENTRY_ENTRIES
#if defined(ODENTRY_ENTRIES2)
  ODENTRY_ENTRIES2
#endif
#if defined(ODENTRY_ENTRIES3)
  ODENTRY_ENTRIES3
#endif
#if defined(ODENTRY_ENTRIES4)
  ODENTRY_ENTRIES4
#endif
#if defined(ODENTRY_ENTRIES4)
  ODENTRY_ENTRIES4
#endif
#if defined(ODENTRY_ENTRIES5)
  ODENTRY_ENTRIES5
#endif
#if defined(ODENTRY_ENTRIES6)
  ODENTRY_ENTRIES6
#endif
#if defined(ODENTRY_ENTRIES7)
  ODENTRY_ENTRIES7
#endif
#if defined(ODENTRY_ENTRIES8)
  ODENTRY_ENTRIES8
#endif
#if defined(ODENTRY_ENTRIES9)
  ODENTRY_ENTRIES9
#endif
#if defined(ODENTRY_ENTRIES10)
  #error Did not expect so many OD entries, add all "ODENTRY_ENTRIESn" initializers here
#endif

#if defined(P100001_Device_Type_1)
  // Special entry to deliver CANopen-style object [1000h,0]
  ODENTRY(0x1000, 0x00, 4 + ODRD, P100001_Device_Type_1),
#endif

  // End-of-table marker
  ODENTRY(0xFFFF,0xFF,0xFF,0xFF)
};


#if USE_EXTENDED_SDO
// Table with generic entries to memory
OD_GENERIC_DATA_ENTRY MEM_CONST gODGenericTable[] = 
{
  ODGENTRY_ENTRIES
#if defined(ODGENTRY_ENTRIES2)
  ODGENTRY_ENTRIES2
#endif
#if defined(ODGENTRY_ENTRIES3)
  ODGENTRY_ENTRIES3
#endif
#if defined(ODGENTRY_ENTRIES4)
  ODGENTRY_ENTRIES4
#endif
#if defined(ODGENTRY_ENTRIES5)
  ODGENTRY_ENTRIES5
#endif
#if defined(ODGENTRY_ENTRIES6)
  ODGENTRY_ENTRIES6
#endif
#if defined(ODGENTRY_ENTRIES7)
  ODGENTRY_ENTRIES7
#endif
#if defined(ODGENTRY_ENTRIES8)
  ODGENTRY_ENTRIES8
#endif
#if defined(ODGENTRY_ENTRIES9)
  ODGENTRY_ENTRIES9
#endif
#if defined(ODGENTRY_ENTRIES10)
  #error Did not expect so many OD entries, add all "ODGENTRY_ENTRIESn" initializers here
#endif

  ODGENTRYP(0xFFFF,0xFF,0xFF,0xFFFF,0xFFFF)
};
#endif // USE_EXTENDED_SDO


// Extended tables for CANopen FD

#if defined(USE_CANOPEN_FD) && USE_CANOPEN_FD

#if !defined(OD_ID_LIST) || !defined(OD_ID_TYPE) || !defined(OD_ID_TABLELOCATION)
#error Extended OD information is missing - CANopen Architect version 5.90 or higher required
#endif

MEM_CONST uint32_t gODIDList[] = {
  OD_ID_LIST
#if defined(OD_ID_LIST2)
  OD_ID_LIST2
#endif
#if defined(OD_ID_LIST3)
  OD_ID_LIST3
#endif
#if defined(OD_ID_LIST4)
  OD_ID_LIST4
#endif
#if defined(OD_ID_LIST5)
  OD_ID_LIST5
#endif
#if defined(OD_ID_LIST6)
  OD_ID_LIST6
#endif
#if defined(OD_ID_LIST7)
  OD_ID_LIST7
#endif
#if defined(OD_ID_LIST8)
  OD_ID_LIST8
#endif
#if defined(OD_ID_LIST9)
  OD_ID_LIST9
#endif
#if defined(OD_ID_LIST10)
  #error Did not expect so many OD entries, add all "OD_ID_LISTn" initializers here
#endif
};
const int gSizeofgODIDList = sizeof(gODIDList) / sizeof(uint32_t);

MEM_CONST uint8_t gODIDType[] = {
  OD_ID_TYPE
#if defined(OD_ID_TYPE2)
  OD_ID_TYPE2
#endif
#if defined(OD_ID_TYPE3)
  OD_ID_TYPE3
#endif
#if defined(OD_ID_TYPE4)
  OD_ID_TYPE4
#endif
#if defined(OD_ID_TYPE5)
  OD_ID_TYPE5
#endif
#if defined(OD_ID_TYPE6)
  OD_ID_TYPE6
#endif
#if defined(OD_ID_TYPE7)
  OD_ID_TYPE7
#endif
#if defined(OD_ID_TYPE8)
  OD_ID_TYPE8
#endif
#if defined(OD_ID_TYPE9)
  OD_ID_TYPE9
#endif
#if defined(OD_ID_TYPE10)
#error Did not expect so many OD entries, add all "OD_ID_TYPEn" initializers here
#endif
};

MEM_CONST ODLocationType gODIDLocation[] = {
  OD_ID_TABLELOCATION
#if defined(OD_ID_TABLELOCATION2)
  OD_ID_TABLELOCATION2
#endif
#if defined(OD_ID_TABLELOCATION3)
  OD_ID_TABLELOCATION3
#endif
#if defined(OD_ID_TABLELOCATION4)
  OD_ID_TABLELOCATION4
#endif
#if defined(OD_ID_TABLELOCATION5)
  OD_ID_TABLELOCATION5
#endif
#if defined(OD_ID_TABLELOCATION6)
  OD_ID_TABLELOCATION6
#endif
#if defined(OD_ID_TABLELOCATION7)
  OD_ID_TABLELOCATION7
#endif
#if defined(OD_ID_TABLELOCATION8)
  OD_ID_TABLELOCATION8
#endif
#if defined(OD_ID_TABLELOCATION9)
  OD_ID_TABLELOCATION9
#endif
#if defined(OD_ID_TABLELOCATION10)
#error Did not expect so many OD entries, add all "OD_ID_TABLELOCATIONn" initializers here
#endif
};

#endif // USE_CANOPEN_FD

/**************************************************************************
END-OF-FILE 
***************************************************************************/ 
